fix(typedefs): Add type for autoEnd on LogConfig.
cypress-io/cypress pull request #14220
Opened 2020-12-17 16:30 UTC by linkel

- Closes #9590

### User facing changelog

Add type for autoEnd on LogConfig.

### Additional details

I wanted to make a small contribution to Cypress and get the dev environment set up. The only change I made was adding the type.

#### Side notes about Cypress development:
After I made the change, I built the package and built the binary, and in my test project I pointed to the package in package.json and had to copy paste the binary into my cypress cache in order to successfully `yarn` on my test project, otherwise it would try to download the binary online and fail since the version didn't exist. 

I also had to downgrade my node version to avoid a build error in node-sass. 

### How has the user experience changed?
Now it doesn't produce a type error and shows autoEnd correctly typed. 

![image](https://user-images.githubusercontent.com/7061807/102514176-0708c800-4041-11eb-9c3f-e10f11de4303.png)

### PR Tasks

- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2020-12-17 16:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=14220) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=14220) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=14220) it.</sub>

2020-12-17 16:35 UTC, linkel commented
Are the three circleci failures expected?

2020-12-18 03:20 UTC, jennifer-shehane commented
@linkel Yah those are some flaky tests.

2020-12-18 03:28 UTC, jennifer-shehane requested changes
It would be nice to have a comment here explaining what autoEnd is for, like the other props have. 

I think this is only used to set autoEnd: false for `.pause()` command correct? The idea is that the command doesn't 'end' exactly. 

Maybe understanding your use case for why you need to use this prop would be helpful.

2021-01-13 08:57 UTC, jennifer-shehane commented
@linkel Do you still have time to address the changes requested in this PR? We will have to close this PR due to inactivity otherwise.

2021-02-09 19:24 UTC, flotwig requested changes

2021-02-09 19:24 UTC, flotwig commented on cli/types/cypress.d.ts
> +    autoEnd: boolean
Can you add a typedoc for this?

2021-02-12 20:00 UTC, emilgoldsmith commented
#15076 was now merged so this should be able to be closed

2021-02-12 20:09 UTC, bahmutov commented
closing as duplicate

2021-02-12 20:09 UTC, closed without merging