Add crossword example app (CT-147)
cypress-io/cypress pull request #14249
Opened 2020-12-19 01:12 UTC by lmiller1990

Closes: https://cypress-io.atlassian.net/browse/CT-147

Some tests are failing. 

- tests related to `cy.route` etc. Related: https://cypress-io.atlassian.net/browse/CT-170
- tests using Cypress.command. Related: https://cypress-io.atlassian.net/browse/CT-181

Also for whatever reason we do not automatically find the webpack config for Vue CLI projects, it seems? I get 

```
TypeError: registeredEvents[event] is not a function
    at Object.execute (/Users/lachlan/code/work/cypress/packages/server/lib/plugins/index.js:210:33)
    at Object.start (/Users/lachlan/code/work/cypress/packages/server/lib/plugins/devserver.js:26:20)
    at /Users/lachlan/code/work/cypress/packages/server-ct/src/project-ct.ts:137:44
From previous event:
    at /Users/lachlan/code/work/cypress/packages/server-ct/src/project-ct.ts:136:16
```

When I do not specify a `webpack.config.js` inside `plugins/index.js`.

2020-12-19 01:15 UTC, JessicaSachs commented
The automatic resolution of the vue CLI configuration was removed when we swapped the `@cypress/vue` webpack implementation out for our existing webpack-dev-server. We used to use a library called find-webpack by Gleb. Essentially it just hunted for the path for the nearest Vue CLI / webpack configuration and required it by default.

2020-12-19 01:17 UTC, lmiller1990 commented
Ok @JessicaSachs that's good to know, let's add that back in. I will make a ticket for this and add it to the next sprint.

2020-12-19 01:21 UTC, JessicaSachs commented
If we decide to embed the example into the repository, we should nohoist this package in the root package.json so that we do not require all developers to install the example dependencies.

An alternative approach is to allow the crossword example repository to be external and instead to make it work by doing a `git clone` in the project and then performing setup instructions there.

The pro of a standalone approach will be that the example is easily consumable by others. A nested example is more complex to use as a demo. For context, there have been convos in the past about how best to work with example applications that we intend to distribute as demos in Documentation, etc...

That being said, I think I am okay with embedding it into the repo for now.  It’s just something we should think about.

2020-12-19 01:25 UTC, lmiller1990 commented
Standalone approach sounds best. How about we move to that once all the tests pass? Having it in the monorepo makes it really easy to update, which may happen a lot during the next few weeks of development. Once it is stable we can move to a standalone repo (this will be prior to merging into develop).

2020-12-19 01:26 UTC, JessicaSachs commented on packages/server-ct/crossword-example/webpack.config.js
> +const VueLoaderPlugin = require('vue-loader/lib/plugin')
Can we delete this file and instead use Vue CLI in the cypress/plugin file? It’s confusing because vue.config.js isn’t being used

2020-12-19 01:28 UTC, JessicaSachs requested changes
In general, I’d like to resolve the multiple webpack configs, fix it so we are nohoist-ing the dependencies, and then I’d like to delete all of the messy comments.

2020-12-19 01:29 UTC, JessicaSachs commented
> Standalone approach sounds best. How about we move to that once all the tests pass? Having it in the monorepo makes it really easy to update, which may happen a lot during the next few weeks of development. Once it is stable we can move to a standalone repo (this will be prior to merging into develop).

Yeah, I’m fine with the approach + timing . If anything, I’d like to transfer the original repo to cypress org when we do that. No sense in having two of them.

2020-12-19 01:54 UTC, lmiller1990 commented
@JessicaSachs I am not entirely clear on what you mean by no-host. Running `yarn lerna bootstrap` does not cause the dependencies for `crossword-example` to be installed. Is that what you mean?

I will look into the webpack config and `find-webpack`.

2020-12-20 12:55 UTC, lmiller1990 commented
I updated it to use `find-webpack` @JessicaSachs - let me know if you see a better place/way to do this.

I also had to do this: https://github.com/cypress-io/cypress/pull/14249/files#diff-920a0d948232476b9bae96e6440d237d1316323fd09cb896dc74f3ed86aba6cf

```
const { startDevServer } = require('@cypress/webpack-dev-server')

module.exports = (on, config) => {
  on('devserver:start', (options) => startDevServer(options))

  return config
}
```

If this is not in `packages/server-ct/crossword-example/cypress/plugins/index.js`, the server errors out - `cypress/webpack-dev-server` expects a `'devserver:start'` to be registered. I wonder if this is necessary long term - we should be able to do this internally somewhere (not sure where).

2020-12-21 20:59 UTC, JessicaSachs approved these changes
This looks good!

2020-12-21 21:02 UTC, merged