ci: create issue mark duplicate
cypress-io/cypress pull request #14450
Opened 2021-01-07 12:56 UTC by xrkffgg

### User facing changelog

None

### Additional details

#### mark duplicate

ref: https://github.com/cypress-io/cypress/issues/14282 https://github.com/cypress-io/cypress/issues/9530 https://github.com/cypress-io/cypress/issues/8933

Now when you type `Duplicate of #xxx`, the GitHub Actions will help you add then `type: duplicate` label auto.

At the same time, it will close the issue if you just click `Comment`. And will remove the `stage: awaiting response` label if the issue has. This `remove-labels` support multiple, but I don't know what you need, you can tell me.

### How has the user experience changed?
None

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [x] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-01-07 12:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=14450) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=14450) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=14450) it.</sub>

2021-01-07 13:28 UTC, xrkffgg commented on .github/workflows/issue-labeled.yml
> +      - name: help wanted
```suggestion
      - name: needs information
```

2021-01-08 09:10 UTC, jennifer-shehane requested changes
@bahmutov thoughts? 

I don't think that I'd like the GitHub action to auto-comment. I don't always want to comment at the time of adding the 'needs:information' label. I usually type in some more specific info in my comment that I'd also like. Also, not sure how the comment shows up, it shows as commenting by GitHub Action? 

The duplicate action seems fine though.

2021-01-08 09:23 UTC, xrkffgg commented
You can see in https://github.com/xrkffgg/test-ci/issues/48. 

![image](https://user-images.githubusercontent.com/29775873/103997482-16a9a580-51d6-11eb-9ed3-c9e0504d2bda.png)

This is default token. And if you set another. You can see https://github.com/ant-design/ant-design/issues/28767

![image](https://user-images.githubusercontent.com/29775873/103997582-3e990900-51d6-11eb-9cdb-b0ebf58a9185.png)

2021-01-08 09:25 UTC, xrkffgg commented
> I don't always want to comment at the time of adding the 'needs:information' label.

If so, do I need to remove this? `issue labeled reply`

2021-01-11 07:50 UTC, jennifer-shehane submitted a review, later dismissed
Yes, I would remove the `issue labeled reply` part of the action. 

We do have a cypress-bot we use for other messages. 

<img width="219" alt="Screen Shot 2021-01-11 at 2 20 05 PM" src="https://user-images.githubusercontent.com/1271364/104156769-2dd7d580-5418-11eb-9269-0aead75197c6.png">

2021-01-11 08:32 UTC, xrkffgg commented
Okay, I have removed it.

2021-01-13 12:08 UTC, xrkffgg commented on .github/workflows/issue-mark-duplicate.yml
> +        uses: actions-cool/issues-helper@v1.8
```suggestion
        uses: actions-cool/issues-helper@1.x
```

2021-01-28 02:06 UTC, jennifer-shehane commented
@xrkffgg Thanks for the PR and suggestions. Unfortunately our team has decided against pulling in a 3rd party GitHub Action into our repo at this time. I'll be closing this PR.

2021-01-28 02:06 UTC, closed without merging

2021-01-28 02:24 UTC, xrkffgg commented
OK~