fix: Added types for runtime config.
cypress-io/cypress pull request #14584
Opened 2021-01-15 07:01 UTC by sainthkh

- Closes #14392

### User facing changelog

Added types for config properties appended at runtime.

### Additional details
- Why was this change necessary? => Some runtime config properties are not defined in the type file. 
- What is affected by this change? => N/A

#### Any implementation details to explain? 

I got the list of runtime config properties with the code below:

```js
it('t', () => {
  console.log(Cypress.config())
})
```

And compared the list of options in `server/lib/config_options.ts`.

### How has the user experience changed?

N/A

### Questions

* I intentionally left some explanations for some properties as `???` because it's hard to guess or track the meaning of them.
* I intentionally grouped and left no explanation for internal or unlisted properties. 

### PR Tasks

I intentionally didn't add tests because config types are not tested in the `cli` tests.

2021-01-19 07:45 UTC, jennifer-shehane requested changes

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * The browser Cypress is runnong on.
```suggestion
     * The browser Cypress is running on.
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * The browsers Cypress can use.
```suggestion
     * Available browsers found on your system.
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * Enables component testing.
```suggestion
     * Whether component testing is enabled.
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +    experimentalFetchPolyfill: boolean
This is deprecated, so probably wouldn't bother documenting this.

```suggestion
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +    hosts: null | string[]
I think this is also mostly used internally? We set it in our Cypress config, but I"m not sure why someone else would need this.

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * @see https://docs.cypress.io/guides/references/configuration.html#modifyObstructiveCode
on link
```suggestion
     * @see https://on.cypress.io/configuration#modifyObstructiveCode
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * and replace code that matches some patterns.
```suggestion
     * Whether Cypress will search for and replace 
     * obstructive JS code in .js or .html files.
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * ???
```suggestion
     * A unique ID for the project used for recording
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * The path to the support folder
```suggestion
     * Path to the support folder.
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * Glob pattern for the test files.
```suggestion
     * Glob pattern to determine what test files to load.
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * ???
```suggestion
     * The user agent the browser sends in all request headers.
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +    isInteractive: boolean
This one is ok to document, we use it in a lot of examples.
```suggestion
    /**
     * Whether Cypress was launched via 'cypress open' (interactive mode)
     */
    isInteractive: boolean
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +    platform: 'linux' | 'darwin' | 'win32'
```suggestion
     /**
     * The platform Cypress is running on.
     */
    platform: 'linux' | 'darwin' | 'win32'
```

2021-01-19 07:45 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +    spec: {
I could see this also being useful to document.

2021-01-19 07:55 UTC, sainthkh commented
@jennifer-shehane Thank you for the feedback. I applied them.

2021-01-20 07:38 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +    hosts: null | string[]
well, TIL. 

```suggestion
    /**
     * Hosts mappings to IP addresses.
     */
    hosts: null | string[]
```

2021-01-20 07:38 UTC, jennifer-shehane approved these changes

2021-01-20 08:38 UTC, merged