fix: webpack-preprocessor-lazy-load - React lazy load breaks webpack config
cypress-io/cypress pull request #14599
Opened 2021-01-16 09:57 UTC by vtereshyn

- Closes #3491 

### User facing changelog
The user who uses `@cypress/webpack-preprocessor` has the ability to set his/her own Webpack `publicPath`

### Additional details
Please, see https://github.com/cypress-io/cypress/issues/14592 for additional explanation.
### How has the user experience changed?

Before: 
![image](https://user-images.githubusercontent.com/32247411/104808487-52082d80-57ef-11eb-8d6a-779ca1b09b93.png)

After:
![image](https://user-images.githubusercontent.com/32247411/104808401-a959ce00-57ee-11eb-82c2-fbb5daa2275d.png)

### PR Tasks
- [+] Have tests been added/updated?

2021-01-16 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=14599) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=14599) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=14599) it.</sub>

2021-01-18 17:04 UTC, vtereshyn commented
Not sure who I have to tag in here, hope that @bahmutov will be the right person to address this.

2021-01-19 08:50 UTC, dmtrKovalenko requested changes
I am not sure it will work with lazy-loaded modules (cypress has some limitations here – only allows 1 javascript file). There is a test https://github.com/cypress-io/cypress/blob/develop/npm/react/cypress/component/advanced/lazy-loaded-suspense/lazy-loaded-suspense.spec.tsx that can check the desired behavior. 

Can you please uncomment it and make sure that CI passed? Thanks

2021-01-19 08:54 UTC, vtereshyn commented
@dmtrKovalenko I am pretty sure it will work with Lazy loaded components as I showed in my screenshots.
 
Here is my usage: I have a component that wrapped into HOC which lazy loads another component (popup) and I got a Webpack error, not React or Cypress.

Right now as a fix I'm editing `node_modules/@cypress/` folder to proceed with my work. 

Also, sorry, I didn't get what particularly should I uncomment? I see that the code you mentioned is uncommented.

2021-01-19 08:55 UTC, dmtrKovalenko commented
Cool if so, sorry just remove the `.skip` on test and the coment

2021-01-19 08:59 UTC, vtereshyn commented
@dmtrKovalenko ok, will do. But my fix is not about that at all. My fix is particularly about webpack-preprocessor and webpack error, not about Cypress and React.Lazy. I didn't change any code in Cypress core

2021-01-19 09:01 UTC, dmtrKovalenko commented
I understand this, but PR title says that React.lazy breaks the webpack-preprocessor code, right?

2021-01-19 09:03 UTC, dmtrKovalenko commented on npm/webpack-preprocessor/test/unit/index.spec.js
> +      it('adds output options when user output options are non-default', function () {
This test doesn't really check that when we have dynamic import somewhere that webpack doesn't crash. It only checks that specific options passed to webpack config. 
What do you think about adding more complex test that shows the desired behavior if @cypress/react tests won't work?

2021-01-19 09:08 UTC, vtereshyn commented
Probably this is incorrect to name PR as I named it here. I named it `React lazy loads breaks webpack config` just because I faced this error during Lazy loading in one of my components. This PR should be named like `Allow Cypress user to pass own Webpack output configuration`. Basically, this fix is about dynamic loading as well, just because Webpack doesn't understand the path inside the code.
Ex:
`import(`../../../${YourComponentName}``

2021-01-19 09:17 UTC, dmtrKovalenko commented
Cool, thx its more clear now. Then it should be not `fix:` but `feat:` as well

2021-01-19 09:18 UTC, vtereshyn commented
> Cool, thx its more clear now. Then it should be not `fix:` but `feat:` as well

Agreed, do you want me to create new PR with using new branch?

2021-01-19 09:19 UTC, dmtrKovalenko commented
I think just rename the title

2021-01-19 09:20 UTC, vtereshyn commented
@dmtrKovalenko sounds good, thanks

2021-01-19 09:28 UTC, vtereshyn commented
@dmtrKovalenko ok, so do you want me to do something else? Write Cypress tests?

2021-01-19 09:42 UTC, dmtrKovalenko commented
It may be nice to add e2e tests in webpack-preprocessor that shows how it works, but maybe that is not needed. :) 
Probably let's wait for CI to pass

2021-01-19 09:43 UTC, vtereshyn commented
Ok, thanks!

2021-01-20 13:38 UTC, vtereshyn commented
Hey @dmtrKovalenko 
I'm sorry, but I can't get what's going on CI because I have executed `test` script locally and everything was good. Not sure what should I do next and how can I reproduce CI issue but locally. Thanks!

2021-01-20 14:02 UTC, vtereshyn commented
![image](https://user-images.githubusercontent.com/32247411/105185148-df71b780-5b38-11eb-9fde-6ccb07b55df8.png)

2021-01-20 14:10 UTC, vtereshyn commented
![image](https://user-images.githubusercontent.com/32247411/105186066-fc5aba80-5b39-11eb-967a-258f82fb3cc0.png)

I am not sure whats wrong on CI then

2021-01-20 15:12 UTC, vtereshyn commented
@dmtrKovalenko any thoughts?

2021-01-21 14:27 UTC, vtereshyn commented
well, I am not getting any responses, so I'm gonna close this PR. @dmtrKovalenko @jennifer-shehane

2021-01-21 14:28 UTC, dmtrKovalenko commented
Do not close it, I'll take a look once get some free time

2021-01-21 22:21 UTC, lmiller1990 commented
@vtereshyn when you run the tests locally you may need to build `npm/webpack-preprocessor` manually - either run `yarn watch` in `npm/webpack-preprocessor` or just with `yarn build`. That might explain why things work locally (you ran the tests without your change) but CI builds everything prior to running the tests.

2021-01-22 08:14 UTC, vtereshyn commented
@lmiller1990 thanks for your suggestion. I did `yarn build` before running tests. And looks like I got all test passed locally again.

2021-01-22 10:22 UTC, lmiller1990 commented
Will take a look!

2021-01-25 00:46 UTC, lmiller1990 commented
I ran the tests locally and reproduced the error once. But then I ran them again and it all seemed fine. I'll try re-running CI and see what happens.

2021-01-26 12:28 UTC, vtereshyn commented
@lmiller1990 thank you

2021-02-12 12:54 UTC, closed without merging