fix: improve studio error states
cypress-io/cypress pull request #14696
Opened 2021-01-22 08:24 UTC by panzarino

- Closes #14691
- Will close #14686

### User facing changelog
Improves studio error state in the following ways:
- Adds cancel button to left side of reporter on fail

### Additional details
Will add more details before moving out of draft state

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-01-26 04:56 UTC, jennifer-shehane submitted a review, later dismissed
I don't think this snapshot is capturing what you expected - it doesn't show the studio error. https://percy.io/cypress-io/cypress/builds-next/8535127/changed/485040355

Looks fine otherwise. Manually tested. The error state looks good. Is tested.

2021-01-26 15:22 UTC, chrisbreiding approved these changes, later dismissed

2021-01-26 23:15 UTC, panzarino commented
@jennifer-shehane Good catch on percy snapshot - fixed now

2021-01-27 04:18 UTC, fornever847 submitted a review, later dismissed

2021-01-27 04:23 UTC, panzarino commented
@jennifer-shehane also fixed modal docs issue you brought up here since I didn't want to make a separate PR along with an additional fix since the first review - more details in OP

2021-01-27 05:06 UTC, jennifer-shehane requested changes

2021-01-27 05:06 UTC, jennifer-shehane commented on packages/runner/src/studio/studio-modals.jsx
> +                <li><pre>cy.get(...).uncheck()</pre></li>
No prefix for child commands. 

```suggestion
                <li><pre>.check()</pre></li>
                <li><pre>.click()</pre></li>
                <li><pre>.select()</pre></li>
                <li><pre>.type()</pre></li>
                <li><pre>.uncheck()</pre></li>
```

2021-01-27 15:40 UTC, jennifer-shehane approved these changes

2021-01-27 17:49 UTC, merged