chore: tsify driver events library
cypress-io/cypress pull request #15026
Opened 2021-02-10 19:24 UTC by flotwig

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-02-10 23:29 UTC, elevatebart requested changes
A quick suggestion to avoid confusion. 
`esInteropModule` is not always making bundlers happy since it needs babel's interop packaging.

2021-02-10 23:29 UTC, elevatebart commented on packages/driver/src/cypress/events.ts
> +import Bluebird from 'bluebird'
You might want to use a * here since bluebird is `export = `
```suggestion
import * as Bluebird from 'bluebird'
```

2021-02-10 23:29 UTC, elevatebart commented on packages/driver/src/cypress/events.ts
> +import Debug from 'debug'
```suggestion
import { debug as Debug } from 'debug'
```

2021-02-11 01:06 UTC, elevatebart submitted a review, later dismissed

2021-02-11 14:21 UTC, flotwig commented on packages/driver/src/cypress/events.ts
> +import * as Bluebird from 'bluebird'
```suggestion
import Bluebird from 'bluebird'
```

otherwise it breaks types

2021-02-11 14:50 UTC, elevatebart approved these changes
seems all better now ;)

2021-02-11 14:56 UTC, merged