Remove experimentalRunEvents flag
cypress-io/cypress pull request #15276
Opened 2021-03-01 16:24 UTC by chrisbreiding

- Addresses [TR-671](https://cypress-io.atlassian.net/browse/TR-671)

### User facing changelog

- The `experimentalRunEvents` configuration flag has been removed. It is no longer necessary to enable listening to run events in the plugins file.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [x] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-03-01 16:33 UTC, bahmutov commented
Will these events be enabled in both interactive and non-interactive modes?

2021-03-01 16:50 UTC, chrisbreiding commented
Just run mode for the time being.

2021-03-01 16:52 UTC, bahmutov commented
I was hoping both, so I could switch code coverage plugin to it, otherwise no luck, has to happen in both modes https://github.com/cypress-io/code-coverage

2021-03-01 17:03 UTC, chrisbreiding commented
That requires more discussion and work to implement. For now, we're just removing the flag.

2021-03-01 19:21 UTC, flotwig approved these changes

2021-03-01 19:21 UTC, flotwig commented on packages/server/lib/config_options.ts
> -    isExperimental: true,
would it be good to add this to `breakingOptions` at the bottom of this file, so users get a warning that it's no longer required to pass this option?

2021-03-02 01:05 UTC, jennifer-shehane requested changes
I'm trying to see that the events work without the flag and I can't console.log any of the details. I know I have the changes because I see the new warning message. Am I missing something? Running via `yarn start`. 

```js
module.exports = (on, config) => {
  on('before:run', (details) => { 
    console.log(details) 
  })
  on('before:spec', (spec) => { 
    console.log(spec) 
  })
  on('after:spec', (spec, results) => { 
    console.log(spec, results) 
  })
  on('after:run', (results) => { 
    console.log(results) 
  })
}
```

<img width="746" alt="Screen Shot 2021-03-01 at 7 59 48 PM" src="https://user-images.githubusercontent.com/1271364/109580634-e6d99880-7ac8-11eb-8fb4-a96303961b8b.png">

Also, when did this happen to our CSS? 😳 This error message on the plugins is completely weird. 

![](http://g.recordit.co/sD9VNR13sr.gif)

2021-03-02 14:02 UTC, chrisbreiding commented
> I'm trying to see that the events work without the flag and I can't console.log any of the details. I know I have the changes because I see the new warning message. Am I missing something? Running via yarn start.

These events only fire in `run` mode, so you won't see them with `yarn start`.

As for the CSS, I think the bootstrap upgrade would be the most likely culprit.

2021-03-02 14:59 UTC, jennifer-shehane approved these changes
@chrisbreiding We didn't upgrade bootstrap recently that I'm aware of. Do you have a PR link?

I'll open a new PR to fix the CSS issue.

2021-03-02 15:06 UTC, chrisbreiding commented
My mistake, I thought we had merged the bootstrap upgrade, but we haven't. Maybe the node-sass change?

2021-03-02 15:07 UTC, merged