feat: create new spec file from desktop-gui
cypress-io/cypress pull request #15335
Opened 2021-03-05 06:35 UTC by panzarino

- Closes GROW-173

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-03-15 18:04 UTC, jennifer-shehane submitted a review, later dismissed
You may want to get @flotwig to test in Windows/Linux. I think he's setup to test both. 

I guess it's also technically possible they could create a file that would be filtered out of the `testFiles` regex, so that's another reason a new file may not show up in the list. I dunno if it's worth mentioning in the warning.

Oh there's a little format dropdown, that is cool. 

The user experience looks good to me on the Mac. 👍 

I'll approve and leave it up to you if you also want flotwig to manually test.

2021-03-16 03:22 UTC, panzarino commented
@jennifer-shehane Yeah I noticed that issue with `testFiles` while doing some manual testing myself - I attempted to address this in the error message with "or is not recognized as a spec file" but we could be more explicit there. I've made some very minor cosmetic changes since your review if you want to take a quick look but don't feel obligated.

@flotwig It'd be great if you could do a simple test on Windows & Linux just to make sure that the user flow is pretty similar. Any images or gifs that you could provide would be super appreciated. Thanks so much!

2021-03-16 15:41 UTC, flotwig commented
Merged in `develop` since it fixes building on Windows :stuck_out_tongue:

2021-03-16 16:23 UTC, flotwig requested changes
I noticed an issue when running in Windows - it says my spec file was created outside of the spec tree, but it is clearly not (pardon the palette, GitHub's file size limit is 10mb): ![o](https://user-images.githubusercontent.com/1151760/111343984-dce09980-8673-11eb-83ad-87c344484382.gif)

Strangely, the same thing doesn't happen on Linux:  ![2021-03-16 new spec file desktop-gui linux](https://user-images.githubusercontent.com/1151760/111341532-83776b00-8671-11eb-8697-2baba9fbb25b.gif)

2021-03-16 16:31 UTC, flotwig commented
I wonder if the `filePath` on Windows is somehow not what we expect for Linux and macOS?

Here is the yielded value of dialog.openSaveDialog on Windows:

```
{
  canceled: false,
  filePath: 'C:\\Users\\zbloo\\AppData\\Local\\Temp\\foo\\cypress\\integration\\untitled.spec.js'
}
```

2021-03-16 16:50 UTC, flotwig commented on packages/desktop-gui/src/specs/specs-store.js
> +    if (this.newSpecAbsolutePath && !_.find(this._files, { absolute: this.newSpecAbsolutePath })) {
yeah, i bet the paths in this._files are either double-escaped Windows paths, or POSIX paths, that's why this is not working as expected on Windows

2021-03-22 21:10 UTC, panzarino commented
@flotwig Nice catch - should be fixed now. Since I tested this on Mac (w/ stubbed tests) could you do one last manual verification that it works properly on an actual Windows system?

2021-03-22 22:50 UTC, flotwig approved these changes
seems to be working great now: 
![2021-03-22 new spec file desktop-gui](https://user-images.githubusercontent.com/1151760/112067993-eb8deb80-8b60-11eb-929b-d2ec79ad9158.gif)

2021-03-23 16:20 UTC, merged