fix: exception when recording with no tests in specfile
cypress-io/cypress pull request #15517
Opened 2021-03-16 14:31 UTC by Bkucera

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-03-16 15:51 UTC, jennifer-shehane commented
Keep getting this error when trying to record in staging. 

```
Recording this run failed because the request was invalid.

Request should follow postRunRequest@2.2.0 schema

Errors:

[
  "data has additional properties: runnerCapabilities"
]

Request Sent:

{
  "ci": {
    "params": null,
    "provider": null
  },
  "specs": [
    "cypress/integration/spec.js",
    "cypress/integration/untitled_spec.js",
    "cypress/integration/untitled_spec2.js",
    "cypress/integration/untitled_spec3.js"
  ],
  "commit": {
    "sha": "71b5c34e5b4bb24fd00a9e43a4222c31161299c1",
    "branch": "master",
    "authorName": "Ralf Richtsteiger",
    "authorEmail": "dev@rwam.de",
    "message": "add example code\n",
    "remoteOrigin": "https://github.com/rwam/cypress-test.git",
    "defaultBranch": null
  },
  "group": null,
  "platform": {
    "osCpus": [
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 48215720,
          "nice": 0,
          "sys": 31910740,
          "idle": 144684890,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 3793580,
          "nice": 0,
          "sys": 5562250,
          "idle": 215287340,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 41126270,
          "nice": 0,
          "sys": 23321200,
          "idle": 160199290,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 3782870,
          "nice": 0,
          "sys": 5308350,
          "idle": 215551590,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 34483520,
          "nice": 0,
          "sys": 19475270,
          "idle": 170687320,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 3794280,
          "nice": 0,
          "sys": 5127750,
          "idle": 215720400,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 28699140,
          "nice": 0,
          "sys": 16052610,
          "idle": 179893690,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 3790350,
          "nice": 0,
          "sys": 4994960,
          "idle": 215856750,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 25706030,
          "nice": 0,
          "sys": 14136700,
          "idle": 184802050,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 3758100,
          "nice": 0,
          "sys": 4879550,
          "idle": 216004010,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 21328750,
          "nice": 0,
          "sys": 11575640,
          "idle": 191739730,
          "irq": 0
        }
      },
      {
        "model": "Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz",
        "speed": 2600,
        "times": {
          "user": 3746870,
          "nice": 0,
          "sys": 4782160,
          "idle": 216112250,
          "irq": 0
        }
      }
    ],
    "osName": "darwin",
    "osMemory": {
      "free": 842321920,
      "total": 17179869184
    },
    "osVersion": "19.6.0",
    "browserName": "Electron",
    "browserVersion": "87.0.4280.141"
  },
  "parallel": null,
  "ciBuildId": null,
  "projectId": "6wa698",
  "recordKey": "5df12e37-11cc-4f1d-a0a0-a7e6842aef6e",
  "specPattern": null,
  "tags": [
    ""
  ],
  "runnerCapabilities": {
    "dynamicSpecsInSerialMode": true,
    "skipSpecAction": true
  }
}
```

2021-03-16 16:21 UTC, jennifer-shehane approved these changes
Manually tested - this fixes the issue. Also tested.

2021-03-16 17:35 UTC, jennifer-shehane requested changes
This exits and does report a Dashboard url, but it looks like it reports as pending forever. So, not sure if this is relevant. https://dashboard-staging.cypress.io/projects/o9ej5p/runs/1

2021-03-17 00:12 UTC, brian-mann commented
This sounds pretty relevant to me... @Bkucera and @traviscy thoughts?

2021-03-17 14:26 UTC, brian-mann approved these changes, later dismissed

2021-03-17 14:27 UTC, brian-mann commented on packages/server/test/e2e/7_record_spec.js
> +    it('succeeds when empty spec file', async function () {
you should link to the github issue that this is fixing, this is a specific regression

2021-03-17 14:27 UTC, brian-mann commented on packages/server/lib/util/tests_utils.ts
> +  if (!suite || !suite.suites) {
maybe explain why this is necessary and link to the github issue that this is fixing, this is a specific regression

2021-03-17 15:51 UTC, merged