feat: report studio usage to dashboard
cypress-io/cypress pull request #15639
Opened 2021-03-24 06:08 UTC by panzarino

- Closes GROW-191

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-04-20 23:19 UTC, Bkucera commented
see https://github.com/cypress-io/json-schemas/pull/616

2021-04-20 23:52 UTC, Bkucera requested changes

2021-04-20 23:52 UTC, Bkucera commented on packages/server/lib/studio.ts
> +}
This is called for each test? 
and do both `wasTestExtended` and `wasTestCreated` read the file or do they sharing the read?
So for a spec file of 60 tests, is this going to read the file from disk 120 times?
the performance test in this PR ensures that a single test takes less than 100ms to parse the ast from an already in memory file, but I could see this being an issue

2021-04-21 01:36 UTC, brian-mann commented
Dont merge this PR yet - it requires discussion.

2021-04-28 15:22 UTC, closed without merging