chore: adjust CSS
cypress-io/cypress pull request #15640
Opened 2021-03-24 07:26 UTC by lmiller1990

- Closes https://cypress-io.atlassian.net/browse/CT-355

### User facing changelog

Improve responsive design of the reporter header for both runner and runner-ct. Also reduce some technical debt; runner-ct no longer defines a custom header.

### Additional details

When resizing the reporter, the various button groups move around strangely. This PR attempts to simplify the structure and make everything wrap in a more natural way.

The entire reporter header probably needs a rethink; Cypress and the UI have evolved a lot since it was first conceived. 

Video showing responsive:

Before:

https://user-images.githubusercontent.com/19196536/112270602-9a4b3c80-8cc5-11eb-8093-ab4c01dcec5a.mov

After:

https://user-images.githubusercontent.com/19196536/112270609-9ddec380-8cc5-11eb-8cf1-6a10e9ad86e5.mov

### How has the user experience changed?

## Runner (before/after)

![image](https://user-images.githubusercontent.com/19196536/112270500-7a1b7d80-8cc5-11eb-9639-213760ae0773.png)

![image](https://user-images.githubusercontent.com/19196536/112270544-87d10300-8cc5-11eb-82b2-81bbb21841b3.png)

## RunnerCt (before/after)

![image](https://user-images.githubusercontent.com/19196536/112270526-81db2200-8cc5-11eb-855a-af81ac31b5b7.png)

![image](https://user-images.githubusercontent.com/19196536/112270482-7556c980-8cc5-11eb-95bc-2d4a8e222208.png)

### PR Tasks

- [ ] Has the original issue or this PR been tagged with a release in ZenHub?  TODO

2021-03-25 05:36 UTC, lmiller1990 commented on packages/runner-ct/src/app/SpecList/SpecList.tsx
>    }
The `runner-ct` changes are unrelated, just fixing a missing dependency on a `useEffect` hook

2021-03-25 05:36 UTC, lmiller1990 commented on packages/runner-ct/src/app/RunnerCt.tsx
> -      const selectedSpec = props.state.specs.find((spec) => spec.absolute.includes(file.relative))
Unrelated but linter was complaining so I fixed it

2021-03-25 13:08 UTC, agg23 reviewed
Looks fine to me, but I'll let the TR team approve.

2021-03-25 23:08 UTC, flotwig commented
I'm not totally sold on removing the groups - I think the groupings are a helpful visual cue. But maybe the groupings could disappear once the sidebar has been shrunk to whatever the breakpoint is that causes things to start wrapping.

2021-03-26 01:02 UTC, jennifer-shehane requested changes
I don’t think I have a problem with removing the grouping. Everything still seems obvious to what its use was before.

It's not obvious in the header in general what are actions and what are not actions though. I think we had this discussion before. Like, the Tests and auto scroll and refresh are actions, but the rest are just indicators - and there’s no real way to realize this in the current design . But I don’t really think this problem was introduced in this PR.

After using the new design, I think I would prefer to have to stop/refresh button right aligned where it always is. I use this pretty frequently, so the positioning of the button feels cumbersome, it should be aligned to the corner to better click. 

Can we have the design below and it still collapse like in this design?

<img width="602" alt="Screen Shot 2021-03-25 at 8 58 34 PM" src="https://user-images.githubusercontent.com/1271364/112562184-1ff5e780-8dad-11eb-85b6-1e29c72e314f.png">

2021-03-29 03:37 UTC, closed without merging