fix: default to electron for runner-ct
cypress-io/cypress pull request #15704
Opened 2021-03-30 02:14 UTC by lmiller1990

- Closes https://cypress-io.atlassian.net/browse/CT-403

### User facing changelog

By default Component Testing will launch in Electron. It looks nicer and is a more consistent experience. Also, this change means users do not need to install a browser on CI - the tests will just run in the electron browser that comes with Cypress.

![image](https://user-images.githubusercontent.com/19196536/112923304-62bf1300-9151-11eb-8e9a-0f0c70015da3.png)

### Additional details

We should default to using the bundled electron browser by default. This is so when you run CT on CI, users do not need to install a browser. Instead, it will just use the Electron that is bundled with Cypress.

### How has the user experience changed?

- Launch Electron by default in open-ct
- Headless by default in run-ct

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-03-30 20:02 UTC, JessicaSachs commented
There's an issue with this PR in which it orphans the renderer process when Cypress is closed. This leads to one orphaned ~100MB process per Cypress application close. This issue does not exist in Chrome. We can either:
1. Change the default to chrome and ship with the orphaned process
2. Fix the child process from being orphaned

Going to investigate #2 for 30mins to see if it's an easy fix. If not, we'll default to Chrome and ship.

2021-03-30 20:05 UTC, JessicaSachs requested changes
Blocked pending the fix for orphaning child processes

2021-03-30 20:31 UTC, brian-mann commented
I'm looking at this now

2021-03-30 21:50 UTC, JessicaSachs commented
This is worse that initially thought. The Electron application crashes and the error code isn't handled properly. This means that if tests fail, we exit with exit code 0 and pass the tests. Brian and Ben and I are looking into this, but we can't ship without fixing it.

2021-03-31 06:02 UTC, lmiller1990 commented on packages/server/lib/modes/run.js
> -    return this.listenForProjectEnd(project, exit, runAllSpecsInSameBrowserSession)
unused

2021-04-01 02:37 UTC, JessicaSachs commented
Update: This PR was attempting to add support for Electron, but the crashers in this PR were masked by an unrelated bug that is now fixed by #15727. After isolating the issue, I was able to fix the root cause of the Electron-only failure. More details are available in #15731 which replaces this PR.

2021-04-01 02:37 UTC, closed without merging