chore: Turn on test retries in run mode for other packages
cypress-io/cypress pull request #15714
Opened 2021-03-30 19:25 UTC by jennifer-shehane

We’d like to use test retries for the UIs tested in Cypress (outside of the driver)

2021-03-30 19:34 UTC, flotwig submitted a review, later dismissed

2021-03-30 19:57 UTC, jennifer-shehane commented
oh no everything failed 😞

2021-04-01 02:15 UTC, panzarino approved these changes

2021-04-01 02:20 UTC, panzarino requested changes
Let's turn off retries for the `mochaEvents` files

2021-04-01 14:26 UTC, jennifer-shehane commented
@panzarino It looks like it's already turned off retries for `runner.mochaEvents` and the `retries.mochaEvents` actually specifically requires retries to be on for what it's testing.

2021-04-01 15:41 UTC, panzarino commented
@jennifer-shehane I think that's for the internal isolated runner. We want to set the retries for the internal isolated runner on a spec-by-spec basis (eg. so that retries can set it to non-zero) but the retries for the outer runner to remain at 0. Basically the "inner Cypress" - `createCypress({})` call should have `retries` set to whatever we're testing (`0` for most files, `2` for the retries spec) while the "outer Cypress" should have `retries` always set to 0 so that it never retries the snapshot comparison (eg. our top-level `describe` should have the config param with `retries: 0`).

2021-04-01 17:31 UTC, panzarino approved these changes

2021-04-02 18:02 UTC, merged