docs(component-testing): Added rerender/updating props recipe
cypress-io/cypress pull request #15742
Opened 2021-04-01 13:29 UTC by agg23

### User facing changelog
Provided recipe example of how to update props without remounting in component testing.

### How has the user experience changed?
Documentation update only; no user experience changes.

2021-04-01 13:37 UTC, dmtrKovalenko commented on npm/react/docs/recipes.md
> +const Wrapper = () => {
```suggestion
const TestAcc = () => {
```

2021-04-01 13:38 UTC, elevatebart commented
The new recipe is very useful as is.
Could you add a mention of rerender somewhere please?
This is what users are going to be searching for.
Thet's give them a leg up ;)

2021-04-01 13:47 UTC, dmtrKovalenko commented on npm/react/docs/recipes.md
> +We recommend building a "wrapper" component with the necessary DOM controls to push new props to your component under test.
```suggestion
We recommend building a "wrapper" component, that will be close to how your users will use this component. And add DOM controls that will change props during the test. 
```

2021-04-01 15:54 UTC, elevatebart requested changes
The new recipe is very useful as is.
Could you add a mention of rerender somewhere please?
This is what users are going to be searching for.
Let's give them a leg up ;)

2021-04-05 03:37 UTC, lmiller1990 approved these changes

2021-04-05 05:46 UTC, lmiller1990 commented
Need approval from @elevatebart to merge.

2021-04-05 15:43 UTC, elevatebart approved these changes
Hope to get the rerender function in there soon... people will ask for it.

2021-04-05 15:43 UTC, merged