fix: debug log video nonexistence instead of logging as warning
cypress-io/cypress pull request #15828
Opened 2021-04-06 20:31 UTC by chrisbreiding

- Closes #9048
- Addresses comments in https://github.com/cypress-io/cypress/issues/2522#issuecomment-767576294
- Addresses [TR-463](https://cypress-io.atlassian.net/browse/TR-463)

### User facing changelog

- There will no longer be a warning displayed when the video cannot be found after a run.
- There will no longer be a warning displayed when running a TypeScript spec without a tsconfig.json file present.

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- N/A Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- N/A Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- N/A Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-04-07 13:44 UTC, flotwig requested changes

2021-04-07 13:44 UTC, flotwig commented on patches/tsconfig-paths+3.9.0.patch
> +     var matchPath = match_path_sync_1.createMatchPath(configLoaderResult.absoluteBaseUrl, configLoaderResult.paths, configLoaderResult.mainFields, configLoaderResult.addMatchAll);
i think this belongs in `packages/server`, no?

2021-04-07 13:44 UTC, flotwig commented on package.json
> +    "postinstall": "patch-package && ./scripts/run-if-not-ci.sh yarn build",
`packages/server`?

2021-04-07 13:52 UTC, flotwig commented on package.json
> +    "postinstall": "patch-package && ./scripts/run-if-not-ci.sh yarn build",
might need a nohoist

2021-04-07 14:42 UTC, flotwig approved these changes

2021-04-07 14:51 UTC, merged

2021-04-11 08:52 UTC, NeverLiez reviewed
-