fix(vite-dev-server): only re-run tests when specs deps are updated
cypress-io/cypress pull request #16215
Opened 2021-04-26 23:58 UTC by elevatebart

- Closes #16125

### User facing changelog
Re-run tests

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-04-27 01:47 UTC, Rada8732 approved these changes

2021-04-27 03:33 UTC, lmiller1990 submitted a review, later dismissed

2021-04-27 03:34 UTC, lmiller1990 commented
The code looks fine. I did not test it yet, so let's hold of merging until we give it a bit of a test.

2021-04-27 03:42 UTC, lmiller1990 reviewed
Let's check for:

- circular imports
- add a check to bail out of potential infinite loop
- general testing

2021-04-27 04:23 UTC, lmiller1990 commented
1. Added a test for [circular imports](https://github.com/cypress-io/cypress/pull/16215/commits/584bf8ad5040f1f7d6728e788c62f27d406059b8). Seems okay.
2. Tested it out. It's so fast for our code-bases (we don't have a huge code-base to test it on - just the demo code-base).
3. Creating/modifying a file in the `cypress/components` directory does *not* cause a re-run or update. Great!

Probably not related to this PR but I could not test with npm/design-system. Seems the project is entirely broken. I don't know when this happened. This should be failing on CI.

![image](https://user-images.githubusercontent.com/19196536/116184962-0eb14980-a764-11eb-95b0-fad93a36e8f4.png)

2021-04-27 13:22 UTC, agg23 requested changes

2021-04-27 13:22 UTC, agg23 commented on npm/vite-dev-server/src/makeCypressPlugin.ts
> +            stopIteration = true
Please use a `for...of` then, because it doesn't make sense to continue iterating through the list of importers

2021-04-27 13:22 UTC, agg23 commented on npm/vite-dev-server/src/makeCypressPlugin.ts
> +          if (specs.some((spec) => spec.absolute === mod.file)) {
Since we keep making this check, we should use a `Set` of available paths.

2021-04-27 13:22 UTC, agg23 commented on npm/vite-dev-server/src/makeCypressPlugin.ts
> +      while (moduleImporters && moduleImporters.size) {
This should probably have a max number of steps. We don't need to go through a dependency tree of 1 million for example

2021-04-28 01:24 UTC, lmiller1990 commented
The error in the screenshot above is also in develop. Not introduced here. I made an issue: https://github.com/cypress-io/cypress/issues/16241

2021-04-28 16:34 UTC, agg23 approved these changes

2021-04-28 17:09 UTC, merged