feat: schematic adds ng e2e to scripts
cypress-io/cypress pull request #16565
Opened 2021-05-18 15:19 UTC by cexbrayat

Refs #16514

### User facing changelog

- Angular schematic now adds `ng e2e` to scripts

### Additional details

New projects generated with Angular v12 do not have the `e2e` script.
This PR adds such a script (in addition to the existing `cy:run` and `cy:open`)

### How has the user experience changed?

It is now possible to run `yarn e2e` out of the box.

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-05-18 15:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=16565) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=16565) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=16565) it.</sub>

2021-05-18 20:23 UTC, admah commented
@cexbrayat thank you for adding this!

To get the PR merged in appropriately to kick off a new package release, you'll need to actually make this PR off of `master` instead of `develop` (https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#branches)

2021-05-18 20:25 UTC, admah requested changes
@cexbrayat thank you for adding this!

To get the PR merged in appropriately to kick off a new npm package release, you'll need to actually make this PR off of master instead of develop (https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#branches).

2021-05-19 01:34 UTC, lmiller1990 commented
Wooo, Angular!

2021-05-19 06:42 UTC, cexbrayat commented
@admah Sure! I rebased on master, let me know if you need anything else.

2021-05-19 14:53 UTC, admah approved these changes
🚀

2021-05-19 15:35 UTC, merged