fix: convert 0 to string in contains command
cypress-io/cypress pull request #16998
Opened 2021-06-17 22:08 UTC by dario-piotrowicz

- Closes https://github.com/cypress-io/cypress/issues/1119

### User facing changelog

`cy.contains(0)` now logs correctly

### Additional details

This change fixes the issue in which 0 was not logged in the cypress console when used in the contains command

This was caused by the use of `_.compact` which removes all falsy values from an array:  https://github.com/cypress-io/cypress/blob/ba8bfd27f1ac218fa3e322425039da834ba7b787/packages/driver/src/cy/commands/querying.js#L523        

My solution was to convert the falsy number 0 to t he truthy string "0", another solution I considered was replacing `_.compact` with `_.without` and only filter out falsy values except from 0, I thought that just converting the 0 to "0" was a cleaner solution, but if you disagree please let me know and I can go with the `_.without` one if you prefer (or any you can suggest)

### How has the user experience changed?

Before the change if you queried `cy.contains(0)` all would work but you would not see `0` in the cypress console:
![Screenshot at 2021-06-17 23-06-33](https://user-images.githubusercontent.com/61631103/122478157-ccb4bf00-cfc0-11eb-9bb9-1c21583cf34a.png)
Now you will see `0`:
![Screenshot at 2021-06-17 23-01-02](https://user-images.githubusercontent.com/61631103/122478169-d1797300-cfc0-11eb-9782-e0972f313365.png)

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

### Extra

`yarn test` passes I hope it's enough, if it's not please let me know
![Screenshot at 2021-06-17 22-51-01](https://user-images.githubusercontent.com/61631103/122476786-a5f58900-cfbe-11eb-8885-a8e9dabc4cb9.png)

2021-06-17 22:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=16998) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=16998) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=16998) it.</sub>

2021-06-21 16:15 UTC, jennifer-shehane requested changes
Hey @dario-piotrowicz Thanks for the contribution. Can you add a test around this new behavior?

There is a Contributing Guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

To run the tests:

- within `cypress` root, run `yarn`
- run `yarn workspace @packages/driver cypress:open`
- click on the test you're writing to run it within Cypress

Instructions for running the `driver` tests can always be found here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/README.md

2021-06-21 22:24 UTC, dario-piotrowicz commented
Hi @jennifer-shehane , I am very sorry if I missed the inclusion of tests for contributions
(but I saw this as a bugfix so I thought it wasn't necessary)

I will read the documentation carefully and add the proper tests soon
(also I need to rebase as I can see my branch has gone a bit out of date)

Thank you very much

2021-06-23 21:51 UTC, dario-piotrowicz commented
@jennifer-shehane sorry I just wanted to apologize for not having come back to this yet, I have been snowed under

I will try to do it this week but may be difficult, likely I'll end up updating the PR this weekend, sorry :cry:

2021-06-26 10:57 UTC, dario-piotrowicz commented
@jennifer-shehane test added, please check the PR again :)

2021-06-30 14:27 UTC, jennifer-shehane approved these changes
I moved the test into our query spec. This helps remove some of the boilerplate and will be easier to find with the other contains tests. 

@dario-piotrowicz Thanks for this work. It looks good and tested!

2021-06-30 17:17 UTC, merged

2021-06-30 19:33 UTC, dario-piotrowicz commented
Thank you very much @jennifer-shehane :slightly_smiling_face: