fix: Add missing focus options on intercept
cypress-io/cypress pull request #17054
Opened 2021-06-22 08:39 UTC by Calyhre

### User facing changelog

Calls to `.focus()` with options are now passing the options down the line instead of dropping them.

### Additional details

As can be seen in the implementation of the focus interceptors: https://github.com/cypress-io/cypress/blob/b222dc08a415ff2a9d05345915b75fec71072512/packages/driver/src/cypress/cy.js#L307-L309

`FocusOptions` as defined in the [`HTMLElement.focus()` specs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus) are supported. Unfortunately, they are dropped right after in the `interceptFocus` method, preventing them to actually reach any native code.

### How has the user experience changed?

Cypress was not correctly handling call to focus with options like `{ preventScroll: true }`

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-06-22 08:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=17054) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=17054) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=17054) it.</sub>

2021-06-22 16:53 UTC, jennifer-shehane commented
Hey @Calyhre, this was not originally an intended option for `.focus()`, but looks like a great idea. I've tagged this as a new feature. 

Can you add some tests around this new behavior?

There is a Contributing Guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

A great place for these tests in particular would be in the focus_spec: https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/integration/commands/actions/focus_spec.js

Some things that would be good to test:

- what happens if you send invalid options to `preventScroll`, like `preventScroll: 'top'`?
- Does passing the options actually prevent scroll (check scroll position when passingg option and not
- maybe some other cases you think of

To run the tests:

- within `cypress` root, run `yarn`
- run `yarn workspace @packages/driver cypress:open`
- click on the test you're writing to run it within Cypress

Instructions for running the `driver` tests can always be found here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/README.md

2021-06-22 16:53 UTC, jennifer-shehane requested changes
Hey @Calyhre, this was not originally an intended option for `.focus()`, but looks like a great idea. I've tagged this as a new feature. 

Can you add some tests around this new behavior?

There is a Contributing Guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

A great place for these tests in particular would be in the focus_spec: https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/integration/commands/actions/focus_spec.js

Some things that would be good to test:

- what happens if you send invalid options to `preventScroll`, like `preventScroll: 'top'`?
- Does passing the options actually prevent scroll (check scroll position when passingg option and not
- maybe some other cases you think of

To run the tests:

- within `cypress` root, run `yarn`
- run `yarn workspace @packages/driver cypress:open`
- click on the test you're writing to run it within Cypress

Instructions for running the `driver` tests can always be found here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/README.md

2021-06-23 09:40 UTC, Calyhre commented
> this was not originally an intended option for `.focus()`

I'm not following, the `.focus()` method is the one provided by the browser. When Cypress is intercepting it, it actually swallows the options and potentially break the user code. This is a bug in the Cypress runner.

> Some things that would be good to test:
> 
>     * what happens if you send invalid options to `preventScroll`, like `preventScroll: 'top'`?
>
>     * Does passing the options actually prevent scroll (check scroll position when passingg option and not

This is another point I don't get. The `preventScroll` is a browser option, implemented and ran by it. Would the point here be to test that the browser is actually doing what the W3 specs describe?

I do agree it misses some regression specs to be sure Cypress is actually passing the focus options down to the browser. I'll see if I can work on adding them :+1:

2021-06-23 13:48 UTC, jennifer-shehane commented
@Calyhre Ok, I think I may have misunderstood the purpose of the PR without a test provided. 

Could you provide an example of a test that would previously break and a test that is now passing due to this change? Ideally, this would be included in our repo so that we don't break this behavior in the future. Thanks.

2021-06-23 14:51 UTC, Calyhre commented
@jennifer-shehane Done, I added a spec that used to fail but now pass with the changes. Let me know what you think.

2021-06-23 15:16 UTC, Calyhre commented
It should fixes https://github.com/cypress-io/cypress/issues/15294

2021-06-23 21:00 UTC, jennifer-shehane commented
@Calyhre Thanks! We'll have someone review it from our team.

2021-06-24 14:58 UTC, Bkucera approved these changes

2021-06-24 15:32 UTC, merged