fix: allow "localhost" in `cy.intercept`'s RouteMatcher
cypress-io/cypress pull request #17068
Opened 2021-06-23 01:07 UTC by sainthkh

- Closes #17015

### User facing changelog

Allow "localhost" in `cy.intercept`'s RouteMatcher.

### Additional details
- Why was this change necessary? -> `localhost` is a valid hostname. But it became an error.
- What is affected by this change? -> N/A
- Any implementation details to explain? -> N/A

### How has the user experience changed?

N/A

### PR Tasks
- [x] Have tests been added/updated?

2021-06-23 01:29 UTC, sainthkh commented
flaky failures.

2021-06-28 13:25 UTC, jennifer-shehane commented
@sainthkh Zach is out of town for the week, so this review will be delayed til he gets back. I think he mentioned that this should be expanded a bit to include more than just "localhost", but I'm not sure exactly what he meant by that.

2021-07-07 18:33 UTC, flotwig requested changes

2021-07-07 18:33 UTC, flotwig commented on packages/driver/src/cy/net-stubbing/add-command.ts
> +  if (_.isString(routeMatcher.hostname) && !isValidDomain(routeMatcher.hostname, { allowUnicode: true }) && routeMatcher.hostname !== 'localhost') {
This change is not comprehensive enough, I think any hostname should be allowed to work here. For example, `somemachine`, `local6`, `router`, etc. should all work.

You could try to patch `isValidDomain`: https://github.com/miguelmota/is-valid-domain/issues/23

Alternatively, you could kludge it here, by checking if `hostname` contains a `.`, and if not, appending `.sometld` before passing it to `isValidDomain`...

2021-07-08 19:56 UTC, flotwig commented on packages/driver/src/cy/net-stubbing/add-command.ts
> +  if (_.isString(routeMatcher.hostname) && !isValidDomain(routeMatcher.hostname, { allowUnicode: true }) && routeMatcher.hostname !== 'localhost') {
or https://github.com/miguelmota/is-valid-hostname, of course

2021-07-12 13:59 UTC, flotwig approved these changes

2021-07-12 14:17 UTC, merged