fix: add missing clientCertificate type to ResolvedConfigOptions
cypress-io/cypress pull request #18028
Opened 2021-09-08 22:26 UTC by ImCesar

- Closes https://github.com/cypress-io/cypress/issues/17799

### User facing changelog
Add missing clientCertificate field type definition to ResolvedConfigOptions

### Additional details
Provides code completion for clientCertificate

### PR Tasks
- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-09-08 22:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=18028) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=18028) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=18028) it.</sub>

2021-09-09 02:52 UTC, lmiller1990 requested changes
Just one change, made a recommendation.

I wonder if we could also use this new type in place of this one to avoid duplication? https://github.com/cypress-io/cypress/blob/956e1c56d2857519b0b6842ea4e35b938cb5ad85/packages/network/lib/client-certificates.ts#L99

2021-09-09 02:52 UTC, lmiller1990 commented on cli/types/cypress.d.ts
> +    clientCertificate: ClientCertificate[]
```suggestion
    clientCertificates: ClientCertificate[]
```

2021-09-09 15:31 UTC, lmiller1990 approved these changes

2021-09-09 15:34 UTC, ImCesar commented
> Just one change, made a recommendation.
> 
> I wonder if we could also use this new type in place of this one to avoid duplication?
> 
> https://github.com/cypress-io/cypress/blob/956e1c56d2857519b0b6842ea4e35b938cb5ad85/packages/network/lib/client-certificates.ts#L99

This one looks different than the type defined in the documentation. It seems to me that the one above defines the actual ClientCertificate as it's used in code and the one defined for this issue is how a ClientCertificate is defined for configuration.

2021-09-09 18:01 UTC, merged

2021-09-09 18:02 UTC, JessicaSachs commented
LGTM, failing test is known flake.