Add iframe feature policy for camera/microphone
cypress-io/cypress pull request #18107
Opened 2021-09-15 10:04 UTC by EtienneBruines

- Closes #8849 

### User facing changelog
Fixes `getUserMedia()` for Firefox 92+

### Additional details
Permissions must be specified to allow access to the (fake) camera and microphone from within the Cypress iframe.

### How has the user experience changed?
It has not, this is a bugfix.

### PR Tasks
None applicable.

2021-09-16 13:43 UTC, jennifer-shehane commented
@EtienneBruines Thanks for the contribution! We will need some tests written to verify this new behavior. 

There is a Contributing Guide that covers how to contribute and get Cypress running locally  here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

Let us know if you have trouble getting the tests running locally.

2021-09-16 13:44 UTC, EtienneBruines commented
@jennifer-shehane Would the Cypres team like a test verifying the attribute is present, or one verifying the `getUserMedia` works?

2021-09-16 15:08 UTC, EtienneBruines commented
Awaiting test-results now, I potentially need to add a `media.navigator.permission.fake` as well - see also https://bugzilla.mozilla.org/show_bug.cgi?id=1730163

2021-09-20 15:24 UTC, flotwig requested changes
@EtienneBruines It seems like the test is failing since the expectation does not quite match: https://app.circleci.com/pipelines/github/cypress-io/cypress/23753/workflows/b86cd9af-9f8f-4ab6-8000-cbc34aff27af/jobs/880555/tests#failed-test-2

Once the test is passing this LGTM

You can run these tests locally by using `yarn cypress:open -P ./packages/driver` from the root of the monorepo.

2021-12-21 16:54 UTC, jennifer-shehane commented
Unfortunately we have to close this PR due to inactivity. Please open a new PR addressing the original issue and any requested changes.

2021-12-21 16:54 UTC, closed without merging