don't reassing the error name if it already exists
cypress-io/cypress pull request #18259
Opened 2021-09-27 09:25 UTC by wKich

### User facing changelog
Don't reassign the error name if it already exists

### Additional details
Throwing custom errors from the tests, those defined like this:
```js
MyCustomError extends Error {
  get name() { return 'MyCustomError' }
}
```
leads to failing Cypress with the error `TypeError: Cannot set property name of [object Object] which has only a getter`
Affected Cypress versions >= 8.3.0

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-09-27 09:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=18259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=18259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=18259) it.</sub>

2021-09-27 13:45 UTC, jennifer-shehane requested changes
@wKich Thanks! Can you add a test around this new behavior?

There is a Contributing Guide that covers how to contribute and get Cypress running locally in generally here: https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md

Instructions for running the `driver` tests can always be found here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/README.md

2021-09-28 08:34 UTC, wKich commented
@jennifer-shehane done

2021-09-30 14:48 UTC, chrisbreiding approved these changes
Looks good 👍 Thanks for the PR!

2021-09-30 14:48 UTC, merged