feat: cypress to update projectId in simple cypress.config.js
cypress-io/cypress pull request #18351
Opened 2021-10-04 22:11 UTC by elevatebart

- Closes https://cypress-io.atlassian.net/browse/UNIFY-379

### User facing changelog
If the config file `cypress.config.js` is a plain object, users can now connect their project with the Cypress cloud without having to update their config file manually.

### Additional details
The module `config-file-updater` now handles all updates of values in both the root of the config and in nested values.

Errors are handled in the desktop-gui

### How has the user experience changed?

New error screen when js file is too complicated:

<img width="1004" alt="Screen Shot 2021-10-04 at 4 58 52 PM" src="https://user-images.githubusercontent.com/5592465/135931564-51b9b6de-7075-4991-86ae-daf44800b17a.png">

If retry fails:

<img width="918" alt="Screen Shot 2021-10-04 at 5 11 11 PM" src="https://user-images.githubusercontent.com/5592465/135931710-02f1b942-e530-4134-85c2-126a58f8331f.png">

### PR Tasks

- [x] Have tests been added/updated?

2021-10-05 13:54 UTC, jennifer-shehane commented
Getting this error currently on this branch when I don't have a cypress.json file. 

<img width="1021" alt="Screen Shot 2021-10-05 at 8 53 26 AM" src="https://user-images.githubusercontent.com/1271364/136036963-82b0402d-3710-4a42-b22a-f938e4c24988.png">

I'd like to refine the design of this but haven't been able to get it running locally or run the component tests.

2021-10-05 20:48 UTC, jennifer-shehane requested changes
Following the recreation instructions, I'm getting this error when opening Cypress so can't get to the Runs tab. 

<img width="810" alt="Screen Shot 2021-10-05 at 3 43 20 PM" src="https://user-images.githubusercontent.com/1271364/136100048-463fdc7f-4bff-4ea6-82b3-663244f6e53f.png">

I tried to switch the config.js file to module.exports and I get a different error:

<img width="721" alt="Screen Shot 2021-10-05 at 3 47 42 PM" src="https://user-images.githubusercontent.com/1271364/136100385-2ae7245e-8177-46ef-84c8-f4ca0bb1d8fa.png">

2021-10-06 18:00 UTC, flotwig requested changes
After registering a project, I still get the `<record-key>` placeholder like so: 
![image](https://user-images.githubusercontent.com/1151760/136257398-fda32f09-a516-4521-9fc2-60e3644f4fb6.png)

The correct record key appears after a couple of seconds, but on the first load it seemed to take forever until I moved my cursor a bunch. Maybe a loading indicator is needed here...

---- 

I used the following `cypress.config.ts` and it produced... weird output:

Before:

```ts
export default {
  projectId: undefined, // i'll set it up later ok?
  fixturesFolder: false,
  componentFolder: "src",
  testFiles: "**/*.spec.{tsx,js}",
  pluginsFile: "cypress/plugins/index.ts"
}
```

After:

```ts
export default {
  projectId: "adhgps",
  projectId: undefined, // i'll set it up later ok?
  fixturesFolder: false,
  componentFolder: "src",
  testFiles: "**/*.spec.{tsx,js}",
  pluginsFile: "cypress/plugins/index.ts"
}
```

I guess this is technically valid TS but it fails TS strict mode and also it is incorrect, `module.exports.projectId` will take the latter value of `undefined`.

This had a fun side effect of the `desktop-gui` temporarily acting like I had a `projectId` set and then refreshing and acting like I had never connected to Cypress Cloud at all. Also, the `<record-key>` placeholder stayed blank after this.

This is a bug, right?

----

Additionally, I agree with Jennifer that the errors could use some work... imo they are a little overwhelming as it is.

2021-10-06 18:00 UTC, flotwig commented on packages/desktop-gui/src/runs/manual-setup.jsx
> +        <span dangerouslySetInnerHTML={{ __html: md.render(error.message) }} />
Shouldn't it use `<MarkdownRenderer>` here so that external links will be sent through `ipc.openExternal`?

2021-10-06 18:00 UTC, flotwig commented on packages/server/lib/errors.js
> +      // TODO: update with cypress language
is this meant to be resolved after this is merged? is there an issue for it?

2021-11-10 04:11 UTC, closed without merging