chore(launchpad): launchpad UI tweaks
cypress-io/cypress pull request #18369
Opened 2021-10-05 21:18 UTC by marktnoonan

- Closes https://cypress-io.atlassian.net/browse/UNIFY-378

### Additional details

This PR fixes the images in the component testing framework picker, improves the Switch and Button components to be more consistent with the specific variations present in the designs in Figma, and tweaks colors and spacing throughout launchpad to better align with Figma.

In more detail, this PR:

- Adjusts sizes and colors for our Button component (also removes the icon sizing from the button component as it causes extra height to be added when icons are present, please correct me if this needs to stay)
- Improves keyboard behavior of the copy button. The button itself is now the next item in the tab order after choosing to install something manually (the rare positive tabindex that makes sense). The offscreen textarea utility used is this component is no longer keyboard-focusable.
- The Switch is using our design colors and now has switch semantics. It has variations for the 4 sizes in Figma.
- New shortcuts for a default focus and hocus style have been added. Focus on dark indigo buttons is still a little hard to see but I think that's a think we can return to with Ryan some other time
- "Select Framework" picker got a little cleanup
- Button Bar now associates a label with the switch via a `name` prop
- Makes "manual install" the only option for `InstallDependencies` - the hope was to close https://cypress-io.atlassian.net/browse/UNIFY-355 but the image in that ticket is old and there is a new design to implement. Still the changes here are in the right direction so I left them in.
- Adds hocus styles and keyboard accessibility to the Testing Type cards. The a11y implementation is not idea but didn't want to get too in the weeds. The strings bound under `:role` previously weren't valid roles, I've renamed that prop to `function`, it seems like it will come in handy when content arrives for those cards but isn't doing anything atm.
- Simplifies WizardLayout CSS a lil bit
- Imports framework SVGs as urls for image tag src values
- Rearranges the Wizard text in the constants file as the titles and description had gotten jumbled at some point.

### How has the user experience changed?

More things match Figma and keyboard behavior is standardized.

2021-10-05 21:33 UTC, JessicaSachs requested changes

2021-10-05 21:33 UTC, JessicaSachs commented on packages/types/src/constants.ts
> +    description: 'Confirm the front-end framework and bundler fused in your project.',
```suggestion
    description: 'Confirm the front-end framework and bundler used in your project.',
```

2021-10-06 00:03 UTC, lmiller1990 requested changes
Can we verify launchpad CT tests are passing locally before merging? Thanks

2021-10-06 13:26 UTC, marktnoonan commented on packages/launchpad/src/setup/TestingTypeCards.vue
> +      :function="firstTimeCT ? 'setup-component-testing' : 'launch-component-testing'"
Thanks for pointing these out, and agreed 👍

2021-10-06 15:31 UTC, merged