feat: Add 'slowTestThreshold' and fix this.slow() inside specs
cypress-io/cypress pull request #18496
Opened 2021-10-14 17:27 UTC by BlueWinds

- Closes #447
- Duplicate of https://github.com/cypress-io/cypress/pull/18371, which targeted 9.0-release rather than develop, since these are not breaking changes.

### User facing changelog
- Adds `slowTestThreshold` config option to customize slow test threshold.
- Changes the default slow test threshold from 75ms (mocha's default) to 10000ms for e2e tests and 250ms for component tests. To restore the old behavior, you can add `"slowTestThreshold": 75` to your cypress configuration.

### Additional details
A test that executes for longer than the slowTestThreshold time will be highlighted in yellow with the default spec reporter. This is a visual change only - slow tests still pass.

### PR Tasks
- [x] Have tests been added/updated? I have added some relevant unit tests, but welcome further suggestions.
- [x] Has the original issue or this PR been tagged with a release in ZenHub? 
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/4145
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [x] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-10-15 17:22 UTC, jennifer-shehane requested changes
We're going to do a product review next week on this, so hold off on merging until then. I think it will be fine though.

2021-10-25 13:42 UTC, chrisbreiding requested changes

2021-10-25 17:31 UTC, chrisbreiding requested changes
Looks like some of the files from the unified branch made it into this PR - `packages/app`, `packages/frontend-shared`, etc.

2021-10-25 18:08 UTC, chrisbreiding approved these changes

2021-10-25 18:31 UTC, jennifer-shehane approved these changes

2021-10-25 18:49 UTC, merged