chore(driver): fix integration test retry configuration
cypress-io/cypress pull request #18643
Opened 2021-10-26 14:38 UTC by emilyrohrbough

Test flakiness in `packages/driver` has been observed and tests have not been retried as expected. This change enables the retry configuration in the integration tests via the cypress configuration.

2021-11-08 21:36 UTC, emilyrohrbough commented
Looking at the failures / flakey tests listed in the last Cypress comment, retries have been enabled.

2021-11-08 22:10 UTC, emilyrohrbough commented on packages/driver/cypress/support/defaults.js
> +const isActuallyInteractive = Cypress.config('isInteractive')
This is the change to enable retries

2021-11-08 22:10 UTC, emilyrohrbough commented on packages/driver/cypress/support/utils.js
> +export const assertLogLength = (logs, expectedLength) => {
Helper to log the list of logs received to help debug when log length is different than expected.

2021-11-09 16:32 UTC, mjhenkes commented on packages/driver/cypress/integration/commands/navigation_spec.js
> +    it('(FLAKY) sets timeout to Cypress.config(pageLoadTimeout)', {
With retries setup, are these passing reliably now?
```suggestion
    it('sets timeout to Cypress.config(pageLoadTimeout)', {
```

2021-11-09 16:44 UTC, mjhenkes commented on packages/driver/cypress/integration/commands/navigation_spec.js
> +    it('(FLAKY) sets timeout to Cypress.config(pageLoadTimeout)', {
```suggestion
    it('sets timeout to Cypress.config(pageLoadTimeout)', {
```

2021-11-09 16:44 UTC, mjhenkes commented on packages/driver/cypress/integration/commands/navigation_spec.js
> +    it('(FLAKY) sets timeout to Cypress.config(pageLoadTimeout)', {
```suggestion
    it('sets timeout to Cypress.config(pageLoadTimeout)', {
```

2021-11-09 16:55 UTC, flotwig requested changes
My supplied test case from earlier works, but some stuff is still not retrying: https://app.circleci.com/pipelines/github/cypress-io/cypress/26345/workflows/825f5705-1c96-4ff5-b0d4-f43234e78612/jobs/994369/parallel-runs/1

There's no evidence of retrying on that failure in the logs.

You can observe this locally running `yarn cypress:run --headed --no-exit`, *some tests* will fail and not be retried, and *some* will be retried. Not sure what's happening, there's no per-test config in this file...

2021-11-09 18:37 UTC, flotwig commented
> @flotwig You linked to the CircleCI logs. If you look in the [Cypress Dashboard results ](https://dashboard.cypress.io/projects/ypt4pf/runs/23408/test-results/93790e21-34ce-4d74-ad3a-929acb822437?statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D) you will see retries are working.

Some tests are retrying, some tests aren't retrying. That test code does work now, but some real specs in `assertions_spec` are still not retrying.

> > You can observe this locally running yarn cypress:run --headed --no-exit, some tests will fail and not be retried, and some will be retried. Not sure what's happening, there's no per-test config in this file...
> 
> I am currently running `yarn workspace @packages/driver cypress:run --headed` and have yet to observed this behavior , but there are a lot of tests here & haven't made it through the `cypress/integration/commands/actions` yet. It'll take while to get through them locally. Can you share which specs (or the video recording) where you observed this so I can dig in deeper?

Observe the results of `yarn cypress:run --headed --no-exit --spec **/assertions_spec.js` (to run the spec with the test that's not retrying in CI):

https://user-images.githubusercontent.com/1151760/140983890-7814d2b3-da51-4a47-b32c-f3d8740b6a9b.mp4

Earlier tests in the file do retry, so I'm not sure what causes this yet. But, it's not retrying.

2021-11-09 19:15 UTC, emilyrohrbough commented
@flotwig  Thanks for the example. I'll take a look.

2021-11-09 20:28 UTC, flotwig approved these changes

2021-11-09 20:32 UTC, emilyrohrbough commented on packages/driver/src/cypress/mocha.ts
> +      }
For anyone curious to reproduce this issue, you can comment this out and runt his test to consistently see the error shown in the video Zach linked: 

```js
      it('should not be true', { defaultCommandTimeout: 1 }, (done) => {
        cy.on('fail', (err) => {
          expect(err.message).to.eq('expected false to be true')

          done()
        })

        cy.noop(false).should('be.true')
      })
```

2021-11-09 20:40 UTC, chrisbreiding approved these changes

2021-11-09 21:16 UTC, merged