fix: use void return type for command implementations
cypress-io/cypress pull request #18967
Opened 2021-11-17 21:03 UTC by remcohaszing

- Closes #18915

### User facing changelog
The TypeScript return type of Cypress command implementations has been fixed.

### Additional details
The `ConditionalKeys` type has been copied from `type-fest`, because I wasn’t sure if you want me to add it as a dependency.

### How has the user experience changed?
Custom Cypress command implementations no longer show a TypeScript error when they use a chainable return value.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-11-22 14:34 UTC, chrisbreiding requested changes
This seems to allow any return value from a custom command implementation.

9.0.0:

![Screen Shot 2021-11-22 at 9 30 14 AM](https://user-images.githubusercontent.com/1157043/142879322-170d656a-70e0-48d1-b332-ce226cfa94f4.png)

This PR:

![Screen Shot 2021-11-22 at 9 31 51 AM](https://user-images.githubusercontent.com/1157043/142879412-e17ba3b1-3a10-4399-938c-01b8f8201ac6.png)

2021-11-22 14:44 UTC, remcohaszing commented
@chrisbreiding:

> This seems to allow any return value from a custom command implementation.

That’s correct. Based on feedback from #18915 that is the desired behaviour, because the return value is discarded. However, your comment implies this is incorrect. Could you verify this, and if so, explain what is allowed to be returned?

2021-11-22 19:52 UTC, BlueWinds commented
> @chrisbreiding:
> 
> > This seems to allow any return value from a custom command implementation.
> 
> That’s correct. Based on feedback from #18915 that is the desired behaviour, because the return value is discarded. However, your comment implies this is incorrect. Could you verify this, and if so, explain what is allowed to be returned?

Agreed, allowing any return value seems correct to me. Consider the following:
```
it('works', () => {
  Cypress.Commands.add('returnTrue', () => true)
  cy.returnTrue().should('eq', true)
})
```

This is perfectly valid and supported, and our types should reflect that. We wrap the function the user passes in in order to ensure the chainability - which means that the function the user passes to `Commands.add` does not itself need to return a chainable value.

2021-11-23 14:13 UTC, chrisbreiding commented
> which means that the function the user passes to Commands.add does not itself need to return a chainable value

I agree with that. But it does weaken the type safety a lot, doesn't it? The type can say the custom command should return an element, while the custom command itself returns a string, and that passes the type-checking.

2021-11-23 14:50 UTC, chrisbreiding commented
> the actual behaviour can’t be described using TypeScript

That was my hunch, but I guess I was hoping there was some way to express the types correctly with maximal type safety. I'm far from a TypeScript expert, so I certainly defer to your knowledge on the matter.

> It’s better to have less strict types that are correct than super strict incorrect types that make get in the way of using the code correctly.

Definitely agree.

> So, if I understand correctly:
> 
>     commands always return a chainable when used
>     command implementations may return a chainable
>     command implementations may return a value that will be wrapped in a chainable
>     command implementations may return undefined

Yes, I think that sums it up nicely.

---

Sorry, I should have just asked some questions instead of submitting a review. I was mostly trying to understand the implications of this. Now that I understand the issue better, it seems like this is the best we can do to add correct types for custom commands.

2021-11-23 14:51 UTC, chrisbreiding requested changes

2021-11-23 14:51 UTC, chrisbreiding commented on cli/types/cypress-type-helpers.d.ts
> +	// Wrap in `NonNullable` to strip away the `undefined` type from the produced union.
Could the tabs in this file be converted to spaces, for the sake of consistency with the rest of the codebase?

2021-11-23 15:15 UTC, remcohaszing commented
If I change the return type to `undefined`, I’m enforced to return explicitly, which is undesired. I think it’s best to keep this as-is.

I just want to add that the `void` type can be changed to `unknown` or `any` as well. These all yield the same result.

2021-11-23 16:55 UTC, chrisbreiding approved these changes

2021-11-24 19:16 UTC, emilyrohrbough approved these changes

2021-11-29 16:27 UTC, chrisbreiding commented
Closing in favor of #19003 as [suggested here](https://github.com/cypress-io/cypress/pull/19003#issuecomment-979054587).

2021-11-29 16:27 UTC, closed without merging