WIP: feat(unify): toggle specs list
cypress-io/cypress pull request #18991
Opened 2021-11-18 21:14 UTC by mapsandapps

* override global SVG styles ([1x56ga2](https://app.clickup.com/t/1x56ga2))
* expand and collapse specs list via reporter header ([1m9167h](https://app.clickup.com/t/1m9167h)) (paired with Mark)
* make reporter header visible when running in unified UI

Closes https://cypress-io.atlassian.net/browse/UNIFY-551

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-11-18 21:20 UTC, mapsandapps commented
@lmiller1990 @marktnoonan following up on conversation from #18921 

i got one-way communication working, but we do need to communicate back the other way as well, so the button will know if the spec list is open or not and display the correct icon. i didn't have time to start digging into that today, but i should have time to start looking at it tomorrow.

2021-12-01 17:09 UTC, marktnoonan commented on packages/reporter/cypress/integration/unit/events_spec.ts
> -
This test change is pretty representative of what's going on in this PR - we no longer "focus the launchpad that's showing the specs list" but instead, change it as a setting that's part of reporter state, just like `autoScrollingEnabled` has worked until now.

2021-12-01 17:11 UTC, marktnoonan commented on packages/reporter/src/lib/shortcuts.ts
> +        events.emit('save:state')
This fixes a bug where this value was not getting saved when the shortcut key was used.

2021-12-01 22:07 UTC, ZachJW34 reviewed
Tested, works great! Just a few minor comments.

We should change the shortcuts to properly reflect what's happening. `f` says it toggles between specs whereas `command + b` says it toggles the list.

<img width="475" alt="Screen Shot 2021-12-01 at 4 05 15 PM" src="https://user-images.githubusercontent.com/25158820/144321773-282b3271-a169-43cd-877e-37b32282173c.png">

2021-12-01 22:07 UTC, ZachJW34 commented on packages/server/lib/project-base.ts
> +      onSavedStateChanged: (state: any) => {
This change can be undone

2021-12-01 22:29 UTC, mapsandapps commented on packages/reporter/src/header/header.tsx
> +    <Tooltip placement='bottom' title={<p>View All Specs <span className='kbd'>F</span></p>} wrapperClassName='toggle-specs-wrapper' className='cy-tooltip'>
We discussed this already, but mentioning it here too: Please change the tooltip to toggle between “Expand Specs List” and “Collapse Specs List”. Sorry I missed this when I was doing the initial work for this ticket!

2021-12-01 22:59 UTC, JessicaSachs commented on packages/reporter/cypress/integration/shortcuts_spec.ts
> +      // checking the aria-expanded state of the button confirms thos
Please install the Code Spell plugin :-)

2021-12-02 12:36 UTC, lmiller1990 commented on packages/app/src/runner/SpecRunner.vue
> +runnerUiStore.setAutoScrollingEnabled(props.gql.localSettings.preferences.autoScrollingEnabled ?? true)
I foresee a bunch of default values coming in the future, we might want a `setDefaults` function at some point but prob fine for now. Good to keep in mind if this pattern of setting defaults expands.

2021-12-02 12:37 UTC, lmiller1990 commented on packages/app/src/runner/SpecRunner.vue
> +    runnerUiStore.setIsSpecsListOpen(state.isSpecsListOpen)
Hmm now I see this I wonder if we want a single `updateState` in the `runnerUiStore` that would more or less 1:1 map to `setPreferences.executeMutation`. Thoughts? Consider we have many more things to come like appX, appY, paneWidth etc - we likely want to have some pattern to consistently update the local Pinia store, as well at GraphQL.

2021-12-02 12:42 UTC, lmiller1990 reviewed
Code seems fine but I see this abstraction with the graphql preferences and local state getting out of sync and unmanageable really quickly, what do you think of a quick abstraction to wrap it all up? See here: https://github.com/cypress-io/cypress/pull/18991/files#r761052458

2021-12-02 12:42 UTC, lmiller1990 commented on packages/app/src/runner/SpecRunner.vue
> +    runnerUiStore.setIsSpecsListOpen(state.isSpecsListOpen)
Eg, I wonder if we want to write some kind of abstraction like an `usePreferences` composables, that does something like:

```ts
function usePreferences (preference: 'autoScrollingEnabled' | ... others ..., value: any) {

  function update(preference: 'autoScrollingEnabled' | ... others ..., value: any) {
    runnerUiStore.setPreference(preference, value)
    setPreferences.executeMutation({ value: JSON.stringify({ [preference]: value ) })
  }

  return {
    update
  }
}
```

What do you think? Then we just do

```ts
const prefs = usePreferences()
prefs.update('autoScrollingEnabled', false)
```

And everything will stay in sync. We could strongly type this; the work has already been done in `packages/types/src/preferences.ts`.

2021-12-02 13:04 UTC, marktnoonan commented on packages/reporter/cypress/integration/shortcuts_spec.ts
> +      // checking the aria-expanded state of the button confirms thos
Done and done :)

2021-12-02 13:21 UTC, marktnoonan commented
> We should change the shortcuts to properly reflect what's happening. `f` says it toggles between specs whereas `command + b` says it toggles the list.

Good point @ZachJW34. And it's not totally clear which to remove. `Cmd+b` is the specs list toggle from the component test runner, and `f` is the old way of focusing the spec list in the launchpad. Possibly we should support both if people have adjusted to using them, even though they have converged to do the same thing.

I think there is a bit more work to do on the keyboard shortcuts popup in general, it's actually missing several as well. I'll update the text for `f` and make a ticket to revisit the overall shortcuts if we don't already have that.

2021-12-03 19:49 UTC, elevatebart requested changes
Some changes, I am going to test it locally

2021-12-03 19:49 UTC, elevatebart commented on packages/app/cypress/e2e/integration/navigation.spec.ts
> +
Was this changed on purpose ?

2021-12-03 19:49 UTC, elevatebart commented on packages/app/src/navigation/KeyboardBindingsModal.spec.tsx
>  describe('SidebarNavigationRow', () => {
This one would be my fault...

```suggestion
describe('KeyboardBindingsModal', () => {
```

2021-12-03 19:49 UTC, elevatebart commented on packages/app/src/runner/SpecRunner.vue
>        <HideDuringScreenshot class="bg-white p-4">
```suggestion
      <HideDuringScreenshot class="bg-white p-16px">
```

2021-12-03 19:49 UTC, elevatebart commented on packages/app/src/runner/SpecRunner.vue
> +        class="flex h-full bg-gray-100 p-4 justify-center"
```suggestion
        class="flex h-full bg-gray-100 p-16px justify-center"
```

2021-12-03 23:20 UTC, marktnoonan commented on packages/app/cypress/e2e/integration/navigation.spec.ts
> +
Nope!

2021-12-03 23:56 UTC, JessicaSachs approved these changes
tested manually.

2021-12-03 23:56 UTC, merged