Lmiller1990/saved state graphql
cypress-io/cypress pull request #19082
Opened 2021-11-24 04:54 UTC by lmiller1990

Make the GraphQL interface for access/updating local preferences more generic.

```gql
# query
{
  localSettings {
    preferences {
      isSpecsListOpen
    }
  }
}

# update
mutation M {
  # value is JSON.stringify({ k1: value1, k1: value2, ... })
  setPreferences(value: "{ \"isSpecsListOpen\": true }")
}
```

2021-11-24 14:09 UTC, marktnoonan requested changes
I think one change is needed for the default values for the preference to survive the initialization, otherwise this works great.

2021-11-29 00:36 UTC, lmiller1990 commented on packages/graphql/src/schemaTypes/objectTypes/gql-Mutation.ts
>          value: nonNull(stringArg()),
Updated, good catch

2021-11-29 00:36 UTC, lmiller1990 commented on packages/types/src/preferences.ts
> +export const defaultPreferences: AllowedState = {
Good point... updated to set defaults in the same place as we load the settings. Local preferences will override defaults.

2021-11-29 00:36 UTC, lmiller1990 commented on packages/types/src/preferences.ts
> +export const defaultPreferences: AllowedState = {
https://github.com/cypress-io/cypress/pull/19082/commits/6b83406160a83a7ada344ff6123fd43bec018103

2021-11-29 12:33 UTC, marktnoonan approved these changes
Looks good, I pushed 1 commit for an out of date description.

2021-11-29 13:04 UTC, merged