fix: set the context when overwriting .clock command
cypress-io/cypress pull request #19158
Opened 2021-11-30 15:21 UTC by Hugo-Hache

### User facing changelog
Previously overwriting .clock command did not preserve this context. Now the following works:

```js
Cypress.Commands.overwrite('clock', (originalCommand, ...args) => {
  return originalCommand(...args)
})

cy.clock
```

### Additional details
This MR is vastly inspired from #9589

### PR Tasks

- [x] Have tests been added/updated?

2021-11-30 15:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=19158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=19158) before we can accept your contribution.<br/><hr/>**Hugo Hache** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=19158) it.</sub>

2021-11-30 15:23 UTC, Hugo-Hache commented
Thanks @bahmutov for #9589, without it I would never have been able to know how to fix the crash I was facing.

2021-11-30 17:24 UTC, ryanthemanuel commented on packages/driver/cypress/integration/commands/clock_spec.js
> +    it('overwrite gracefully', () => {
Let's be more explicit about what we're testing here. Something like:

```suggestion
    it('overwrites without crashing', () => {
```

2021-12-01 16:07 UTC, jennifer-shehane commented
@Hugo-Hache Thanks for signing the CLA, unfortunately one of the author of the commits does not match the email address on your GitHub account. Our CLA bot gets confused when they don't match. Here are some solutions to fixing when commits are linked to the wrong user: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

2021-12-01 16:21 UTC, jennifer-shehane requested changes
Update CLA signature

2021-12-01 16:43 UTC, Hugo-Hache commented
@jennifer-shehane fixed the identity of my first commit to match my GitHub account

2021-12-02 15:43 UTC, flotwig approved these changes

2021-12-02 16:40 UTC, ryanthemanuel approved these changes

2021-12-02 17:22 UTC, merged