fix(unify): Do not crash when an ill formed URL request is proxied
cypress-io/cypress pull request #19186
Opened 2021-12-02 02:13 UTC by ryanthemanuel

- Closes #9220 

### User facing changelog

The Cypress App will no longer crash when proxying an ill formed request. For example, if the application under test has a resource of "http: //localhost/asset.js" (notice the extraneous space) the Cypress App will no longer crash. Instead, a debug message will be logged and the asset will fail to load.

### Additional details

The goal here is to treat these ill-formed requests just like any other requests that are problematic (e.g. not found resources).  Thus, we don't attempt to stop the tests outright, but instead just fail the individual request.

### How has the user experience changed?

Before:

Terminal:

![image](https://user-images.githubusercontent.com/4873279/144344749-911b7b20-d2b1-4982-8ee5-b245060d3d69.png)

After:

Terminal:

![image](https://user-images.githubusercontent.com/4873279/144344273-91b3a7a3-4f04-41a1-9340-8c5a2bed8508.png)

Browser Console:

![image](https://user-images.githubusercontent.com/4873279/144344317-f44045a6-1628-4ec2-8a49-97ec2bccf38b.png)

Network:

![image](https://user-images.githubusercontent.com/4873279/144344505-d18aac0d-2c40-4b16-a3fa-3ea8214181a5.png)

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-12-03 16:33 UTC, flotwig requested changes
This fix is good, but could you also add some error handling around the `addContext` call itself? It shouldn't crash the process if it fails. In fact, I don't really see why the promise chain isn't catching the error, is it an unhandled rejection or is there no `.on('error'` handler on the HTTPS server so this error crashes the process?

2021-12-03 22:39 UTC, ryanthemanuel commented
@flotwig I have made the requested changes

2021-12-06 16:04 UTC, flotwig approved these changes
:+1:  Very nice :+1:

2021-12-06 16:35 UTC, BlueWinds approved these changes

2021-12-06 18:13 UTC, merged