chore: apply ux feedback
cypress-io/cypress pull request #19286
Opened 2021-12-07 00:13 UTC by JessicaSachs

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-12-07 15:39 UTC, pstakoun commented on packages/frontend-shared/src/locales/en-US.json
> +      "cloud": "Cypress Cloud Service",
Are we using "Cloud" in this release? I think this is still very much up in the air and may cause confusion if we haven't changed this verbiage throughout services before releasing this.

2021-12-07 19:25 UTC, marktnoonan approved these changes
Pulled this branch and the changes all seem to work just fine.

2021-12-07 20:23 UTC, marktnoonan requested changes
Actually noticed some inconsistent font weights in the header, not sure why we are bold for Docs when focused (and Upgrade always) but not for Browser and Login, but it looks off
![Screen Shot 2021-12-07 at 2 46 00 PM](https://user-images.githubusercontent.com/8340719/145099633-c62cfa3b-aac5-4384-80b8-e885bfa6133a.png)
![Screen Shot 2021-12-07 at 2 45 54 PM](https://user-images.githubusercontent.com/8340719/145099634-f52b3a31-0e44-484f-ab2f-61d37d6a4a20.png)
![Screen Shot 2021-12-07 at 2 45 49 PM](https://user-images.githubusercontent.com/8340719/145099635-7f221130-1285-4b3e-ae9e-92e66d8e0662.png)

2021-12-21 23:01 UTC, marktnoonan submitted a review, later dismissed

2021-12-21 23:02 UTC, marktnoonan commented
I made minor changes to have consistent fonts in the header and resolve some conflicts where @ZachJW34 had made changes that overlapped.

2021-12-22 01:12 UTC, merged