Windows build fix
cypress-io/cypress pull request #19380
Opened 2021-12-15 20:19 UTC by modern-sapien

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2021-12-15 20:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=19380) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=19380) before we can accept your contribution.<br/>**9** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: elevatebart<br/>:white_check_mark: estrada9166<br/>:white_check_mark: mapsandapps<br/>:white_check_mark: ZachJW34<br/>:white_check_mark: marktnoonan<br/>:white_check_mark: ryanthemanuel<br/>:white_check_mark: JessicaSachs<br/>:white_check_mark: tgriesser<br/>:white_check_mark: flotwig<br/>:x: modern-sapien<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=19380) it.</sub>

2021-12-15 21:05 UTC, elevatebart requested changes

2021-12-15 21:05 UTC, elevatebart commented on scripts/gulp/tasks/gulpGraphql.ts
> +  const spawned = spawn('bash.exe', ['graphql-codegen','--watch', '--config', 'graphql-codegen.yml'], {
is this working on macos?

2021-12-15 21:05 UTC, elevatebart commented on scripts/gulp/tasks/gulpWebpack.ts
> +  `bash.exe ${devServer
this is unnecessary, one can simply add the `.cmd` at the end to get the windows version

2021-12-15 21:05 UTC, elevatebart commented
I believe this PR is accomplishing the same goal. https://github.com/cypress-io/cypress/pull/19187

2021-12-16 15:54 UTC, jennifer-shehane commented
@elevatebart Thanks bart. Just wanted to surface in case it was useful. Feel free to close.

2021-12-16 21:10 UTC, closed without merging