feat: Encode URL Iif there is any non-latin character in `cy.visit`
cypress-io/cypress pull request #19509
Opened 2022-01-03 01:09 UTC by sainthkh

- Closes #19355

### User facing changelog

If there is any non-latin character in `cy.visit` URL, you can encode them with `encodeIfNecessary` option.

### Additional details
- Why was this change necessary? => For those who wants to test their pages with the URL with non-latin characters, they had to encode them manually. This solves that problem. 
- What is affected by this change? => N/A
- Any implementation details to explain? => This checks if the URL has the character that's not `[A-Za-z0-9_.\-~%:/]`.

### How has the user experience changed?

**Before:**

```js
it('t', () => {
  cy.visit(encodeURI('https://seototo.net/한글-도메인-사용해도-될까-한글-도메인의-장단점-소/amp/'))
})
```

It would fail if URL is already encoded like below:

```js
it('t', () => {
  cy.visit(encodeURI('https://seototo.net/%ED%95%9C%EA%B8%80-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%8F%84-%EB%90%A0%EA%B9%8C-%ED%95%9C%EA%B8%80-%EB%8F%84%EB%A9%94%EC%9D%B8%EC%9D%98-%EC%9E%A5%EB%8B%A8%EC%A0%90-%EC%86%8C/amp/'))
}) // => fail.
```

**After:**

```js
it('t', () => {
  cy.visit('https://seototo.net/한글-도메인-사용해도-될까-한글-도메인의-장단점-소/amp/', {
    encodeIfNecessary: true,
  })
})
```

It passes even if it's already encoded:

```js
it('t', () => {
  cy.visit('https://seototo.net/%ED%95%9C%EA%B8%80-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%8F%84-%EB%90%A0%EA%B9%8C-%ED%95%9C%EA%B8%80-%EB%8F%84%EB%A9%94%EC%9D%B8%EC%9D%98-%EC%9E%A5%EB%8B%A8%EC%A0%90-%EC%86%8C/amp/', {
    encodeIfNecessary: true,
  }) // => pass
})
```

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-01-04 20:54 UTC, emilyrohrbough requested changes
@sainthkh This change appears to add a convient wa

2022-01-06 03:11 UTC, sainthkh commented
There were 2 requests in your review.

## Test about the redirection

I re-read the issue and it was a bit weird. It generates 302 redirection which can only be done on the server side. And the request was `/vida`, not a URL with non-latin texts. It should work correctly without this change on Cypress's side. I don't know what server the user uses, but there might be a setting that removes accents. 

And as Cypress version 2.88.10 deosn't exist and we don't have the user's server code, we cannot replicate the problem.

But non-latin requests don't work anyway, I believe this PR is still valid and provides easy-to-read way to use non-latin characters in URLs.

## About `cy.intercept` and `cy.request`.

All `cy.visit`, `cy.intercept`, `cy.request` make a request to the server (or the mocked server for `cy.intercept`'s case). But they don't share code on the client side. This change doesn't affect them.

2022-01-12 15:49 UTC, emilyrohrbough commented
Hey @sainthkh . We discussed this enhancement in our Product Review meeting earlier this week. I apologize for not getting back quicker. There are a few things we’d like to research and confirm before moving forward with this enhancement.

The goal of the research is to determine how the browser handles urls with non-latin characters and determining if we have correctly implemented this in Cypress.

The questions we had are:

- To understand what the browser does…
    - How the browsers handle urls with non-latin characters today?
    - Are these behaviors consistent between the browser we support? 
- Have we aligned / implemented the W3 spec correctly?
    - If no, what are we missing?
- Do we need this enhancement or do we need to correct our logic? 

I had originally asked about `cy.request` and `cy.intercept` because although this enhancement did not impact those commands, this diverged the capabilities and added features to `cy.visit` that would need to be carried forward to these other commands. It’s important to maintain as much parity as possible between the APIs and behaviors of these commands.

2022-01-13 01:25 UTC, sainthkh commented
@emilyrohrbough Thank you for the reply. I've researched about your questions and below are the result and my thoughts. 



### How the browsers handle urls with non-latin characters today?

They handle domain and path differently. 

As for domain, they use [punycode](https://www.w3.org/International/articles/idn-and-iri/#resolvedomain). For example, `JP納豆.例.jp` is converted to `xn--jp-cd2fp15c.xn--fsq.jp`

As for path, they use [percent-encoded text (IRI)](https://www.w3.org/International/articles/idn-and-iri/#iritechnical). For example, `/dir1/引き割り.html` is converted to `/dir1/%E5%BC%95%E3%81%8D%E5%89%B2%E3%82%8A.html`.

These conversion is the job of [user agent](https://www.w3.org/WAI/UA/work/wiki/Definition_of_User_Agent)s (i.e. browsers and other tools that handle web contents).

And the modern browsers usually show punycode and IRI in unicode format in the URL bar. But in some cases, they just show the raw version. [Please check the "Why Is There Punycode in My Browser?" of this article.](https://uxmag.com/articles/a-url-in-any-language)

If a user clicks a Unicode path in an HTML document, browsers automatically convert them to percent-encoded text.



### Are these behaviors consistent between the browser we support?

Yes, Chrome, Firefox, Edge show them in unicode format. Please check the screenshots below:

**Chrome**

![image](https://user-images.githubusercontent.com/8130013/149245932-67ae59a2-c73d-4597-b126-62d186b4626b.png)

**Firefox**

![image](https://user-images.githubusercontent.com/8130013/149245970-adbfdcef-fcf6-487a-8f39-451f43aab566.png)

**Edge**

![image](https://user-images.githubusercontent.com/8130013/149246015-361c1675-78be-4d41-9364-28f02933ba4b.png)

As I wrote above, this might not be the case in your browser if your environment doesn't care Korean.

I guess they implemented this way because they're more visually better for the users. (They're simply easy to understand what's going on.)



### Have we aligned / implemented the W3 spec correctly?

It depends. If Cypress is a user agent, it's no. If not, it doesn't matter. 

As far as I know, Cypress doesn't send HTTP request with `user-agent: Cypress`. But users interact with Web contents with Cypress, I think Cypress can be categorized as a user agent. 

In my opinion, "no" is the right answer. 



### If no, what are we missing?

Those who use the Internet with non-latin characters expect them to be converted automatically. But Cypress only supports manual conversion with `encodeURI` function.



### Do we need this enhancement or do we need to correct our logic?

I decided to create this option because I didn't want to create a breaking change. I thought there might be some users who want this current behavior. 

But not that I think about it, they might be really really few. They might want to test between `/рayрal` and `/paypal`. (The first "p" isn't English "p", it's Cryllic.)

Maybe creating a breaking change with `neverEncodeURI` option might be a better idea. Because I guess there are more users who want automatic conversions than manual ones.



### About `cy.request` and `cy.intercept`. 

Personally, I believe "A problem is not a problem until it's a problem." That's why I said this PR doesn't impact them and thought  I might fix them when an issue was raised. But it would make users think Cypress APIs are not consistent. 

I'll add them after we decide to implement `encodeIfNecessary` or `neverEncodeURI`.

2022-01-26 15:54 UTC, emilyrohrbough commented
Hey @sainthkh . Sorry for the long delay. We discussed your findings in the last Product Review. Reading your notes, it appears that Cypress is not behaving like the browser which is causing unexpected behaviors.

Instead of adding an enhancement to `cy.visit` to try work around this, we are viewing this gap as a bug and would like to fix Cypress’ logic to interpret the domain with puny code and url path with percent-encoding the same way as the browser does.

When this is close, we can determine if we’ll release as a minor-release bug fix or if we need to release as a breaking change. You mentioned you were concerned above passivity; listing/adding example of these cases would be helpful for evaluating how we should release this fix.

2022-02-01 00:50 UTC, sainthkh commented
@emilyrohrbough  

I was concerned because there can be some unexpected use cases. But after thinking about it for a long time, I concluded that my concern doesn't have much base. 

Treating it as a bug is better. If there are real cases that break the test because of that change, we can add options later. It isn't hard.

2022-02-01 02:28 UTC, sainthkh commented
Things that I learned after trying to implement the fix:

* [`URL` class](https://developer.mozilla.org/en-US/docs/Web/API/URL) converts the url to punycode and percent-encoded domain. We don't need any punycode library.
* Punycode conversion isn't necessary with `cy.visit`. `cy.visit('http://JP納豆.例.jp')` simply works without any change. 

Possible Todos:
* support automatic percent-encoding conversion to `cy.visit`
* support automatic percent-encoding conversion to `cy.request`
* support punycode conversion and match to `cy.intercept`.
* support percent-encoding match to `cy.intercept`.

2022-02-01 14:39 UTC, emilyrohrbough commented
@sainthkh Good information. Do you want to do the work in this PR or open a new one? A known issue that you might encounter/solve is https://github.com/cypress-io/cypress/issues/19407 as well.

2022-02-03 02:17 UTC, closed without merging

2022-02-03 02:18 UTC, sainthkh commented
I decided to start fresh. And it seems that I need to start with #19407 and tackle this one later.