Fix: Issue 16102
cypress-io/cypress pull request #19557
Opened 2022-01-05 05:44 UTC by hang-up

- Closes https://github.com/cypress-io/cypress/issues/16102

### User facing changelog
Enable comma separated glob pattern matching for CLI parameter `spec`. Fixes #16102

### Additional details
This PR aims at fixing a bug discovered since `v6.5.0`.
When glob patterns were defined with at least one comma, the original implementation would assume that when parsed as a string, the `spec` argv could be split into an array. 

This assumption holds when the argv is a string of spec files to run: 
- `--spec "cypress/integration/spec-1.spec.js,cypress/integration/spec-2.spec.js"` would give an array similar to
```
[
  "cypress/integration/spec-1.spec.js", 
  "cypress/integration/spec-2.spec.js"
]
```

Unfortunately in the case of comma separated glob pattern, we would end with erroneous paths:
- `--spec 'cypress/integration/{[!fix]*.spec.js,!(_unit)/**/[!fix]*.specs.js}'` would give an array similar to
```
[
  "cypress/integration/{[!fix]*.spec.js", 
  "!(_unit)/**/[!fix]*.specs.js"
]
```

This PR fixes this issue by performing a glob check before mapping the string to an array of spec paths.

### How has the user experience changed?

Following the same file structure as defined in the issue ticket
```
.
├── cypress
│   ├── integration
│       └── _fixtures
│           └── fixture-should-not-match.spec.js
│       └── _unit
│           └── unit-should-not-match.spec.js                  
│       └── sub-level-1
│           └── should-match-level-1.spec.js                   --> this one should match!
│         └── sub-level-2
│             └── should-match-level-2.spec.js                 --> this one should match!
│       └── fixture-should-not-match.spec.js
```
**Before**
![image](https://user-images.githubusercontent.com/8967158/148166404-2ea7822d-4fd5-4a9b-a20e-8402d71546b6.png)

**After**
![image](https://user-images.githubusercontent.com/8967158/148165930-61374b89-40f9-4505-bf8e-1a7777292045.png)

### PR Tasks

- [ ] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-01-05 05:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=19557) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=19557) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=19557) it.</sub>

2022-01-05 17:13 UTC, hang-up commented
I'm just realizing now that some snapshot tests are failing.
I'll await the initial feedback on this PR before taking any steps further (eg. update those snapshots).

2022-01-05 19:03 UTC, jennifer-shehane requested changes
@hang-up The change has the unintended side effect of updating the value that is printed to CLI when showing what Cypress searched for in the specs. We'd like to maintain the original behavior or printing the original search value and not the found values (since this is already printed in the Specs heading). 

Can you update the code to not change the value?

<img width="917" alt="Screen Shot 2022-01-05 at 1 02 15 PM" src="https://user-images.githubusercontent.com/1271364/148273956-feae080c-7c5f-47a8-9c50-724bb3bdb003.png">

2022-01-06 00:03 UTC, hang-up commented
@jennifer-shehane The side effect should have been addressed :)

2022-01-06 19:00 UTC, mjhenkes commented
I believe this solution will break the case where we have multiple globs or a mixture of globs and specific spec files.

ie.
```
--spec"cypress/integration/examples/actions.spec.js,cypress/integration/examples/files.spec.js,cypress/integration/login/**/*"
```
indicating that you want:
* cypress/integration/examples/actions.spec.js
* cypress/integration/examples/files.spec.js
* and any specs that match cypress/integration/login/**/*

I think a better solution would involve escaping the comma and more complex parsing of the string than our current [comma split](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/args.js#L121).

2022-01-06 20:49 UTC, hang-up commented
Hey @mjhenkes!
Thanks for the feedback. I've updated my array of test files/folders to the following:

```
.
├── cypress
│   ├── integration
│       └── _fixtures
│           └── fixture-should-match.spec.js        -> should match
│       └── _unit
│           └── unit-should-match.spec.js           -> should match     
│       └── login
│           └── login.spec.js                       -> should match
│       └── sub-level-1
│           └── should-not-match-level-1.spec.js                   
│         └── sub-level-2
│             └── should-not-match-level-2.spec.js                 
│       └── fixture-should-not-match.spec.js
```

And running a mixture of 2 specs + 1 glob pattern:
```
yarn cypress:run -- --spec='cypress/integration/login/login.spec.js,cypress/integration/_unit/unit-should-match.spec.js,cypress/integration/_fixtures/**/*.spec.js'
```
seems to pick up the right specs to run.

![image](https://user-images.githubusercontent.com/8967158/148449763-a6dea7e7-c4d0-4843-b157-a0cd6686d981.png)

2022-01-07 20:55 UTC, mjhenkes commented
I dug into the code some more, The issue will arise when there is a square or curly bracket in t regular expression. If found the whole `--spec` string will be treated as a single glob.

I believe the following string will fail for you (I have a different folder setup for my test repo so i can't be sure 😄 )
```
yarn cypress:run -- --spec='cypress/integration/login/login.spec.js,cypress/integration/_unit/unit-should-match.spec.js,cypress/integration/**/{login,fixture-should-match}.spec.js'
```

2022-01-08 19:46 UTC, hang-up commented
You're right! 

I've narrowed it down to these 8 possible scenarios (to make sure I'm not missing anything):
```js
const patterns = {
  0: "cypress/integration/glob/**/*",
  1: "cypress/integration/spec1.spec.js",
  2: "cypress/integration/spec1.spec.js,cypress/integration/spec2.spec.js",
  3: "cypress/integration/spec1.spec.js,cypress/integration/spec2.js,cypress/integration/glob/**/*",  
  4: "{[!fix]*.spec.js,!(_unit)/**/[!fix]*.spec.js}",
  5: "cypress/integration/{[!fix]*.spec.js,!(_unit)/**/[!fix]*.spec.js},cypress/integration/spec1.spec.js",
  6: "cypress/{static,build/public,{src,src/increment}}/*.js",
  7: "cypress/integration/{[!fix]*.spec.js,!(_unit)/**/[!fix]*.spec.js},cypress/integration/spec1.spec.js,cypress/integration/{[!fix]*.specs.js,!(_unit)/**/[!fix]*.specs.js}"
};
```
I'll do a rewrite of the split logic to accommodate them :)

2022-01-12 14:10 UTC, mjhenkes commented on packages/server/lib/util/args.js
> +const parseSpecArgv = (pattern) => {
Could you document this function like you have the inner functions?

2022-01-12 14:13 UTC, mjhenkes commented
@hang-up your spec test cases look pretty good, I don't think i have anything to add.

2022-01-12 23:06 UTC, hang-up commented on packages/server/lib/util/args.js
> +   * Sanitizes a path from leftover commas.
Done!

2022-01-13 15:04 UTC, mjhenkes submitted a review, later dismissed

2022-01-14 14:44 UTC, davidmunechika approved these changes

2022-01-14 20:29 UTC, mjhenkes commented on packages/server/lib/util/args.js
> +   * Slice & mutate a string.
```suggestion
   * Slice and mutate a string.
```

2022-01-18 16:08 UTC, mjhenkes approved these changes

2022-01-18 16:16 UTC, davidmunechika approved these changes
lgtm

2022-01-18 17:10 UTC, merged