test(unify): Specs Page Workflows
cypress-io/cypress pull request #19659
Opened 2022-01-11 17:07 UTC by tbiethman

- Closes #19207 

### User facing changelog

N/A

### Additional details

The following reqs are accounted for here:

New Project - Specs Page (component)
* When there are no specs detected (and user has not overridden `defaultSpecPattern`), the page has selections for 'Create from story' and 'Create from component'
* When there are no specs detected, there's a button to 'View spec pattern'
* Clicking the 'View spec pattern' button will redirect you to the Settings page
* Clicking 'Create from story' will open a 'Choose a story' modal
* Clicking 'Create from component' will open a 'Choose a component' modal

New Project - Specs Page - Choose a Story (component)
* The modal can be closed by clicking an 'x' button and take you back to specs empty page
* The 'modal has a default file extension filter of *.stories
* The modal has a file extension button that can be clicked to type in the file extension. This will filter the results by file extension found
* The number of files matching from the search will display in the searchbar
* Clicking on a matching story will route you to a 'Spec successfully added' modal

New Project - Specs Page - Choose a component (component)
* The modal can be closed by clicking an 'x' button and take you back to specs empty page
* There's a default file extension filter of *.(component testing framework)
* There's a file extension button that can be clicked to type in the file extension. This will filter the results by file extension found
* The number of files matching from the search will display in the searchbar
* Hovering over a matching file will display its relative path
  * TODO - needs UI enhancement to make file list items keyboard accessible
* Clicking on a matching story will route you to a 'Spec successfully added' modal

New Project - Specs Page - Spec Successfully Added (component)
* The 'Spec successfully added' modal will display the spec's relative path that was added in green
* The new specfile has been created in your file system
* Clicking the spec's relative path will expand to display a preview of the specfile's contents
* Clicking 'x' to close the modal will display the Specs list page with the current spec
* Clicking 'create another spec' will display the 'Create from story' and 'Create from component' options within the modal
* Clicking 'Okay, run the spec' button will open the spec in the Test Runner

### How has the user experience changed?

### PR Tasks

- [X] Have tests been added/updated?
- [X] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [n/a] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-01-11 17:09 UTC, tbiethman commented on packages/frontend-shared/src/components/Card.vue
> +    :tabindex="disabled ? -1 : 0"
The tabindex of 1 pulled the cards out of the natural tab order. Talked with @marktnoonan, the cards are going to get a larger markup change in the future.

2022-01-11 17:11 UTC, tbiethman commented on packages/frontend-shared/src/components/StandardModalHeader.vue
> +    <div>
Adding an additional container here to remove the 'Need help?' link from the dialog's label while keeping the desired styling. Prior to this change, the dialog would read as "Choose a spec Need help?"; now it's just "Choose a spec".

2022-01-11 17:18 UTC, tbiethman commented on packages/app/cypress/e2e/specs_page.cy.ts
> +  describe('Code Generation', () => {
Full credit to @ZachJW34 for writing the Code Generation tests, I moved them into into this file to co-locate them with the rest of the specs page tests.

2022-01-13 15:11 UTC, marktnoonan requested changes
Looks good! Just a couple of suggestions in the tests. 

And then, not for this PR, but: these tests also makes me think we could refactor our tabindex checks into a custom chai assertion so that we could use `be.focusable` and `not.be.focusable`, it would be good to talk about that . There's a [recipe](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/extending-cypress__chai-assertions/cypress/support/index.js) that looks pretty straightforward.

2022-01-13 16:00 UTC, tbiethman commented
> And then, not for this PR, but: these tests also makes me think we could refactor our tabindex checks into a custom chai assertion so that we could use be.focusable and not.be.focusable, it would be good to talk about that . There's a recipe that looks pretty straightforward.

That's a good point. Even a custom cy command to call `focus` on an element and assert that is it actually focused afterwards might be helpful, if a little more intrusive to the AUT. Ideally, we wouldn't be explicitly checking tabindex at all and relying on 'disabled' attributes where possible; the Card refactor will help a lot there.

2022-01-13 19:48 UTC, emilyrohrbough commented on packages/app/cypress/e2e/specs_page.cy.ts
> +        cy.findByTestId('create-spec-page-description').should('be.visible').and('contain', defaultMessages.createSpec.page.defaultPatternNoSpecs.component.description)
```suggestion
        cy.findByTestId('create-spec-page-description')
        .should('be.visible')
        .and('contain', defaultMessages.createSpec.page.defaultPatternNoSpecs.component.description)
```

2022-01-13 19:48 UTC, emilyrohrbough commented on packages/app/cypress/e2e/specs_page.cy.ts
> +        cy.findByTestId('no-specs-message').should('be.visible').and('contain', defaultMessages.createSpec.noSpecsMessage)
```suggestion
        cy.findByTestId('no-specs-message')
        .should('be.visible')
        .and('contain', defaultMessages.createSpec.noSpecsMessage)
```

2022-01-13 20:10 UTC, marktnoonan approved these changes, later dismissed

2022-01-13 20:28 UTC, emilyrohrbough commented on packages/app/cypress/e2e/specs_page.cy.ts
> +    context('with storybook', () => {
```suggestion
    context('create spec with storybook', () => {
```

2022-01-13 20:33 UTC, emilyrohrbough commented on packages/app/cypress/e2e/specs_page.cy.ts
> +    context('with storybook', () => {
maybe
`project with storybook`

2022-01-13 20:34 UTC, emilyrohrbough commented on packages/app/cypress/e2e/specs_page.cy.ts
> +    context('without storybook', () => {
```suggestion
    context('project without storybook', () => {
```

2022-01-13 20:35 UTC, emilyrohrbough commented on packages/app/cypress/e2e/specs_page.cy.ts
> +      context('create from story', () => {
Would it be worth throwing a test in to verify that clicking create from component correctly finds matches?

It does look like the stories are matched as well which makes it seem like we won't even need the create from story option...
<img width="647" alt="Screen Shot 2022-01-13 at 2 35 32 PM" src="https://user-images.githubusercontent.com/14099737/149405233-5e2eb9a1-eacb-4e30-868c-dc52a8affaf1.png">

2022-01-13 20:38 UTC, emilyrohrbough commented on packages/app/cypress/e2e/specs_page.cy.ts
> +
It'd be worth beefing this up to test for:
- generating spec from component/story multiple times --  naming and code generation
- cannot generate spec from a spec
- generating a spec from a story when the `create from component` route is used

2022-01-13 20:39 UTC, emilyrohrbough commented on packages/app/cypress/e2e/top-nav.cy.ts
> +        cy.findByRole('dialog', { name: 'Upgrade to Cypress 10.1.0' }).as('upgradeModal').within(() => {
are 10.0.0 and 10.1.0 hard coded?

2022-01-13 20:40 UTC, emilyrohrbough approved these changes, later dismissed
Nice job. Overall it seems like this is pretty much there. My bigger questions are around the implementation, not the tests themselves.

2022-01-13 22:51 UTC, emilyrohrbough commented on packages/app/cypress/e2e/top-nav.cy.ts
> +        cy.findByRole('dialog', { name: 'Upgrade to Cypress 10.1.0' }).as('upgradeModal').within(() => {
ahh I should have expanded these further to view the full spec

2022-01-20 05:57 UTC, tbiethman commented
A lot has changed since I've been pulled away from these. Going to close this in favor of a new PR: https://github.com/cypress-io/cypress/pull/19780

2022-01-20 05:57 UTC, closed without merging