feat: Focus browser from select browser screen and on dashboard login
cypress-io/cypress pull request #19842
Opened 2022-01-24 13:54 UTC by ryanthemanuel

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-01-24 15:51 UTC, ZachJW34 submitted a review, later dismissed
Tested, looks good. #19781 was recently merged that fixed the Electron browser launching which will be good to test against.

2022-01-26 15:10 UTC, brian-mann commented
Since we're not supporting focus in linux + firefox, but support every other combination... we probably need to update the graphql for the frontend to "know" whether to render the `Focus Browser` button ahead of time.

2022-01-26 15:10 UTC, brian-mann requested changes
Need to update the graphql schema indicating whether the browser is focusable so the frontend knows to render or not render the `Focus Browser` button

2022-01-26 15:30 UTC, ZachJW34 commented on packages/launchpad/src/setup/OpenBrowserList.vue
> +gql`
Unused, as the `Close` button emits an event to the parent in order to execute the mutation.

2022-01-26 15:30 UTC, ZachJW34 commented on packages/launchpad/src/setup/OpenBrowserList.vue
> +const closeBrowserMutation = useMutation(OpenBrowserList_CloseBrowserDocument)
Unused.

2022-01-26 15:30 UTC, ZachJW34 commented on packages/launchpad/src/setup/OpenBrowserList.vue
> +const focusActiveBrowserWindow = useMutation(OpenBrowser_FocusActiveBrowserWindowDocument)
We have two different ways of calling the mutation. Your method calls the mutation in this component, the other emits an event to the parent component to execute the mutation. I'm normally fine with either, but we already emitting for both the launchProject and closeBrowser so let's go with that method. There is also a `TODO` in the `emits` of this component that we can remove for browser focus with this suggested change.

2022-01-26 20:42 UTC, brian-mann commented on packages/server/lib/gui/auth.ts
> +    onLogin()
yay i'm glad you updated this

2022-01-26 21:30 UTC, ZachJW34 approved these changes
Looks great! LGTM!!

2022-01-27 18:02 UTC, ZachJW34 approved these changes

2022-01-27 18:04 UTC, merged