fix: set correct config file on migration
cypress-io/cypress pull request #19990
Opened 2022-01-31 21:38 UTC by estrada9166

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-01-31 22:54 UTC, elevatebart approved these changes

2022-02-01 00:46 UTC, ImCesar requested changes

2022-02-01 00:46 UTC, ImCesar commented on packages/launchpad/cypress/e2e/migration.cy.ts
> +    migrateAndVerifyConfig('ts')
This test is currently failing as it's still creating a JS file

2022-02-01 02:22 UTC, lmiller1990 approved these changes

2022-02-01 02:23 UTC, merged