feat: CLI `config` not supporting nested properties correctly
cypress-io/cypress pull request #20127
Opened 2022-02-09 20:42 UTC by BlueWinds

- Closes UNIFY-1028

### User facing changelog
Can now pass in testing-type specific config options via `--config` without nesting JSON. 

### Additional details
With the addition of more testing type specific config options, and especially with the requirement that `specPattern` be configured per testing type, using `--config` via command line was a bit clunky, requiring a user to nest the config value, eg.

```
--config={"e2e":{"specPattern":["*/test2.coffee","*/test1.js"]}}
```

Unlike 9.x, where it was relatively simpler:
```
--config specPattern="*/test2.coffee,*/test1.js"
or
--config={"specPattern":["*/test2.coffee","*/test1.js"]}
```

This restores the previous behavior. If a user passes in a config value that's invalid at the top level, we attempt to interpret it as a testing-type specific config. So specPattern continues to work from the command line as it did in 9.x, even though in config files it must now be nested.

### How has the user experience changed?
Restores 9.x behavior to 10.0-release.

### PR Tasks
- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-02-10 19:28 UTC, BlueWinds commented
A number of tests are failing here on this branch, but I'm seeing the same failures in 10.0-release, and even develop when running locally - it feels like something changed with regards to cookies recently, perhaps a browser version upgrade?

Going to put this as ready for review while I look into it, since I suspect the solution is unrelated to the changes in here.

2022-02-10 20:24 UTC, emilyrohrbough commented
Without looking at the changes, could I run something like:
```
--e2e --config= "specPattern":["*/test2.coffee","*/test1.js"]}
```

2022-02-17 01:40 UTC, lmiller1990 approved these changes
One question. Also, rebased it, so we should be good to get another :heavy_check_mark: and merge.

2022-02-17 01:40 UTC, lmiller1990 commented on packages/server/test/unit/util/args_spec.js
> +    it('moves testing-type specific config options', function () {
Cool, looks good. Do we have a pre-existing pattern for if they pass invalid config, eg `--config={blablah=false}`, or we just ignore these? It looks like we will inherit the same behavior with the hoisted keys, just wanted to clarify.

2022-02-17 17:07 UTC, cowboy commented
> I want to clarify: we use JSON for `--config`, but the actual config is no longer JSON, but a JS module. Do you know if this has been discussed (stick w/ JSON on config, even if we are not using JSON for the `cypress.config.js`. What about if they try to pass a key that's a function, like `devServer`? I wonder if we should error.
> 
> I'm guessing this is something @cypress-io/dx has considered previously when thinking about `cypress.config.js`?

We did discuss the `--config` option, and what I remember from that conversation (I couldn't find any documentation) was that all options specified via `--config` override the _resolved_ config value, so that the user never needs to specify the `e2e` or ` component` objects. It was my understanding that this is the 9.x behavior, and we were going to keep it in 10.0.

Also, I believe we decided that function options would _not_ be able to be specified via `--config`.

Does this make sense? Are there any issues with this?

2022-02-17 17:13 UTC, cowboy commented
> ```
> --e2e --config='{"specPattern":["*/test2.coffee","*/test1.js"]}'
> ```

Not sure if this is relevant, but Windows cmd shell only understands `"` as a string delimiter, in case we're testing this there.

2022-02-17 17:46 UTC, BlueWinds commented
> We did discuss the --config option, and what I remember from that conversation (I couldn't find any documentation) was that all options specified via --config override the resolved config value, so that the user never needs to specify the e2e or component objects. It was my understanding that this is the 9.x behavior, and we were going to keep it in 10.0.

> Also, I believe we decided that function options would not be able to be specified via --config.

> Does this make sense? Are there any issues with this?

Makes sense to me, and matches what was implemented in the PR, thanks for explaining. Just wanted to double check to make sure this was desired and intended.

> > ```
> > --e2e --config='{"specPattern":["*/test2.coffee","*/test1.js"]}'
> > ```
> 
> Not sure if this is relevant, but Windows cmd shell only understands `"` as a string delimiter, in case we're testing this there.

No tests / docs using single quotes, provided here only as an example for discussion in the PR.

2022-02-18 00:04 UTC, lmiller1990 approved these changes
thanks for clarification @cowboy, seems we are all good.

2022-02-20 21:28 UTC, brian-mann requested changes
This was something we discussed during the design of the CLI changes as per 10.0

In fact there is not supposed to be support for passing nested `--config` values for e2e + component. They are supposed to be passed **flattened** for the testing type that you want applied.

So passing `--config specPattern='...'` is only applied **to the testing type you eventually go into** and is applied to both testing types. You don't pass different configuration to different testing types.

It this is something we'd like to revisit I'm all ears - but it was intentionally designed this way. It's possible the existing implementation was not working correctly, but the aforementioned behavior was the desired behavior.

### Edit
Sorry I just reread the comments throughout this PR and clearly others have chimed in with the same information. @BlueWinds what's not clear from this PR is what specific behavior this is fixing. When I first read this I saw the PR description regarding the `config` not supporting nesting and assumed it was attempting to pass specific testing type config. What I'm looking for clarity on is what specific **existing** behavior is and what this PR is changing to the **desired** behavior. A simple before/after.

2022-02-21 00:14 UTC, lmiller1990 commented
I just tested this out and as @brian-mann points out, the flat/merging stuff actually already works as-expected in `10.0-release`. Maybe this does not actually fix anything?

2022-02-21 15:55 UTC, BlueWinds commented
> Sorry I just reread the comments throughout this PR and clearly others have chimed in with the same information. @BlueWinds what's not clear from this PR is what specific behavior this is fixing. When I first read this I saw the PR description regarding the `config` not supporting nesting and assumed it was attempting to pass specific testing type config. What I'm looking for clarity on is what specific **existing** behavior is and what this PR is changing to the **desired** behavior. A simple before/after.

Latchaln put this fairly clearly, so I'll refer you to his comment for a before / after.

Currently in 10.0, *most* config values already work as you describe, getting included in whichever config type the user selects. The only ones that don't are those explicitly not available as root config values - eg, those in [breakingRootOptions](https://github.com/cypress-io/cypress/blob/issue-UNIFY-1028-cli-nested-config/packages/config/lib/options.ts#L532): `supportFile`, `specPattern`, `excludeSpecPattern` and `baseUrl`. These are not valid as 'root' config options, and so the CLI rejects them.

This PR aims to allow those breakingRootOptions to be applied to the appropriate testing type when passed in via --config. I'll update the PR description once I address @lmiller1990's findings above.

2022-02-21 16:17 UTC, BlueWinds commented
> I tested this branch a bit more. This one isn't working for me unless I explicitly include `--e2e` or `--component`. I'm not sure if that's related, and it only seems to be for nested only config options (like `specPattern`).

It was checking to see what testing type the user had actually passed in, which, upon reflection, is not the correct action - we *know* what testingType `baseUrl` applies to. I've updated the PR so that it nests invalid root configs directly to the testing types they apply to - it will also now work in open mode when you switch between testing types, applying CLI args to the appropriate one.

2022-02-21 17:05 UTC, BlueWinds commented
Updated PR with clear before / after examples.

2022-02-21 23:57 UTC, lmiller1990 approved these changes
Cool, seems good to me.

2022-02-24 16:22 UTC, flotwig commented
Seems like a legit failure in server-unit-tests: https://app.circleci.com/pipelines/github/cypress-io/cypress/32422/workflows/962760ee-0761-4d37-b915-8babc3bf8e5d/jobs/1284475

2022-02-24 23:02 UTC, BlueWinds commented
> Seems like a legit failure in server-unit-tests: https://app.circleci.com/pipelines/github/cypress-io/cypress/32422/workflows/962760ee-0761-4d37-b915-8babc3bf8e5d/jobs/1284475

Fixed.

2022-02-25 02:24 UTC, merged