fix: treat form-data bodies as binary
cypress-io/cypress pull request #20144
Opened 2022-02-10 12:54 UTC by mlauinger

- Closes https://github.com/cypress-io/cypress/issues/20143

### User facing changelog
Http-Requests with content-type `multipart/form-data` will no longer stringified when they are intercepted

### Additional details
This change is necessary to guarantee that form-data requests which contain a binary file and a certain amount of plain text will not be serialized when they are intercepted. The serialization breaks binary files (like PDFs).

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-02-10 14:00 UTC, jennifer-shehane requested changes
@mlauinger Can you please describe the issue this is solving in the PR description. Can you also sign our CLA? These are required to merge.

2022-02-14 17:39 UTC, BlueWinds approved these changes
This change looks correct to me. Even though `"binary"` encoding in nodejs is an alias for `"latin1"`, and we're trying to move away from it and towards using `null` as an encoding to refer to binary files, here the `"binary"` string is being used as a flag ("should we call `.toString()` on this") rather than as an encoding for the buffer.

2022-02-17 18:20 UTC, merged

2022-08-16 14:55 UTC, JoshAGordon commented
We are currently awaiting for this to be fixed in one of my projects, is there any update as to when it is expected to be fixed?

2022-08-16 15:42 UTC, BlueWinds commented
No update, and not currently in our planned work; If you'd like to take a stab using this PR as a basis and fix the issues that caused a revert (see discussion in https://github.com/cypress-io/cypress/pull/20343), we'd welcome the contribution.