fix: connect to dashboard page when there are no existing projects
cypress-io/cypress pull request #20188
Opened 2022-02-14 21:36 UTC by ryanthemanuel

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-02-15 17:40 UTC, elevatebart submitted a review, later dismissed

2022-02-16 21:51 UTC, tbiethman approved these changes

2022-02-17 18:52 UTC, tbiethman commented on packages/app/src/runs/modals/SelectCloudProjectModal.vue
> +            v-if="projects.length > 0"
Is this check ever falsy? If the length is 0, it doesn't look like this branch of markup would be generated.

2022-02-17 21:17 UTC, tbiethman commented on packages/app/src/runs/modals/SelectCloudProjectModal.vue
> +            v-if="projects.length > 0"
Do'h, Ryan filled me in. newProject is a `ref` and not `computed`, so this all works as expected.

2022-02-17 21:34 UTC, tbiethman submitted a review, later dismissed

2022-02-18 15:59 UTC, elevatebart requested changes

2022-02-18 15:59 UTC, elevatebart commented on packages/app/src/runs/modals/SelectCloudProjectModal.cy.tsx
> +  it('can only create new projects if the organization has no projects', () => {
```suggestion
  it('can only choose an existing project if the organization has a project', () => {
```

2022-02-18 15:59 UTC, elevatebart commented
One heavy suggestion...

2022-02-18 16:08 UTC, elevatebart approved these changes

2022-02-18 17:30 UTC, merged