no longer check if dev to show devtools
cypress-io/cypress pull request #20298
Opened 2022-02-21 20:18 UTC by marktnoonan

- Closes [UNIFY-1189](https://cypress-io.atlassian.net/browse/UNIFY-1189)

### Additional details

This is a pretty minimal set of changes. We could actually do away with the whole `withDevTools` option in `menu.set` and tests related to it, since we no longer have any case where we would set this to not be true.

### How has the user experience changed?

Before (no devtools in production mode): 
![Screen Shot 2022-02-21 at 3 13 02 PM](https://user-images.githubusercontent.com/8340719/155020752-34499fbf-040b-4f27-9039-693b406e2d0a.png)

After (devtools for all):
![Screen Shot 2022-02-21 at 3 10 16 PM](https://user-images.githubusercontent.com/8340719/155020644-731c085f-b7e5-4f0d-b0c6-433e5990af86.png)

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-02-22 02:08 UTC, ryanthemanuel submitted a review, later dismissed

2022-02-22 02:35 UTC, brian-mann requested changes
I don't think we want to always enable `graphiql` and options like forcing gql requests over fetch to be in the `Developer Tools` menu. Those are strictly internal only.

I would recommend you add back in `withDevTools` and maybe rename it to `withInternalDevTools` and exclude those 2 options.

2022-02-22 17:23 UTC, marktnoonan commented
@brian-mann this is updated now to remove the 2 graph ql items in production.

2022-02-22 20:09 UTC, ryanthemanuel approved these changes

2022-02-23 16:22 UTC, brian-mann approved these changes

2022-02-23 16:23 UTC, merged