fix: UNIFY-676 browsers should be configurable in setupNodeEvents
cypress-io/cypress pull request #20367
Opened 2022-02-25 17:27 UTC by tgriesser

- Closes UNIFY-676

Adds a system test to show that filtering browsers is working properly

2022-02-25 19:12 UTC, tbiethman commented
We just need to interpolate the majorVersion now: https://github.com/cypress-io/cypress/blob/a015397f577313b9ae09c86fbeea11cc067ed724/packages/server/lib/browsers/chrome.ts#L407

2022-02-25 19:31 UTC, tgriesser commented
I had updated the type because it seemed to be wrong but who knows, the types in the server layer are pretty tough to follow. Didn't need to address it as part of this PR.

2022-02-25 20:26 UTC, tbiethman submitted a review, later dismissed

2022-02-25 21:26 UTC, elevatebart submitted a review, later dismissed

2022-02-25 21:48 UTC, JessicaSachs reviewed
Doesn't work, Tim and I DM'd about it already.

2022-02-25 21:48 UTC, JessicaSachs requested changes
Doesn't work, Tim and I DM'd about it already.

![image](https://user-images.githubusercontent.com/2801156/155807724-f7c9dc3b-2bf4-43b1-955d-511f072094f7.png)

2022-02-25 22:19 UTC, elevatebart requested changes
Would this mean that now `config.browser` is available in the types of `setupNodeEvents()`?

The value will always be null and setting it should have no effect. 

How far off am I ?

2022-02-28 07:10 UTC, lmiller1990 commented
Seems fine to me, I followed https://docs.cypress.io/guides/guides/launching-browsers#Customize-available-browsers and got this:
 
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/19196536/155939576-b01646ef-1826-4e63-b8bb-22343cb91fd7.png">

2022-02-28 08:19 UTC, lmiller1990 submitted a review, later dismissed

2022-02-28 08:24 UTC, lmiller1990 commented
Alrighty I got this green, let's get one more test/approval. The types are working fine for me, too, from what I can see. I had to specify `headless` and `isHeaded` which seems weird, but fixing the types in the entirely of Cypress is a huge task.

2022-02-28 12:25 UTC, tgriesser commented on cli/types/tests/plugins-config.ts
> +  config.browsers // $ExpectType: false
@lmiller1990 this is what I was most recently looking into. This was set as a failing test but it doesn't seem to be triggered. Looking to see where we regressed in terms of running the test on these

2022-02-28 12:27 UTC, tgriesser commented
@lmiller1990 I'm not sure why all of these changes were even needed. I wasn't sure if the types were correct

2022-02-28 12:46 UTC, tgriesser commented
Changing to draft to investigate why the `$ExpectTypre` types aren't being checked

2022-02-28 20:42 UTC, tgriesser commented
@elevatebart:

> Would this mean that now config.browser is available in the types of setupNodeEvents()?

Nah, it's using a `Partial` so it'll be `Browser | undefined`

2022-03-01 02:22 UTC, lmiller1990 approved these changes
Seems fine to me! I tried it as mentioned in a previous review and it worked okay, including types.

2022-03-01 06:06 UTC, elevatebart approved these changes
@tgriesser I beg to disagree, the problem is still here:
The code below seems to be valid typed configFile. 

```ts
import { defineConfig } from 'cypress'

export default defineConfig({
  e2e: {
    setupNodeEvents (on, config) {
      config.browser = 'chrome'
    },
  },
})
```

What I am saying is that the types are not correct since they contain more than the actual object. Instead of helping the types we have here could confuse users. 
I prefer that we do not fix it in this PR though.

2022-03-01 07:52 UTC, lmiller1990 commented
@elevatebart what's an example of a property on config that's not actually there? I think since it's a `Partial` everything is going to be nullable, which seems fine - users will basically need to assume any of the properties they are accessing are nullable and do the required defensive checks.

2022-03-01 07:54 UTC, merged