Fix invalid type on Cypress.Buffer
cypress-io/cypress pull request #20553
Opened 2022-03-10 02:57 UTC by dantman

BufferType refers to an instance of Buffer instead of the Buffer type itself. As a result `Cypress.Buffer.from('asdf')` is considered invalid code.

To get the Buffer class itself rather than the type for an instance of the class, you need to use the typeof keyword.

Fixes #20542

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-03-10 03:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=20553) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=20553) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=20553) it.</sub>

2022-03-10 17:08 UTC, emilyrohrbough submitted a review, later dismissed

2022-03-10 17:09 UTC, emilyrohrbough commented
@dantman can you sign the CLA?

2022-03-10 17:10 UTC, BlueWinds approved these changes

2022-03-10 19:31 UTC, jennifer-shehane requested changes
@dantman Can we have a test to cover this change? Our Types tests exist within the `cli/tests` folder.

2022-03-22 15:41 UTC, jennifer-shehane commented
@dantman Can you sign our CLA? We can't merge in this work or continue the work on our own without this being signed.

2022-03-22 21:35 UTC, BlueWinds approved these changes

2022-03-23 14:36 UTC, merged