feat: issue-3387
cypress-io/cypress pull request #20800
Opened 2022-03-28 14:27 UTC by ladvish

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-03-28 14:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=20800) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=20800) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=20800) it.</sub>

2022-03-28 14:35 UTC, jennifer-shehane requested changes
@ladvish Thanks for the contribution. You'll need to sign our CLA before we can merge this in. Additionally, please fill our the PR template with the information on the change as well as writing a test to ensure the intended behavior is tested.

2022-03-28 14:39 UTC, ladvish commented
Hello Folks!

Please move this PR in draft stage since its not ready for review.

Just picked up my first issue to explore more about cypress.

I somehow figured out the file to be modified - cypress/packages/driver/src/cy/commands/request.ts

I ended up with this error - 
Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

cy.request()

The cy command you invoked inside the promise was:
cy.fixture()


Any suggestions where i should be looking at to fix this?

2022-05-23 19:33 UTC, jennifer-shehane commented
@ladvish Unfortunately we have to close this PR due to inactivity. Please open a new PR addressing the original issue and any requested changes.

2022-05-23 19:33 UTC, closed without merging