fix(desktop-gui): use native file picker on non-GTK desktop environments
cypress-io/cypress pull request #20852
Opened 2022-03-30 20:23 UTC by flotwig

- Closes 

### User facing changelog

- Fixed an issue on Linux where the GTK file picker would be used in non-GTK desktop environments.

### Additional details

- See https://tristan.partin.io/blog/2021/04/01/electron-linux-and-your-file-chooser/ for the reasoning and below for screenshots

### How has the user experience changed?

#### Before (on KDE)

![image](https://user-images.githubusercontent.com/1151760/160923968-9dd6be87-3101-493a-9883-f95594339525.png)

#### After (on KDE)

![image](https://user-images.githubusercontent.com/1151760/160923865-347cd38c-5ba5-43f5-ae58-f73b850bc0c3.png)

#### After (on GNOME, or when a `xdg-desktop-portal` package is not present

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-03-31 15:50 UTC, emilyrohrbough commented on cli/lib/exec/spawn.js
> -      env: process.env,
why remove the default here?

2022-03-31 15:57 UTC, emilyrohrbough commented on cli/lib/exec/open.js
> +      return { GTK_USE_PORTAL: '1' }
Just curious, is this something that could be validated and set in `packages/electron` instead of needing to setup & pass this ENV around?

2022-03-31 15:57 UTC, emilyrohrbough commented on cli/lib/exec/open.js
> +    function getOpenModeEnv () {
nit: feels like this name should be something about `getNativeFilePickerEnvs`

2022-04-04 22:09 UTC, BlueWinds commented
Hm. Possibly because I don't have the appropriate gtk modules installed, I'm seeing your "After" filepicker across all branches and versions - it doesn't seem to make any difference to me. Which goes to show, I suppose, that it's at the very least a harmless change.

2022-04-04 22:15 UTC, BlueWinds requested changes

2022-04-04 22:15 UTC, BlueWinds commented on cli/__snapshots__/verify_spec.js
> +
This newline seems to be causing the unit tests to fail in CI.

2022-04-04 22:16 UTC, BlueWinds approved these changes

2022-06-16 20:20 UTC, BlueWinds commented
@flotwig - I believe we discussed this in slack, and you decided the issue was a relic of your setup. Still planning on coming back to this PR?

2022-06-21 21:14 UTC, flotwig commented
@BlueWinds I'll close this for now, if I see it again I'll reopen.

2022-06-21 21:14 UTC, closed without merging