feat: implement log group API and update log group styles
cypress-io/cypress pull request #20886
Opened 2022-04-01 16:40 UTC by emilyrohrbough

- Apart of #18822 

<img width="684" alt="Screen Shot 2022-04-01 at 11 34 27 AM" src="https://user-images.githubusercontent.com/14099737/161305504-38e16f83-2daa-42fe-9066-cf7372566a73.png">
<img width="667" alt="Screen Shot 2022-04-01 at 11 35 05 AM" src="https://user-images.githubusercontent.com/14099737/161305506-badde2e8-387e-4c0d-8a46-7837333c7bc6.png">

2022-04-04 22:15 UTC, tbiethman submitted a review, later dismissed

2022-04-04 22:19 UTC, davidmunechika submitted a review, later dismissed
lgtm

2022-04-04 23:17 UTC, tgriesser commented on packages/driver/src/cypress.ts
> +        // Cypress logs will only trigger an update every 4 seconds so there is a
```suggestion
        // Cypress logs will only trigger an update every 4 milliseconds so there is a
```

2022-04-04 23:32 UTC, tgriesser commented
Was looking into this to understand a bit better, and I think this flake actually might actually be due to a legitimate regression in the `chore: refactor log function to class` merge here: https://github.com/cypress-io/cypress/pull/20382 

Specifically the fact that the original behavior seemed to create a single debounced `fireChangeEvent` per Log class.

https://github.com/cypress-io/cypress/blob/047aefc4ba0b2eeb60b869e8ac2fab1322034fa8/packages/driver/src/cypress/log.ts#L552-L556

whereas the new behavior:

https://github.com/sainthkh/cypress/blob/ce95894a35bedbee51920ae7073ee48a241195a4/packages/driver/src/cypress/log.ts#L556-L566

appears to create a new debounced fn, which is immediately invoked, per event fired. Might be missing something non-obvious since there's quite a few `fn` binds, etc. going on here, but that's just how it appears at first glance.

/cc @sainthkh

2022-04-04 23:32 UTC, tgriesser requested changes

2022-04-04 23:32 UTC, tgriesser commented on packages/runner-shared/src/event-manager.js
> +      // Cypress logs will only trigger an update every 4 seconds so there is a
```suggestion
      // Cypress logs will only trigger an update every 4 milliseconds so there is a
```

2022-04-05 01:36 UTC, brian-mann commented
Yes this is the problem per @tgriesser comment:

https://github.com/cypress-io/cypress/pull/20886#issuecomment-1088120615

The debounce cannot be on each log instance - it needs to be a singleton and all log calls need to go through that function.

2022-04-05 06:24 UTC, sainthkh commented
I admit that I refactored it wrong way. I didn't read the `_.debounce()` carefully. [It says that](https://lodash.com/docs/4.17.15#debounce):

```
Subsequent calls to the debounced function return the result of the last func invocation.
```

I guess creating debounce function every call changed the behavior. 

----

As `fireChangeEvent` is an internal function only used inside `log.ts` file. I think it's OK to give it `any` type. 

As I don't have the authority to push commits to this PR. I left my code suggestion at #20908.

2022-04-05 16:30 UTC, tgriesser approved these changes

2022-04-05 16:35 UTC, davidmunechika approved these changes

2022-04-05 20:45 UTC, merged