fix: scaffold examples with correct ext based if project has TS
cypress-io/cypress pull request #21070
Opened 2022-04-13 17:42 UTC by estrada9166

- Closes  [UNIFY-1451](https://cypress-io.atlassian.net/browse/UNIFY-1451)

### User facing changelog

### Additional details

Scaffold the examples using the correct extension, checking if the project has TS, use `.ts` extension to be consistent with the project

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-04-14 05:18 UTC, lmiller1990 approved these changes

2022-04-14 16:40 UTC, flotwig requested changes
I feel like this change needs a little bit more thought than just renaming `.js` to `.ts`. `cypress-example-kitchensink` isn't written with types in mind nor is it typechecked at all, and this PR does not add typechecking for the converted files... so it's going to be really easy for us to accidentally be generating broken `.ts` without knowing it.

I think to fix this, there are ~~two~~ three options:

1. Convert `cypress-example-kitchensink` to typescript and build a JS version from that
	* This might not be possible to do without TS injecting boilerplate, which would make this a non-starter
2. Convert `cypress-example-kitchensink` to typescript, and update this PR to rename `cy.ts` to `cy.js` (reversed from how it is now)
	* Only problem here is that TS has syntax that is invalid JS, so you'd have to also lint that no TS-specific constructs are used (type annotations, `type` keywords...)
3. Add a test in this PR that typechecks the converted `.ts` files against the `cypress` typedefs.

(3) would probably be easiest. (2) would need to be a bigger decision involving DX I think.

2022-04-18 04:18 UTC, lmiller1990 commented
> I feel like this change needs a little bit more thought than just renaming `.js` to `.ts`. `cypress-example-kitchensink` isn't written with types in mind nor is it typechecked at all, and this PR does not add typechecking for the converted files... so it's going to be really easy for us to accidentally be generating broken `.ts` without knowing it.
> 
> I think to fix this, there are ~two~ three options:
> 
>     1. Convert `cypress-example-kitchensink` to typescript and build a JS version from that
>        
>        * This might not be possible to do without TS injecting boilerplate, which would make this a non-starter
> 
>     2. Convert `cypress-example-kitchensink` to typescript, and update this PR to rename `cy.ts` to `cy.js` (reversed from how it is now)
>        
>        * Only problem here is that TS has syntax that is invalid JS, so you'd have to also lint that no TS-specific constructs are used (type annotations, `type` keywords...)
> 
>     3. Add a test in this PR that typechecks the converted `.ts` files against the `cypress` typedefs.
> 
> 
> (3) would probably be easiest. (2) would need to be a bigger decision involving DX I think.

I agree (1) and (2) probably are not ideal and/or a lot of work for not (that) much value. For (3), we could just throw a `/// <reference types="cypress" />` at the top and run `tsc --noEmit` at the tail end of this test to ensure the generated code is valid.

2022-04-19 14:51 UTC, estrada9166 commented
Closing this one - we can revisit if needed

2022-04-19 14:51 UTC, closed without merging