fix: update not supported plugins errors
cypress-io/cypress pull request #21169
Opened 2022-04-21 22:10 UTC by estrada9166

- Closes  [UNIFY-1524](https://cypress-io.atlassian.net/jira/software/projects/UNIFY/boards/20/backlog?assignee=5ea883deddd45f0b94f5d98d&selectedIssue=UNIFY-1524)

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-04-22 06:35 UTC, lmiller1990 approved these changes
Definitely a big improvement. We still show the original error "glob pattern not found" but I'm guessing this is somewhere deep in driver and not practical to change.

Did we see if any other (official) plugins are broken by 10.x?

2022-04-22 18:25 UTC, chrisbreiding requested changes
I think it would be better if the error message were formatted like:

```
Cypress detected that the current version of @cypress/code-coverage is not supported. Update it to the latest version.

The following error was caught:

> glob pattern string required

Because this error occurred during a after all hook we are skipping all of the remaining tests.
```

2022-04-22 18:25 UTC, chrisbreiding commented on packages/driver/src/cypress/runner.ts
> +      const unsupportedPlugin = runnable.invocationDetails && runnable.invocationDetails.originalFile && runnable.err && runnable.err.message ? $errUtils.getUnsupportedPlugin(runnable.invocationDetai
Maybe pass the `runnable` to `$errUtils.getUnsupportedPlugin` and let it take care of this logic and return null if these properties aren't available?

2022-04-28 00:52 UTC, lmiller1990 commented
Nice @estrada9166, for completion sake (and it it's not too difficult) can you add a screenshot of how the error looks? I think it'll be useful for historical context, if we ever look back, as well as for the final review and :heavy_check_mark:  :pray:

2022-04-28 12:23 UTC, chrisbreiding approved these changes

2022-04-28 12:59 UTC, lmiller1990 commented
Alright got the double ✅ , let's ship it.

2022-04-28 12:59 UTC, merged