fix: issue with generating cypress.config.js in projects with type of module
cypress-io/cypress pull request #21323
Opened 2022-05-03 18:53 UTC by ryanthemanuel

- Closes UNIFY-1669

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-05-03 19:02 UTC, ryanthemanuel commented on packages/data-context/test/.mocharc.js
> +  spec: 'test/unit/**/codegen.spec.ts',
```suggestion
  spec: 'test/unit/**/*.spec.ts',
```

2022-05-04 14:14 UTC, ryanthemanuel commented on packages/config/src/ast-utils/addToCypressConfig.ts
> +  isProjectECMAScript: boolean
Doh good call. I was struggling with what to call this. I like this better

2022-05-04 14:16 UTC, ryanthemanuel commented on packages/config/src/ast-utils/addToCypressConfig.ts
> +  isProjectECMAScript: boolean
Resolved here: [`e02f2b1` (#21323)](https://github.com/cypress-io/cypress/pull/21323/commits/e02f2b103a18d0c3188566d9c135cac3abaf3cf0)

2022-05-04 18:29 UTC, tgriesser approved these changes

2022-05-04 20:41 UTC, flotwig requested changes
Nice, one minor thing

2022-05-04 20:41 UTC, flotwig commented on system-tests/projects/migration-e2e-module/README.md
> +An e2e project with all defaults. We rename the `integrationFolder` and spec extension.
```suggestion
## Migration E2E Module

An e2e project with ES modules. We rename the `integrationFolder` and spec extension.
```

2022-05-04 21:10 UTC, flotwig approved these changes

2022-05-04 21:41 UTC, merged