feat(cypress/schematic): add headed option and other fixes
cypress-io/cypress pull request #21415
Opened 2022-05-09 20:53 UTC by admah

- Fixes #18745 - custom `baseUrl` can be specified via configuration in `angular.json`. More details are in README.md
- Fixes #21332 - `headed` is now a valid option in `run` mode
- updated to add support for Angular 13

2022-05-10 02:34 UTC, lmiller1990 commented
@admah you may need to sign in to CircleCI again, or it won't trigger CI to run.

2022-05-10 02:41 UTC, lmiller1990 reviewed
I see the `headed` fix: https://github.com/cypress-io/cypress/pull/21415/files#diff-4ee798fa6c842712558f99121e5b14db00d1410c489de4bb52597724123be34eR11, but where is the code for "custom baseUrl can be specified via configuration in angular.json. More details are in README.md"? I don't see any changes to this meaning.

2022-05-10 02:41 UTC, lmiller1990 commented on npm/cypress-schematic/sandbox13/README.md
> +This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 12.0.0.
The title of the file (sandbox13) suggests this is angular 13, but the readme says angular 12?

2022-05-10 14:19 UTC, jordanpowell88 requested changes

2022-05-10 23:36 UTC, lmiller1990 approved these changes
Code seems fine from what I can see, just need CI to be ✅

2022-05-11 15:42 UTC, jordanpowell88 approved these changes

2022-05-11 18:16 UTC, merged