chore: fix windows tests in 10.0
cypress-io/cypress pull request #21427
Opened 2022-05-10 16:20 UTC by ryanthemanuel

### User facing changelog

n/a

### Additional details

Additional tests needed fixing in windows:

* The fuzzy spec search does not consistently use the windows separator. This PR ensures that we do.

### How has the user experience changed?

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-05-10 19:53 UTC, ryanthemanuel commented on packages/frontend-shared/src/utils/spec-utils.ts
> +  return window.Cypress?.platform || JSON.parse(decodeBase64Unicode(window.__CYPRESS_CONFIG__.base64Config)).platform
This seems to be necessary since the specs list exists before Cypress necessarily exists

2022-05-10 22:39 UTC, lmiller1990 requested changes
Good fix, we move this entire file (and associated change) to `app`, and use the existing function to decode the __CYPRESS_CONFIG_ (see comment).

2022-05-10 22:39 UTC, lmiller1990 commented on packages/frontend-shared/src/utils/spec-utils.ts
> +const platform = JSON.parse(decodeBase64Unicode(window.__CYPRESS_CONFIG__.base64Config)).platform
I don't think we should use `__CYPRESS_CONFIG__` in `frontend-shared`, it's not available in launchpad - it's `app` specific.

How about exporting this function and using it? https://github.com/cypress-io/cypress/blob/10.0-release/packages/app/src/runner/index.ts#L341-L343

2022-05-10 22:39 UTC, lmiller1990 commented on packages/frontend-shared/src/utils/spec-utils.ts
> +const separator = platform === 'win32' ? '\\' : '/'
Actually this entire file should not be in `frontend-shared`, it's only used in `app`. How about moving it?

2022-05-11 06:36 UTC, lmiller1990 commented on packages/app/src/specs/spec-utils.ts
> +const platform = window.Cypress?.platform ?? getRunnerConfigFromWindow().platform
```suggestion
const platform = getRunnerConfigFromWindow().platform
```

I think - `window.Cypress` won't exist here, only on the runner page, but `__CYPRESS_CONFIG__` is defined from the very moment the app is opened (see here  https://github.com/cypress-io/cypress/blob/10.0-release/packages/data-context/src/sources/HtmlDataSource.ts#L119).

2022-05-11 17:44 UTC, flotwig approved these changes

2022-05-16 19:55 UTC, ZachJW34 approved these changes

2022-05-17 02:13 UTC, lmiller1990 commented
Looks good... once CI is green, let's merge. I'll leave it to you 👍

2022-05-17 02:13 UTC, lmiller1990 approved these changes

2022-05-17 20:01 UTC, AtofStryker approved these changes

2022-05-18 01:16 UTC, merged