chore: deprecate Cypress.Cookies.preserveOnce and Cypress.Cookies.defaults
cypress-io/cypress pull request #21455
Opened 2022-05-12 20:08 UTC by mschile

- Closes #21333 

### User facing changelog

* `Cypress.Cookies.preserveOnce()` and `Cypress.Cookies.defaults()` are deprecated. In a future release, support for
`Cypress.Cookies.preserveOnce()` and `Cypress.Cookies.defaults()` will be removed. Consider using [`cy.session()`](/api/commands/session) instead.

### Additional details

* Marked the `Cypress.Cookies.preserveOnce()` and `Cypress.Cookies.defaults()` APIs as deprecated.

### How has the user experience changed?

<img width="950" alt="Screen Shot 2022-05-12 at 2 04 16 PM" src="https://user-images.githubusercontent.com/2002044/168158898-ff2bf843-6b07-48a2-89cd-c494d69164aa.png">

### PR Tasks

- [na] Have tests been added/updated?
- [x] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/4475
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [na] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-05-12 20:43 UTC, mjhenkes approved these changes

2022-05-12 20:57 UTC, chrisbreiding approved these changes

2022-05-12 21:32 UTC, emilyrohrbough approved these changes

2022-05-13 14:31 UTC, jennifer-shehane requested changes
This is only deprecating the use of these within the types, so only users with TypeScript would see this. We should also send a warning message to the console when these commands are used like cy.route: https://github.com/cypress-io/cypress/blob/10.0-release/packages/driver/src/cy/commands/xhr.ts#L400:L400

2022-05-13 16:39 UTC, mjhenkes approved these changes

2022-05-13 16:40 UTC, chrisbreiding approved these changes

2022-05-13 17:07 UTC, jennifer-shehane approved these changes

2022-05-13 19:53 UTC, AtofStryker approved these changes

2022-05-16 14:15 UTC, merged