fix: display cy.mount command log
cypress-io/cypress pull request #21500
Opened 2022-05-13 20:09 UTC by estrada9166

- Closes  [UNIFY-1671](https://cypress-io.atlassian.net/browse/UNIFY-1671)

### User facing changelog

Update vue2 to log the mount command, it was previously not being logged as we do for the different frameworks

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-05-16 00:47 UTC, lmiller1990 requested changes

2022-05-16 00:47 UTC, lmiller1990 commented on npm/vue2/src/index.ts
> +    const baseFileName = fileName.replace(/\.(js|ts|vue)?$/, '')
If `filepathSplit` does not have a `/`, `fileName` will be `undefined`, then we will get "Cannot call replace on undefined" here.

I think we need

```js
const fileName = filepathSplit[filepathSplit.length - 1] ?? DEFAULT_COMP_NAME
```

2022-05-16 19:15 UTC, ZachJW34 approved these changes
Looks good!

2022-05-16 20:52 UTC, tbiethman approved these changes

2022-05-17 02:36 UTC, lmiller1990 approved these changes

2022-05-17 02:36 UTC, merged