fix: disable ct testing when run via binary
cypress-io/cypress pull request #21540
Opened 2022-05-17 22:09 UTC by ZachJW34

- Closes [UNIFY-1695](https://cypress-io.atlassian.net/browse/UNIFY-1695)

### User facing changelog
Disable CT Testing when invoked from the binary

### Additional details
CT Testing requires the binary to be invoked from the cli due to the need to source the user's `node_module` dependencies. If the project is not invoked from the cli, we will now disable the option for the user to choose CT Testing from the page.

I did a small refactor of the testing type status. Since we are now adding another one (disabled), the attributes were getting hard to manage. I also had to make some changes to the `Card.vue` component as it had `pointer-events-none` when disabled which was preventing the link from being clicked.

### How has the user experience changed?

https://user-images.githubusercontent.com/25158820/168918630-ea76b0f3-8578-4247-8cc2-b36dc210c938.mov

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-05-18 13:47 UTC, tgriesser requested changes
Change seems fine to me - based on the test failures I'm assuming there's something else in  the e2e setup layer that needs to be adjusted to make this work?

2022-05-18 16:09 UTC, BlueWinds approved these changes
Some small suggestions, looks good overall. Thanks for the component refactors.

2022-05-18 16:09 UTC, BlueWinds commented on packages/frontend-shared/src/locales/en-US.json
> +      "link": "installing Cypress"
I'd prefer active over passive voice here.

```suggestion
      "description": "To test your components you must {0} as an NPM dependency for this project.",
      "link": "install Cypress"
```

2022-05-18 16:09 UTC, BlueWinds commented on packages/graphql/src/schemaTypes/objectTypes/gql-Query.ts
> +      description: 'Whether the app was invoked from the CLI',
```suggestion
      description: 'Whether the app was invoked from the CLI', False if user is using the binary without npm.
```

Just imagining coming in on this later and not being sure how else the app can be invoked.

2022-05-20 14:53 UTC, tgriesser approved these changes

2022-05-20 15:09 UTC, ZachJW34 commented on packages/frontend-shared/src/locales/en-US.json
> +      "link": "installing Cypress"
@BlueWinds going with your suggestion

2022-05-20 15:42 UTC, merged