fix: pass family parameter to connect method
cypress-io/cypress pull request #21545
Opened 2022-05-18 11:07 UTC by insane-developer

- Closes https://github.com/cypress-io/cypress/issues/21535

### User facing changelog
n/a

### Additional details

`family: 4` explicitly forces Socket.connect to use ipv4 address.
Without this change Socket.connect may use ipv6 address which whould lead to error due to the explicit use of `127.0.0.1` [here](https://github.com/cypress-io/cypress/blob/develop/packages/https-proxy/lib/server.js#L271).

### How has the user experience changed?

### PR Tasks

- [n/a] Have tests been added/updated?
- [n/a] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [n/a] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2022-05-18 11:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=21545) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=21545) before we can accept your contribution.<br/><hr/>**Andrey Mokrousov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=21545) it.</sub>

2022-05-18 12:46 UTC, jennifer-shehane requested changes
@insane-developer Could you please sign our CLA? We can’t accept any PRs without this signed.

2022-05-23 15:58 UTC, flotwig approved these changes
Looks good to me @insane-developer. We try to use `127.0.0.1` as much as possible to avoid bugs like this, but this is a much better fix.

2022-05-25 15:47 UTC, ryanthemanuel approved these changes

2022-05-25 18:16 UTC, merged