chore: document internal vite options
cypress-io/cypress pull request #21667
Opened 2022-05-27 18:42 UTC by AtofStryker

- Closes N/A

### User facing changelog

### Additional details
Wanted to take the opportunity to document some of the internal vite options as well as their function for posterity. Hopefully the added docs in the readme reflect things appropriately 😅 .
### Steps to test

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2022-06-07 21:28 UTC, lmiller1990 reviewed
Had no idea half of these existed - good to know, thanks for documenting.

I don't think these should be documented here, though. This is more for the `vite-dev-server` we publish on npm for CT users - these variables are exclusively internal for developing Cypress. I'm not sure where this should go, but likely not in `npm`.

2022-06-08 17:30 UTC, AtofStryker commented on npm/vite-dev-server/README.md
> +
```suggestion
```

2022-06-08 22:59 UTC, lmiller1990 approved these changes

2022-06-09 16:43 UTC, mschile requested changes

2022-06-09 17:18 UTC, AtofStryker commented on CONTRIBUTING.md
> +###### `CYPRESS_INTERNAL_VITE_INSPECT`
I think it just needs to be truthy, so I can probably add here that setting to `'1'` turns it on, similar to vite dev

2022-06-09 19:18 UTC, AtofStryker commented on CONTRIBUTING.md
> +Leveraged only when `CYPRESS_INTERNAL_VITE_DEV` is set to spawn the vite dev server for the launchpad on the specified port. The default port is `3001`.
It should already be below it https://github.com/cypress-io/cypress/pull/21667/files/8c769a60ab75531ef7e87b37e7ccddea9a5c5f87#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R414

2022-06-09 19:21 UTC, AtofStryker commented on CONTRIBUTING.md
> +###### `CYPRESS_INTERNAL_VITE_INSPECT`
added in 4767c6c7a8

2022-06-09 19:34 UTC, mschile commented on CONTRIBUTING.md
> +Leveraged only when `CYPRESS_INTERNAL_VITE_DEV` is set to spawn the vite dev server for the launchpad on the specified port. The default port is `3001`.
I was thinking more like a hierarchy but I'm fine with it this way too. I would suggest updating the `CYPRESS_INTERNAL_VITE_OPEN_MODE_TESTING` description to match the wording on these two though (i.e. "Leveraged only when `CYPRESS_INTERNAL_VITE_DEV is set..."

2022-06-13 19:08 UTC, AtofStryker commented on CONTRIBUTING.md
> +Leveraged only when `CYPRESS_INTERNAL_VITE_DEV` is set to spawn the vite dev server for the launchpad on the specified port. The default port is `3001`.
@mschile how's something like https://github.com/cypress-io/cypress/pull/21667/commits/bd409fa3b6d443b848dd41284f370585d4dc1c5f?

2022-06-13 20:07 UTC, merged