fix: call screencastOpts as a function for starting a screencast on e…
cypress-io/cypress pull request #23330
Opened 2022-08-13 20:12 UTC by htekdev

- Closes 

### User facing changelog

### Additional details

### Steps to test

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2022-08-13 20:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=23330) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=23330) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mjhenkes<br/>:x: htekdev<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=23330) it.</sub>

2022-08-15 14:04 UTC, mjhenkes requested changes
We haven't traditionally done patch fixes on prior major versions of Cypress. We'll need to discuss internally if/how we want to approach this. Marking this PR as Request changes to ensure it isn't merged until we're ready.

2022-09-01 21:01 UTC, emilyrohrbough commented
@htekdev At this time, we are not interested in creating a patch release for 9.x. Historically we have not done patch releases for previous major versions. This isn't to say we wouldn't consider it in the future, but at this time we will make that call on a case-by-case basis.

Is there a reason you are unable to update to Cypress 10.0 where this issue might be fixed and/or this change could be applied there?

2022-09-12 20:04 UTC, nagash77 commented
@htekdev We haven't heard from you in awhile so I am going to close this PR.  We would love to hear more about why you are unable to upgrade your Cypress to the latest version, so please do respond to this ticket if you can.  If there are blockers we would like to understand what they are.

2022-09-12 20:04 UTC, closed without merging