[CY-21858] Show tooltip when hovering over 'Create new spec' button within Specs panel in App
cypress-io/cypress pull request #23682
Opened 2022-09-05 08:42 UTC by gitstart

### User facing changelog

Fix an issue where the user does not see a tooltip showing text `Create new spec` on the `+` button on hover.

### Additional details
Improve user accessibility making it clear the purpose of the `+` button on hover.

### Refs
[GitStart Issue](https://app.gitstart.com/clients/cypress/tickets/CYP-40)
[Cypress Issue](https://github.com/GitStartHQ/client-cypress/issues/40)

### Steps to test
- Hover Mouseover `+` Button. Should show tooltip `Create new spec`

### How has the user experience changed?

#### Before
https://www.loom.com/share/dc1b7c5e47ef42e1bca42977dfc3cc21

#### After
https://www.loom.com/share/7a07b98860b346e1bb6f1c96c34dd74b

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2022-09-05 09:06 UTC, gitstart commented
Hi @marktnoonan Could you help to trigger CI build on this PR, thanks.

2022-09-23 00:46 UTC, lmiller1990 reviewed
One comment. I'll run CI.

2022-09-23 00:46 UTC, lmiller1990 commented on packages/frontend-shared/src/locales/en-US.json
> +    "createNewSpec": "Create new spec",
```suggestion
    "createNewSpec": "Create New Spec",
```

2022-09-23 18:15 UTC, emilyrohrbough requested changes
Why is tooltip needed in this scenario? The button's message is fine. This bloats the dom unnecessarily. If we need a tooltip we should provide a message that gives better insides into what "new spec means".

2022-09-25 16:43 UTC, gitstart commented
Thanks for the review @emilyrohrbough,
The PR was created to resolve issue raised in #21858 with the assumption that a tooltip is desired as mentioned in issue. Do you propose that it might not be the case? or prefer a better tooltip message.
CC: @lmiller1990

2022-09-26 00:20 UTC, lmiller1990 commented
I kind of agree with @emilyrohrbough - I am not sure a button really needs a tooltip. I think the original issue seems obsolete, we should have closed it before work was put into this.

I think we should close this. Sorry to waste your time/effort @gitstart - might be worth tagging someone before picking up something if there's any ambiguity.

2022-09-26 00:20 UTC, closed without merging