fix: update mocha-junit-reporter in server package
cypress-io/cypress pull request #24218
Opened 2022-10-12 03:25 UTC by Turbotailz

This change was meant to be included in #24056 but I missed the dependency also residing in the server package.json

This should fix #18970

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2022-10-12 14:14 UTC, marktnoonan requested changes
Not actually requesting changes, but since we have folks on the issue willing to try out a pre-release version, let's get that validation done before we merge, to make sure there's nothing else needed to close that issue.

2022-10-12 14:24 UTC, emilyrohrbough approved these changes

2022-10-12 14:46 UTC, AtofStryker approved these changes

2022-10-13 20:07 UTC, marktnoonan approved these changes

2022-10-13 21:48 UTC, merged