fix: get correct env from npm config
cypress-io/cypress pull request #24664
Opened 2022-11-13 16:48 UTC by abcfy2

`npm config set VAR VAL` will inject `npm_config_var=val` environment variable. This commit will solve this issue

Closes: #24556

2022-11-13 16:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=24664) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=24664) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=24664) it.</sub>

2022-11-17 01:01 UTC, ryanthemanuel requested changes
Can we add a test for this?

2022-11-17 02:56 UTC, abcfy2 commented
> Can we add a test for this?

I don't know how to add this test case. Because `npm config set FOO BAR`should execute before test.

If we add this command in unit test, then we should execute this test in sub process.

2022-11-17 03:23 UTC, abcfy2 commented
> Can we add a test for this?

I try to add a simple unit test for this. You can review again. Thanks.

2022-11-22 03:21 UTC, ryanthemanuel approved these changes

2022-11-23 14:14 UTC, mjhenkes approved these changes

2022-11-28 13:21 UTC, abcfy2 commented
Hi @marktnoonan . Please review my PR and let me know if I lost something. Thanks.

2022-11-29 15:12 UTC, mjhenkes commented on system-tests/lib/system-tests.ts
> +      },
```suggestion
```

2022-11-29 16:03 UTC, mjhenkes commented on .circleci/workflows.yml
> +            CYPRESS_COMMERCIAL_RECOMMENDATIONS=0
```suggestion
```

2022-11-29 16:03 UTC, mjhenkes commented on .circleci/workflows.yml
> +            CYPRESS_COMMERCIAL_RECOMMENDATIONS=0
```suggestion
```

2022-11-29 16:04 UTC, mjhenkes commented on .circleci/workflows.yml
> +          command: CYPRESS_COMMERCIAL_RECOMMENDATIONS=0 yarn workspace @tooling/system-tests test:ci "test/non_root*spec*" --browser electron
```suggestion
          command:  yarn workspace @tooling/system-tests test:ci "test/non_root*spec*" --browser electron
```

I need to fix these in develop for them to apply

2022-11-29 18:00 UTC, mjhenkes commented on cli/test/lib/util_spec.js
> +
```suggestion


```

2022-11-29 18:00 UTC, mjhenkes commented on cli/test/lib/util_spec.js
> +
```suggestion
```

2022-12-01 21:43 UTC, mjhenkes commented
Yay a green build, @abcfy2 thanks for the PR and being patient while i got the build fixed!

2022-12-01 21:43 UTC, merged