feature to add #24964
cypress-io/cypress pull request #25467
Opened 2023-01-14 12:06 UTC by nilgaar

- Closes #24964 

### User facing changelog
The `cy.log()` `message` will display a line breaks if containing `\n`.
Also, `Cypress.log` `message` will, of course, behave the same way.

### Additional details
This feature enriches the `cypress open` functionality, by adding the line break to the `log` command.
Staking `\n` will be translated in a single line break.

### Steps to test
#### `cy.log`
1. Build up a cypress test, add a log like: `cy.log('I am the first line! \n I am the second line!'`
2. Run your test with `cypress open`

#### `Cypress.log`
1. Build up a cypress test, add a log like: `Cypress.log({displayName:'I won\'t be \n broken!!', message:"but I \n will"})`
2. Run your test with `cypress open`

### How has the user experience changed?
Not sure if this can be considered a user experience change but:
from this:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/73447234/212470749-9f6b5c24-151b-48c1-b799-4d09cf58b301.png">

to this:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/73447234/212470700-723b9213-bc11-41a8-b703-88c4c8a69a75.png">

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has the original issue (or this PR, if no issue exists) been tagged with a release in ZenHub? (user-facing changes only)
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2023-01-14 12:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=25467) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=25467) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=25467) it.</sub>

2023-01-18 15:07 UTC, mike-plummer requested changes

2023-01-18 15:07 UTC, mike-plummer commented on packages/reporter/src/commands/command.tsx
> +  const withLineBreaks = converted.replace(/\n/g, '<br>')
It looks like `markdown-it` has built-in support for this through the [`breaks` parameter](https://markdown-it.github.io/markdown-it/#MarkdownIt.new) (which defaults to false). We should be able to update line 27 to something like this to get the same behavior

```
const md = new Markdown({ breaks: true })
```

2023-01-18 18:28 UTC, AtofStryker requested changes
Hi @nilgaar. Thank you for opening a PR! Nothing here stands out to me that would cause significant issues but are you able to add a test in the driver in [log.cy.ts](https://github.com/cypress-io/cypress/blob/develop/packages/driver/cypress/e2e/cypress/log.cy.js) to verify the line break behavior?

2023-01-23 21:30 UTC, AtofStryker commented
@mike-plummer are you able to take another look at this?

2023-01-23 21:36 UTC, BlueWinds approved these changes

2023-01-23 22:46 UTC, lmiller1990 approved these changes

2023-01-24 02:58 UTC, lmiller1990 commented
Two approvals, let's merge this up. Thanks for the contribution!

2023-01-24 02:58 UTC, merged