feat: Added configuration parameter that controls the amount of connection attempts to the browser
cypress-io/cypress pull request #25848
Opened 2023-02-16 12:12 UTC by Malvitus

### Additional details
Currently, there is a hardcoded limit of 62 attempts until a connection to the browser is considered fails. For my usecase, this timeout is sometimes to low and i can't change it.

I added a config value and made sure that it is used at the corresponding places when connections to browsers is attempted.

### Steps to test
1. Try to start a browser without changing the config. Everything should work just fine
2. Set connectRetryThreshold to an absurd low value (like 5). Connection should fail due to timeout

### How has the user experience changed?
In the default usecase, Experience did not change. However when users experience connection timeouts, User can adjust the config value to stabilize their tests.

### PR Tasks
- [ x] Have tests been added/updated?
- [ x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? (https://github.com/cypress-io/cypress-documentation/pull/5070)
- [x ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

###  Other

As this is my first PR for cypress, i am unsure if I did everything right. Should something be amiss, please contact me and I will try my best to solve the issues.

2023-02-16 12:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=25848) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=25848) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=25848) it.</sub>

2023-02-16 17:53 UTC, flotwig requested changes
@Malvitus Thanks for opening a PR.

Instead of adding a new configuration option, could you use an environment variable instead? Something like `CYPRESS_BROWSER_CONNECTION_RETRIES`. Since the vast majority of users won't need to adjust this value there's no need to put it in config.

2023-02-17 07:19 UTC, Malvitus commented
Sure, I can change it to an Environment Variable. Should I open a new PR then?

2023-02-20 08:12 UTC, Malvitus commented
@flotwig 
I completed the changes and kept them in this PR  just in case. I did not modify the changelog yet as im unsure when this change can be released. I also adjusted my Pr in the documentation repo

2023-02-28 15:22 UTC, flotwig approved these changes
This looks good @Malvitus. Can you clarify your use case on why you want to add this? Why is it taking more than a minute for your browser to open?

2023-02-28 19:12 UTC, mjhenkes commented on packages/server/lib/browsers/firefox-util.ts
> +  if (i < maxRetries) {
```suggestion
  if (i <= maxRetries) {
```
looks like we lost a retry here

2023-03-01 08:49 UTC, Malvitus commented on packages/server/lib/browsers/firefox-util.ts
> +  if (i < maxRetries) {
Good Catch!. I commited your suggestion

2023-03-01 09:11 UTC, Malvitus commented
@flotwig 

I confess that my setup is not that straight forward. For once, my server executing the tests is not that beefy, so execution of anything is not that fast (which I don't mind). The other factor is that I have different browser versions i want to use in my Cypress tests on a network share (as I don't want them to clutter the machine). So depending on the available bandwidth, starting a browser can take longer than expected. Again this is fine for me as I don't have that many tests. Also its not the case that the browsers never start in time, just that they sometimes take a bit longer, which introduces a flakyness to my tests. So after I saw that the connection timeout is hardcoded, I thought it might be a good idea to introduce a config option there so that users can adjust the timeout up or down if needed.

2023-03-01 14:01 UTC, mjhenkes approved these changes

2023-03-01 16:21 UTC, mjhenkes commented
@Malvitus could you add a changelog entry here: https://github.com/Malvitus/cypress/blob/develop/cli/CHANGELOG.md

```md
**Features:**

 - <Insert change details>. Addressed in [#25848](https://github.com/cypress-io/cypress/pull/25848).
```

2023-03-02 08:11 UTC, Malvitus commented
@mjhenkes Done. Do you need anything else?

2023-03-02 14:06 UTC, mjhenkes commented
@Malvitus, looks good! Thanks for the contribution. I'll work on getting this merged today.

2023-03-02 14:06 UTC, mjhenkes commented on cli/CHANGELOG.md
> +## 12.8.0
```suggestion
## 12.8.0
```

2023-03-02 14:26 UTC, mjhenkes commented on cli/CHANGELOG.md
> +_Released (PENDING)_
```suggestion
_Released xx/xx/xxxx (PENDING)_
```

2023-03-02 14:39 UTC, mjhenkes commented on cli/CHANGELOG.md
> +_Released xx/xx/xxxx (PENDING)_
```suggestion
_Released 03/14/2023 (PENDING)_
```

2023-03-02 21:56 UTC, merged