chore: update triage workflow to add comment to contributor prs
cypress-io/cypress pull request #26493
Opened 2023-04-13 13:56 UTC by emilyrohrbough

Related PR: https://github.com/cypress-io/release-automations/pull/81

Adds PR comments to 
- dep bot pr to add guidance on reviewing
- contributor PRs to add guidance on how to contribute

2023-04-18 19:34 UTC, nagash77 approved these changes

2023-04-18 19:35 UTC, nagash77 requested changes

2023-04-18 19:35 UTC, nagash77 commented on .github/workflows/triage_add_to_project.yml
> +          ref: 'move-to-action'
```suggestion
          ref: 'master'
```

2023-04-18 20:15 UTC, nagash77 commented
Just an FYI I tested these in an adapted version on this [PR](https://github.com/nagash77-cypress/hello-world-javascript-action/pull/88) in my own repo.  Here is [a link to the action being successfully run](https://github.com/nagash77-cypress/hello-world-javascript-action/actions/runs/4735651730).

2023-04-20 14:39 UTC, emilyrohrbough commented on .github/workflows/triage_add_to_project.yml
> +          ref: 'move-to-action'
Will update once https://github.com/cypress-io/release-automations/pull/81 merges

2023-05-11 16:07 UTC, nagash77 approved these changes

2023-05-17 14:41 UTC, mjhenkes approved these changes

2023-05-17 14:41 UTC, merged