Ct 26204 typescript config fix
cypress-io/cypress pull request #26815
Opened 2023-05-19 20:01 UTC by dkasper-was-taken

- Closes #26204 

### Additional details

### Steps to test
- Make a new folder
- yarn init in directory

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2023-05-19 20:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=26815) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=26815) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=26815) it.</sub>

2023-05-22 15:54 UTC, astone123 approved these changes

2023-05-22 17:08 UTC, mike-plummer requested changes

2023-05-22 17:08 UTC, mike-plummer commented on cli/CHANGELOG.md
> +- Fixed Typescript detection in component testing setup. Fixed in [#26204](https://github.com/cypress-io/cypress/issues/26204).
```suggestion
- Fixed an issue in Component Testing setup where TypeScript version 5 was not properly detected. Fixes [#26204](https://github.com/cypress-io/cypress/issues/26204).
```

2023-05-22 17:37 UTC, mike-plummer approved these changes

2023-05-22 21:09 UTC, merged