fix: Properly type Cypress and Chai globals as properties of the global object
cypress-io/cypress pull request #27540
Opened 2023-08-11 22:10 UTC by rewento

Minor modifications to CLI types so that Cypress and Chai globals are correctly declared not only to be in the global scope but also to be in properties of globalThis, which they are. The change allows composers to reference them through the global object (e.g., 'globalThis.cy.mount', 'globalThis.expect', 'window.assert'). The current typing prohibits this by incorrectly declaring that the objects in question are held in local variables of the global scope rather than in properties of the global object.

- Closes [Issue 27539](https://github.com/cypress-io/cypress/issues/27539)

### Additional details

- Why was this change necessary?
This small accommodates a coding style convention that demands that values in properties of the global object be accessed via the globalThis property of that object to enhance clarity regarding the origin of the values as globals as opposed to values defined in and imported from modules.
- What is affected by this change?
The change has no impact on the TypeScript compiler's acceptance of code that uses Cypress globals without that convention, which is the majority of such code.
- Any implementation details to explain?
Resolving the issue entailed swapping the use of `const` for `var` in type declarations in cli/types/cypress-expect.d.ts and cli/types/cypress-global-vars.d.ts.

### Steps to test

Ensure that typical code that leverages Cypress like this still is accepted by the TypeScript compiler:

```ts
const browserVersion = window.Cypress.browser.version;
window.cy.mount(AppComponent);
window.assert("foo" !== "bar", "foo is not bar");
window.expect(true).not.to.be.false;
```

Then confirm that the TypeScript compiler also issues no errors regarding code that follows the aforementioned convention like the following:

```ts
const browserVersion = window.Cypress.browser.version;
window.cy.mount(AppComponent);
window.assert("foo" !== "bar", "foo is not bar");
window.expect(true).not.to.be.false;
```

```ts
const browserVersion = globalThis.Cypress.browser.version;
globalThis.cy.mount(AppComponent);
globalThis.assert("foo" !== "bar", "foo is not bar");
globalThis.expect(true).not.to.be.false;
```

### How has the user experience changed?

Before:
<img width="673" alt="image" src="https://github.com/cypress-io/cypress/assets/62110041/2fbb2210-425f-4a48-8c1a-ca59e65a1a3b">

After:
<img width="686" alt="image" src="https://github.com/cypress-io/cypress/assets/62110041/3ffac3f0-8935-4e2b-b4f3-a3a5deec80f5">

### PR Tasks

- [na] Have tests been added/updated?
- [no] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? (Little to no value in drawing attention in the documentation to the fact that `globalThis.cy` and `window.cy` now work just as well as `cy` in TypeScript code.)
- [yes] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2023-08-11 22:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=27540) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=27540) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=27540) it.</sub>

2023-08-17 14:42 UTC, chrisbreiding requested changes
Thanks for the contribution! Could you add tests for this in [cypress-tests.ts](https://github.com/cypress-io/cypress/blob/develop/cli/types/tests/cypress-tests.ts)? Adding the following should suffice:

```
namespace CypressGlobalsTests {
  Cypress
  cy
  expect
  assert

  window.Cypress
  window.cy
  window.expect
  window.assert

  globalThis.Cypress
  globalThis.cy
  globalThis.expect
  globalThis.assert
}
```

2023-08-18 17:09 UTC, rewento commented
@chrisbreiding 

I'll soon push a commit on to the source branch of this PR that adds the code you provided in [your comment](https://github.com/cypress-io/cypress/pull/27540#pullrequestreview-1582791027) to the cypress-test.ts file verbatim.

However, the JavaScript compiled from that added test code would execute with no runtime error with or without the Cypress and Chai globals type changes introduced in this PR. That being said, the TypeScript compiler would refuse to compile cypress-tests.ts in the first place without those type adjustments.

So is that a good enough addition to the tests? That the added test logic, while incapable of triggering a runtime error under any circumstances, would outright prevent the compilation (and thus execution) of the test code itself without the Cypress and Chai globals type changes in question?

2023-08-18 17:34 UTC, chrisbreiding commented
> So is that a good enough addition to the tests? That the added test logic, while incapable of triggering a runtime error under any circumstances, would outright prevent the compilation (and thus execution) of the test code itself without the Cypress and Chai globals type changes in question?

Yes, we have a CI job that runs the TypeScript compiler on that file, so it stands as a test for the TypeScript types. Since it fails without these type additions, it's a perfectly good test that they're doing what we expect them to do. Thanks for adding them!

2023-08-18 18:00 UTC, chrisbreiding approved these changes

2023-08-24 15:21 UTC, nagash77 approved these changes

2023-08-24 15:22 UTC, merged