fix: fix failures and correlation in proxy
cypress-io/cypress pull request #28094
Opened 2023-10-20 02:07 UTC by ryanthemanuel

### Additional details

We recently made a change to clean up browser prerequests when requests are aborted, but we don't do the same thing with proxy prerequests. This PR ensures that we clean things up on both sides.

### Steps to test

I added some integration tests to cover if CDP failures come in first vs. proxy failures.

### How has the user experience changed?

n/a

### PR Tasks

- [X] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2023-10-20 14:23 UTC, chrisbreiding approved these changes

2023-10-23 15:02 UTC, cacieprins requested changes

2023-10-23 15:02 UTC, cacieprins commented on packages/proxy/lib/http/index.ts
> +      const pendingRequest = ctx.pendingRequest as PendingRequest | undefined
This coercion is needed because ctx is `HttpMiddlewareCtx<any>`, which causes `ctx` to be `any`.

Removing this templated `any` results in a couple of typescript errors that may be indicative of bugs; one of which is in `deferSourceMapRewrite` which should be returning a string instead of void (unless the fn definition on L#320 is more correct than the type definition on L#68). Can resolving the ambiguous definition of `ctx` be rolled into this PR, or is that out of scope?

2023-10-23 15:02 UTC, cacieprins commented on packages/proxy/lib/http/util/prerequests.ts
> +      this.queues[queueKey].splice(i, 1)
if `value` is not in `this.queues[queueKey]`, this will remove the last item in `this.queues[queueKey]` even if it doesn't match the value passed in - is that desired behavior?

gating this operation on `!!~i` should fix it

2023-10-23 15:45 UTC, ryanthemanuel commented on packages/proxy/lib/http/index.ts
> +      const pendingRequest = ctx.pendingRequest as PendingRequest | undefined
I think at this point given I want to try and get this in for tomorrow, that I'll call this out of scope for now. It's a good find though. This can definitely be cleaned up at some point.

2023-10-23 16:38 UTC, ryanthemanuel commented on packages/proxy/lib/http/util/prerequests.ts
> +      this.queues[queueKey].splice(i, 1)
Ooh good catch. Fixed and added a test: [`d1fd7ea` (#28094)](https://github.com/cypress-io/cypress/pull/28094/commits/d1fd7ea551fe6923c4b86b0536e8197a8d7c0a04)

2023-10-23 16:39 UTC, ryanthemanuel commented on cli/CHANGELOG.md
> +- Fixed a performance problem with proxy correlation when requests get aborted and then get miscorrelated with follow up requests. Addressed in [#28094](https://github.com/cypress-io/cypress/pull/280
```suggestion
- Fixed a performance problem with proxy correlation when requests get aborted and then get miscorrelated with follow up requests. Fixed in [#28094](https://github.com/cypress-io/cypress/pull/28094).
```

2023-10-23 17:28 UTC, cacieprins approved these changes

2023-10-23 21:08 UTC, merged