Cacie/feat/upload activity indicator
cypress-io/cypress pull request #28277
Opened 2023-11-08 17:01 UTC by cacieprins

- Closes [#28239](https://github.com/cypress-io/cypress/issues/28239)

### Additional details

When uploading large artifacts to the cloud, we need a keep alive signal for CI systems, as well as an indicator for users when running in record mode locally.

### Steps to test

1. Throttle network connections using charles proxy or similar (alternatively, select a project that generates a large test replay database or video)
2. Run cypress in record mode
3. Verify the upload indicator progresses

### How has the user experience changed?

(screenshots to be taken)

### PR Tasks

- [X] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2023-11-09 15:36 UTC, cacieprins commented on cli/CHANGELOG.md
> +## 13.6.0
```suggestion

## 13.6.0
```

2023-11-09 18:25 UTC, chrisbreiding approved these changes

2023-11-13 16:27 UTC, cacieprins commented on system-tests/lib/normalizeStdout.ts
> -  .replace(/(Uploading Screenshots & Videos.*?\n\n)((.*-.*[\s\S\r]){2,}?)(\n\n)/g, replaceUploadingResults)
This mask was no longer in used, so replaced with the activity mask

2023-11-14 14:59 UTC, jennifer-shehane requested changes
The animation looks great.

@cacieprins Could we have the 'Uploading' text indented 2 spaces like the other text? 

<img width="398" alt="Screen Shot 2023-11-14 at 9 55 22 AM" src="https://github.com/cypress-io/cypress/assets/1271364/954f45e8-c4e6-44a6-890c-217a7b40cce5">

I also wonder if there should be some interval before printing the 'Uploading Cloud Artifacts: .' text, where it will just skip this if it uploads so fast. Most of my run just had this line printed arbitrarily when the upload was instant.

2023-11-16 16:35 UTC, jennifer-shehane commented
@cacieprins Mine has the Uploading displaying without a spaced line above it from the Test Replay output, like shown in your screenshots.

<img width="549" alt="Screen Shot 2023-11-16 at 11 35 00 AM" src="https://github.com/cypress-io/cypress/assets/1271364/faa83d0a-0079-49bb-afa0-fbeadcd38030">

2023-11-20 15:48 UTC, jennifer-shehane approved these changes

2023-11-20 16:50 UTC, merged