chore: implement record telemetry
cypress-io/cypress pull request #28425
Opened 2023-11-29 16:11 UTC by emilyrohrbough

Add telemetry insights for Cypress record mode.

2023-12-28 20:49 UTC, jennifer-shehane approved these changes
@emilyrohrbough Might be nice to note in the PR description that this is just tracking telemetry on our OWN tests, not data collected of our users.

2024-01-02 15:31 UTC, cacieprins requested changes

2024-01-02 15:31 UTC, cacieprins commented on packages/server/lib/modes/record.js
> +            const result = updateInstanceStdout({
`updateInstanceStdout` pushes stdout data to Cy Cloud & returns a promise - should this promise resolve before ending the span?

2024-01-03 15:37 UTC, emilyrohrbough commented on packages/server/lib/modes/record.js
> +            const result = updateInstanceStdout({
nice catch 👍🏻 updated - [`5ca160c` (#28425)](https://github.com/cypress-io/cypress/pull/28425/commits/5ca160c811a5ae3a4efd708784bb9bbdfe9675f4)

2024-01-03 19:35 UTC, cacieprins approved these changes

2024-01-03 20:09 UTC, merged