fix: patch vulnerable browserify-sign dep
cypress-io/cypress pull request #28573
Opened 2023-12-21 21:07 UTC by jordanpowell88

- Closes https://github.com/cypress-io/cypress/issues/28240

### Additional details
Currently their is a security vulnerability for `< browserify-sign@4.2.1`. It is only being used in our system tests but is hoisted to root. This PR adds a resolution so that we pin to `browserify-sign@4.2.2` to avoid hitting this security vulnerability.

### Steps to test

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2023-12-22 13:06 UTC, jennifer-shehane approved these changes

2023-12-28 15:07 UTC, emilyrohrbough commented on cli/CHANGELOG.md
> +- Updated browserify-sign from `<=4.2.1` to `4.2.2`. Addresses [#28240](https://github.com/cypress-io/cypress/issues/28240).
Given this is only used in system tests, we should not have a changelog entry & the pr title should be chore.

2023-12-28 15:07 UTC, emilyrohrbough requested changes
This is a chore

2023-12-29 18:10 UTC, emilyrohrbough approved these changes

2023-12-29 22:35 UTC, merged