chore: remove matrix from Synk SCA Scan
cypress-io/cypress pull request #28761
Opened 2024-01-20 17:26 UTC by emilyrohrbough

- Closes 

### Additional details

### Steps to test

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-01-20 17:27 UTC, emilyrohrbough commented on .github/workflows/snyk_sca_scan.yaml
>      # Skip this job on PRs from forks
```suggestion
    # skip this job on PRs from forks
```

2024-01-22 13:19 UTC, AtofStryker approved these changes

2024-01-22 18:02 UTC, jennifer-shehane approved these changes

2024-01-22 18:03 UTC, jennifer-shehane requested changes
@emilyrohrbough Is the Snyk scan running at all?

2024-01-22 18:44 UTC, emilyrohrbough commented
@jennifer-shehane Yes, before we merge this we will need to update the required check to be `Snyk Software Composition Analysis Scan / Snyk_SCA_Scan (pull_request)` and remove `Snyk_SCA_Scan (18.x)`
See https://github.com/cypress-io/cypress/actions/runs/7595830123/job/20688818407?pr=28761

2024-04-23 16:26 UTC, closed without merging