misc: Replacing LayerCI references with webapp.io (finishing previous PR)
cypress-io/cypress pull request #28874
Opened 2024-02-06 10:24 UTC by joshuadsouza

- Closes

### Additional details
LayerCI has rebranded to webapp.io, context here https://webapp.io/blog/layerci-has-rebranded-to-webapp-io/. 

The environment build variables have updated in webapp.io to some new variables (instead of the old ones with reference to LayerCI). Refer to the following documentation in webapp.io with the [`environment build variables`](https://docs.webapp.io/layerfile-reference/build-env)

This PR finishes up the work done in this previously opened PR https://github.com/cypress-io/cypress/pull/28577/files and also adds in the `EXPOSE_WEBSITE_HOST` build environment variable exposed by webapp.io 

### Steps to test

### How has the user experience changed?

### PR Tasks
- [x] Have tests been added/updated?
- [x] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? https://github.com/cypress-io/cypress-documentation/pull/5632
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-02-06 10:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=28874) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=28874) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=28874) it.</sub>

2024-02-06 14:43 UTC, jennifer-shehane requested changes
@joshuadsouza What's the intention behind adding the `EXPOSE_WEBSITE_HOST`? I don't think this env var is needed. These env vars are primarily surfaced for Cypress use, and we don't have a need for this env var that I can see. 

Otherwise this looks good!

2024-02-06 15:29 UTC, joshuadsouza commented
> @joshuadsouza What's the intention behind adding the `EXPOSE_WEBSITE_HOST`? I don't think this env var is needed. These env vars are primarily surfaced for Cypress use, and we don't have a need for this env var that I can see.
> 
> Otherwise this looks good!

Got it, just updated the PR and removed `EXPOSE_WEBSITE_HOST` 👍

2024-02-06 16:12 UTC, jennifer-shehane approved these changes

2024-02-13 20:03 UTC, cacieprins approved these changes

2024-02-19 18:25 UTC, merged