refactor: ensure 'its' function type excludes null and undefined (#28872)
cypress-io/cypress pull request #28904
Opened 2024-02-09 08:34 UTC by AkshatHotCode

This fix addresses an issue where the 'its' function could return null or undefined, causing unexpected behavior in certain scenarios. The change introduces a more robust type check to ensure that the returned value is always non-null and non-undefined.

- Closes [https://github.com/cypress-io/cypress/issues/28872]

### Additional details
The change was necessary to address an issue where the 'its' function could potentially return null or undefined. This behavior led to unexpected outcomes in certain scenarios. The fix ensures that the 'its' function consistently returns a value that is non-null and non-undefined.
The affected area is the 'its' function, specifically its type signature. Prior to the fix, the function had the potential to return null or undefined. This change impacts any usage of the 'its' function, ensuring that users can rely on a non-null and non-undefined result.
The implementation involves a modification to the 'its' function to include a more robust type check. This check ensures that the returned value is guaranteed to be non-null and non-undefined. 

### Steps to test

### How has the user experience changed?

### PR Tasks

- [na] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-02-09 08:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=28904) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=28904) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=28904) it.</sub>

2024-02-09 15:54 UTC, jennifer-shehane requested changes
@AkshatHotCode There are some errors in the lint types and unit tests. Could you look at those from the failing CircleCI checks above? We'll also need a changelog entry for this change. https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md

2024-02-27 15:00 UTC, jennifer-shehane requested changes
@AkshatHotCode Looks like there's some Lint errors - likely from the formatting changes you made that were unrelated to the actual fix. https://app.circleci.com/pipelines/github/cypress-io/cypress/60042/workflows/b5c2b3d3-bbae-40df-92db-f7058dd2a131/jobs/2498299

![Screenshot 2024-02-27 at 9 59 43 AM](https://github.com/cypress-io/cypress/assets/1271364/5c606bcb-bb69-4060-b725-d1ca3e5b89f5)

2024-03-07 14:28 UTC, jennifer-shehane commented
@AkshatHotCode Will you have time to address the lint errors? We'll have to close this PR otherwise.

2024-03-08 05:27 UTC, AkshatHotCode commented
I will address this.

2024-03-08 06:44 UTC, AkshatHotCode commented
@jennifer-shehane Changes are being made, apologies for the delay.

2024-03-26 15:12 UTC, ryanthemanuel commented on cli/types/cypress.d.ts
> +       */add<T extends keyof Chainable>(name: T, options: CommandOptions & { prevSubject: false }, fn: CommandFn<T>): void
```suggestion
       */
       add<T extends keyof Chainable>(name: T, options: CommandOptions & { prevSubject: false }, fn: CommandFn<T>): void
```

2024-04-01 14:16 UTC, ryanthemanuel commented on cli/types/cypress.d.ts
> +       add<T extends keyof Chainable>(name: T, options: CommandOptions & { prevSubject: false }, fn: CommandFn<T>): void
```suggestion
      add<T extends keyof Chainable>(name: T, options: CommandOptions & { prevSubject: false }, fn: CommandFn<T>): void
```

2024-04-02 15:29 UTC, ryanthemanuel approved these changes

2024-04-17 14:17 UTC, jennifer-shehane commented
@AkshatHotCode Looking back at this, sorry for the delay

2024-04-17 14:24 UTC, jennifer-shehane approved these changes

2024-04-23 16:38 UTC, merged