docs: Add link to chromeWebSecurity read more
cypress-io/cypress pull request #29146
Opened 2024-03-14 12:47 UTC by esetnik

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [x] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-03-14 12:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=29146) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=29146) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=29146) it.</sub>

2024-03-14 15:49 UTC, jennifer-shehane approved these changes

2024-03-14 15:51 UTC, jennifer-shehane requested changes
We'd want an on link so that we can redirect this in the future.

2024-03-14 15:51 UTC, jennifer-shehane commented on cli/types/cypress.d.ts
> +     * Whether Chrome Web Security for same-origin policy and insecure mixed content is enabled. Read more about this [here](https://docs.cypress.io/guides/guides/web-security#Disabling-Web-Security)
```suggestion
     * Whether Chrome Web Security for same-origin policy and insecure mixed content is enabled. Read more about this [here](https://on.cypress.io/web-security#Disabling-Web-Security)
```

2024-03-20 00:44 UTC, esetnik commented
@jennifer-shehane is there anything else I need to do in order to get this merged?

2024-03-21 16:07 UTC, jennifer-shehane approved these changes

2024-04-03 16:08 UTC, AtofStryker approved these changes
to `.d.ts` render like markdown files?

2024-04-03 17:14 UTC, jennifer-shehane commented
@AtofStryker There was a link in some other parts, so I assumed so. https://github.com/cypress-io/cypress/pull/29146/files#diff-9fde1fb2f7eaba5ea49b585c811461495bfbba88e614e900a96863ecfe6b980aL3001

2024-04-03 17:15 UTC, merged