fix: Encode fileServerFolder to fix #25839
cypress-io/cypress pull request #29162
Opened 2024-03-17 02:45 UTC by Zzet-Z

- Closes https://github.com/cypress-io/cypress/issues/25839 

### Additional details
When there are special characters in our test folder path, (such as Chinese characters) and under the ubuntu system, the folder path is not parsed correctly, causing Cypress to crash and throw a stack error "Invalid character in header content ["x- cypress-file-path"]".
This PR will encode the test folder path to solve the issue and decode it in the error_messages.ts file to prevent the error log from being expressed intuitively.

### Steps to test

### How has the user experience changed?

### PR Tasks
- [NA] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-03-19 15:08 UTC, jennifer-shehane submitted a review, later dismissed
Thanks for the contribution! Could you add a test around this behavior? We'll need a test in order to merge the fix.

2024-03-20 01:38 UTC, Zzet-Z commented
> Thanks for the contribution! Could you add a test around this behavior? We'll need a test in order to merge the fix.
I added a new unit test case, but since this issue will only occur in Ubuntu, I just can write a passing case. Is this okay?

2024-03-29 01:53 UTC, Zzet-Z commented
@jennifer-shehane Thanks for your review！
Sorry，I hit the Unassign button by mistake😖.
This is my first time making an open source contribution. I have checked many related documents on GitHub, but I am still a little confused about the current process. Is there anything else that I need to deal with now? Looking forward to your help.

2024-04-17 14:21 UTC, jennifer-shehane commented on packages/server/test/unit/config_spec.js
> +        it('passes if a string contain invalid character but encode it', function () {
```suggestion
        it('passes if a string contains an invalid character but encodes it', function () {
```

2024-04-18 03:48 UTC, Zzet-Z commented
@jennifer-shehane I'm a bit confused right now, sorry. Is there anything else need me to do,  or just wait for you to verify and initiate the merge?

2024-04-19 15:25 UTC, jennifer-shehane commented
@Zzet-Z Just waiting til next sprint to see if I can assign some more eyes to review this.

2024-04-19 15:54 UTC, Zzet-Z commented
> @Zzet-Z Just waiting til next sprint to see if I can assign some more eyes to review this.

OK thx！

2024-04-22 15:06 UTC, jennifer-shehane requested changes, later dismissed
@Zzet-Z There appear to be some failing tests with this change: https://app.circleci.com/pipelines/github/cypress-io/cypress/61086/workflows/6745104d-7a56-4c94-a750-d7c5a415b06e/jobs/2539954

2024-04-24 01:53 UTC, Zzet-Z commented
> @Zzet-Z There appear to be some failing tests with this change: https://app.circleci.com/pipelines/github/cypress-io/cypress/61086/workflows/6745104d-7a56-4c94-a750-d7c5a415b06e/jobs/2539954

@jennifer-shehane Oh, that's a problem, and I found some other problems and dealt with them. The local operation passed these tests. Could you please help me run the integration test again if it is convenient.

2024-04-24 16:36 UTC, jennifer-shehane commented
@Zzet-Z Running them now

2024-04-25 01:48 UTC, Zzet-Z commented
@jennifer-shehane Oops,I neglected a test case, now it is updated, please help run it again when you are free.By the way, there are still a small part of failures that seem not to be caused by my changes, could you please help me check whether these need my attention, thx!

2024-05-16 22:57 UTC, mschile commented on cli/CHANGELOG.md
> +- Fixed an issue parsing the `fileServerFolder` path when there are special characters. Fixes [#25839](https://github.com/cypress-io/cypress/issues/25839).
```suggestion
- Fixed an issue setting the `x-cypress-file-path` header when there are invalid header characters in the file path. Fixes [#25839](https://github.com/cypress-io/cypress/issues/25839).
```

2024-05-16 22:59 UTC, mschile approved these changes

2024-05-17 14:10 UTC, ryanthemanuel approved these changes

2024-05-21 14:54 UTC, merged