chore: reduce flake in windows-run-app-integration-tests-chrome
cypress-io/cypress pull request #29198
Opened 2024-03-26 18:48 UTC by AtofStryker

- Closes #28942

### Additional details

reduces flake in windows-run-app-integration-tests-chrome by not testing certain tests that are flaky inside the pap-integration cy-in-cy pipeline. Because there are issues recording with `--spec` specified with cy-in-cy, we will not be recording the windows app integration tests. Additionally, this fixes the `windows-test-binary-against-kitchensink-chrome` where `yarn` is not installed on the windows-server executor by making sure yarn is installed first before any action happens when checking out a repo

### Steps to test

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-03-26 19:50 UTC, AtofStryker commented
Took two reruns to get a passing windows pipeline, but it **can** pass

2024-03-28 17:50 UTC, cacieprins requested changes

2024-03-28 17:50 UTC, cacieprins commented on .circleci/workflows.yml
> +              if [[ "$IS_WINDOWS_APP_INTEGRATION_TEST" = true ]]; then
can we detect host os in the specs themselves, to ease tracking down why these tests are skipped in the future?

e.g.,

```
;(isWindowsHostCI ? describe.skip : describe)('top level describe block', function () { })
```

2024-03-28 18:02 UTC, AtofStryker commented on .circleci/workflows.yml
> +              if [[ "$IS_WINDOWS_APP_INTEGRATION_TEST" = true ]]; then
We don't want to skip them on the OS itself though. Only in CI on a specific OS for a given test. They don't flake locally or have issues.

2024-03-29 18:33 UTC, jennifer-shehane approved these changes

2024-04-02 14:14 UTC, cacieprins approved these changes

2024-04-02 14:14 UTC, merged