fix: Allow option values containing quotation marks to be selected
cypress-io/cypress pull request #29214
Opened 2024-03-28 08:41 UTC by davidfurey

- Closes https://github.com/cypress-io/cypress/issues/29213

### Additional details

I believe this issue was introduced by https://github.com/cypress-io/cypress/pull/25016

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-03-28 08:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=29214) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=29214) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=29214) it.</sub>

2024-03-28 14:15 UTC, jennifer-shehane commented
@davidfurey Could you add a changelog entry to this PR? Thanks! https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md

2024-03-28 14:41 UTC, davidfurey commented
> @davidfurey Could you add a changelog entry to this PR? Thanks! https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md

Does this belong in `cli/CHANGELOG.md`?

2024-03-28 14:50 UTC, jennifer-shehane requested changes
@davidfurey For the changelog, this should be added to the `cli/changelog.md` file, not the file within the main changelog. (This isn't used anymore). 


I verified that this fixes the previously failing test. Thanks for the contribution!

### Before
![Screenshot 2024-03-28 at 10 12 23 AM](https://github.com/cypress-io/cypress/assets/1271364/8b31add0-9564-4b0f-b296-65ad75ff7473)

### After
![Screenshot 2024-03-28 at 10 46 07 AM](https://github.com/cypress-io/cypress/assets/1271364/798d6d1a-04f7-4c69-b7ce-40b73f5210c7)

2024-03-28 14:58 UTC, davidfurey commented
Thanks for the speedy review @jennifer-shehane

I've updated the changelog

2024-03-28 18:32 UTC, jennifer-shehane approved these changes

2024-03-28 18:37 UTC, cacieprins approved these changes

2024-03-29 15:04 UTC, samelawrence commented on packages/driver/src/cy/commands/actions/select.ts
> +            if (options.$el.find(`option[value="${value.replace(/"/g, '\\\"')}"]`).length > 1) {
@davidfurey Only if you have the spare cycles - but I'm curious as a RegEx noob what this logic actually does and how it resolves the bug. Would appreciate an explanation (but again, only if you have time). Thank you!

2024-03-29 20:24 UTC, jennifer-shehane commented
Going to merge with these chrome beta tests failing, this is a known issue we're investigating here: https://github.com/cypress-io/cypress/issues/29199

2024-03-29 20:25 UTC, merged