fix: --spec now allows () in filename (https://github.com/cypress-io/cypress/issues/28509)
cypress-io/cypress pull request #29279
Opened 2024-04-05 18:43 UTC by TomasTeixeira2003

- Closes https://github.com/cypress-io/cypress/issues/28509

### Additional details
Even though there was an existing workaround, it is easier to just allow parenthesis.

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-04-09 17:40 UTC, jennifer-shehane commented on cli/CHANGELOG.md
> + - Specs with () in the filename will no longer fail to load and now behave as any other spec. Fixes [#28509](https://github.com/cypress-io/cypress/issues/28509)
```suggestion
**Bugfixes**

 - Specs with () in the filename will no longer fail to load and now behave as any other spec. Fixes [#28509](https://github.com/cypress-io/cypress/issues/28509)
```

2024-04-09 18:02 UTC, TomasTeixeira2003 commented
Is there anything I should do?

2024-04-11 16:58 UTC, jennifer-shehane commented on cli/CHANGELOG.md
> +**Bugfixes**
@TomasTeixeira2003 Seems to be just missing a colon here. 
```suggestion
**Bugfixes:**
```

2024-04-11 17:54 UTC, jennifer-shehane approved these changes
I tested this manually and confirmed that the tests now run when specifying a spec with opening and closing parens. 

#### Before

![Screenshot 2024-04-11 at 1 53 41 PM](https://github.com/cypress-io/cypress/assets/1271364/8000c240-c303-4cd9-9d61-4481efb5c8b5)




#### After

![Screenshot 2024-04-11 at 1 50 03 PM](https://github.com/cypress-io/cypress/assets/1271364/bf69582a-fac2-4310-a68e-b2a90bbceb4c)

2024-04-12 14:55 UTC, AtofStryker reviewed
I don't know if we want to escape parenthesis in all cases in cypress. the `--spec` arg can support glob patterns and parenthesis are a valid glob pattern, but I haven't been able to get glob patterns outside of wildcards to work correctly. @jennifer-shehane do you have more knowledge on what's expected? I mainly going off of https://docs.cypress.io/guides/guides/command-line#cypress-run-spec-lt-spec-gt and testing with the CLI and using https://globster.xyz/

2024-04-12 14:55 UTC, AtofStryker commented on cli/CHANGELOG.md
> + - Specs with () in the filename will no longer fail to load and now behave as any other spec. Fixes [#28509](https://github.com/cypress-io/cypress/issues/28509)
```suggestion
 - Specs with () in the filename will no longer fail to load and now behave as any other spec when run with the `--spec` argument via `cypress run`. Fixes [#28509](https://github.com/cypress-io/cypress/issues/28509)
```

2024-04-12 14:55 UTC, AtofStryker commented on cli/CHANGELOG.md
> + - Specs with () in the filename will no longer fail to load and now behave as any other spec. Fixes [#28509](https://github.com/cypress-io/cypress/issues/28509)
We also need to move this to a new change entry since 13.7.3 was released yesterday

2024-04-12 21:11 UTC, jennifer-shehane commented
@AtofStryker That's a good call out. This bug only happens when you have a closing paren DIRECTLY following an opening paren, so `()` not `(a)`. I don't think that would be valid in any globs, so escaping them back to back should be fine. That's what I'm thinking.

2024-04-15 18:46 UTC, AtofStryker approved these changes

2024-04-16 17:39 UTC, AtofStryker commented
@jennifer-shehane is the failure in CI legit in relation to the glob changes?

2024-04-16 18:20 UTC, jennifer-shehane requested changes
@TomasTeixeira2003 There does appear to be a snapshot that has changed with globs - that is failing here. Can you take a look: https://app.circleci.com/pipelines/github/cypress-io/cypress/60955/workflows/e499d77f-ccf3-4aba-8f7f-ed00d2595ba1/jobs/2535654

![Screenshot 2024-04-16 at 2 19 19 PM](https://github.com/cypress-io/cypress/assets/1271364/f755552b-c7f7-4b86-9a55-3f535ae7df25)

2024-04-17 09:45 UTC, TomasTeixeira2003 commented
I will look into it today

2024-04-22 18:50 UTC, jennifer-shehane commented
@tomasbjerre Any chance to look at this?

2024-04-22 18:55 UTC, tomasbjerre commented
> @tomasbjerre Any chance to look at this?

@jennifer-shehane you probably tagged the wrong Tomas. But I think it looks great :)

2024-04-22 19:51 UTC, jennifer-shehane commented
Sorry @TomasTeixeira2003 Any chance to look at this?

2024-04-22 19:58 UTC, TomasTeixeira2003 commented
I'm sorry, have had a lot of work lately. By tomorrow I will check it.

2024-05-10 11:34 UTC, jennifer-shehane commented
@TomasTeixeira2003 Just pinging to check in on these updates again.

2024-06-11 16:43 UTC, jennifer-shehane commented
@TomasTeixeira2003 Any chance you'll be able to fix this PR? We'll need to close otherwise.

2024-06-11 21:45 UTC, TomasTeixeira2003 commented
I've been working on another feature to rerun failed tests and didn't remember about this. Sorry. By Sunday i will have it working.

2024-06-18 12:31 UTC, TomasTeixeira2003 commented
What is the yarn command to run only the system-tests?

2024-06-18 14:28 UTC, jennifer-shehane commented
@TomasTeixeira2003 The instructions are here: https://github.com/cypress-io/cypress/blob/develop/system-tests/README.md

2024-06-19 17:32 UTC, jennifer-shehane commented
Rerunning the tests here

2024-06-20 19:26 UTC, jennifer-shehane commented
@TomasTeixeira2003 There are some linting errors

2024-06-20 19:28 UTC, TomasTeixeira2003 commented
And the other ones are flaky?

2024-06-24 13:54 UTC, jennifer-shehane requested changes
@TomasTeixeira2003 I'm not seeing this fix working anymore when passing the `--spec` arg. I understand this may be isolated to running Cypress in the local mode, but I can't see the change fixing the issue now with the recent changes. Including a log of what I was running. The test.cy.js file ran, but the test().cy.js file did not run.

![Screenshot 2024-06-24 at 9 53 01 AM](https://github.com/cypress-io/cypress/assets/1271364/3bdc12a8-b9b9-4171-a2c7-3f6557cc7dcc)

2024-07-12 12:44 UTC, TomasTeixeira2003 commented
@jennifer-shehane if I pass the spec file without any blackslash before the parenthesis, bash doesn't even accept the command. But if i do it with the backslash it does work.
![Screenshot from 2024-07-12 13-42-07](https://github.com/user-attachments/assets/85a1e075-6312-4d52-95d4-354a7f8fde60)
![Screenshot from 2024-07-12 13-42-25](https://github.com/user-attachments/assets/90824fc9-476c-486c-9d39-036766a72f23)

2024-07-12 13:58 UTC, jennifer-shehane commented
@TomasTeixeira2003 Are you planning to investigate further?

2024-07-12 14:57 UTC, TomasTeixeira2003 commented
I don't know what more i can do since my machine allows me to run the spec this way.

2024-11-05 15:38 UTC, closed without merging