feat: capture Semaphore PR number
cypress-io/cypress pull request #29314
Opened 2024-04-11 18:52 UTC by estrada9166

- Closes  [CF-1442](https://cypress-io.atlassian.net/browse/CF-1442)

### Additional details

Capture Semaphore PR number to correctly display it on the cloud

### Steps to test

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-04-11 19:06 UTC, jennifer-shehane approved these changes
This env var is documented here: https://docs.semaphoreci.com/ci-cd-environment/environment-variables/#semaphore_git_pr_number

2024-04-11 19:08 UTC, jennifer-shehane commented
@estrada9166 Can you add a changelog entry as outlined in this guide? https://github.com/cypress-io/cypress/blob/develop/guides/writing-the-cypress-changelog.md#writing-guidelines

2024-04-12 13:22 UTC, AtofStryker approved these changes

2024-04-12 14:30 UTC, mschile commented on cli/CHANGELOG.md
>  - Fixed an issue where asserts with custom messages weren't displaying properly. Fixes [#29167](https://github.com/cypress-io/cypress/issues/29167)
```suggestion
## 13.7.4

_Released 4/16/2024 (PENDING)_

**Misc:**

- We now capture the [Semaphore](https://semaphoreci.com/) CI provider's environment variable [`SEMAPHORE_GIT_PR_NUMBER`](https://docs.semaphoreci.com/ci-cd-environment/environment-variables/#semaphore_git_pr_number) to display the linked PR number in the Cloud. Addressed in [#29314](https://github.com/cypress-io/cypress/pull/29314).

## 13.7.3

_Released 4/11/2024_

**Bugfixes:**

- Fixed an issue where asserts with custom messages weren't displaying properly. Fixes [#29167](https://github.com/cypress-io/cypress/issues/29167)
```

2024-04-12 14:31 UTC, mschile approved these changes

2024-04-12 15:08 UTC, AtofStryker commented
I wonder if next version is failing due to my entry of 13.8.0 in #29306r or if the semantic commit job thinks MISC is a feature bump? My guess is the later

2024-04-12 18:04 UTC, jennifer-shehane requested changes
@estrada9166 There's a failure in the server tests. 

![Screenshot 2024-04-12 at 2 03 49 PM](https://github.com/cypress-io/cypress/assets/1271364/e47d0e90-eddf-445b-9a24-3927e8a748dc)

2024-04-12 21:23 UTC, jennifer-shehane commented
@AtofStryker Maybe it's failing because the initial commit was prefixed with `feat:`??

2024-04-12 22:12 UTC, jennifer-shehane commented on cli/CHANGELOG.md
> +## 13.7.4
```suggestion
## 13.8.0
```

2024-04-15 13:57 UTC, jennifer-shehane approved these changes

2024-04-15 14:21 UTC, jennifer-shehane commented on cli/CHANGELOG.md
> +## 13.8.0
```suggestion
## 13.7.4
```

2024-04-15 14:21 UTC, jennifer-shehane approved these changes

2024-04-15 19:24 UTC, merged