fix: Searching by files using digits (Fixes #29034)
cypress-io/cypress pull request #29464
Opened 2024-05-02 19:13 UTC by migueldsol

When trying to search for a file with a long name and digits within using digits cypress was unable to find it. Now it is able to do more complex searches with digits.

- Closes cypress-io/cypress/issues/29034)

### How has the user experience changed?

Before:
![image](https://github.com/cypress-io/cypress/assets/46138945/e3aaff25-97de-4adb-aa4e-e922c098750b)

After:
![image](https://github.com/cypress-io/cypress/assets/46138945/fc5c1d34-0bf5-4c89-9d30-6396967e2c13)

### PR Tasks

- [x] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-05-02 19:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=29464) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=29464) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=29464) it.</sub>

2024-05-03 11:50 UTC, jennifer-shehane requested changes
@migueldsol Thank you so much for contributing and adding tests! Could you please sign our CLA?

2024-05-03 16:00 UTC, jennifer-shehane commented on cli/CHANGELOG.md
> +**Bugfixes**
```suggestion
**Bugfixes:**
```

2024-05-06 18:43 UTC, jennifer-shehane approved these changes
Manually tested and confirmed this fixes the original issue. I also tried searching with a lot of test files and it doesn't seem to negatively impact performance to lower the threshold.

![Screenshot 2024-05-06 at 2 37 49 PM](https://github.com/cypress-io/cypress/assets/1271364/5cd8f06b-107c-4171-aac4-b0c641767163)

2024-05-07 14:16 UTC, mschile approved these changes

2024-05-08 18:59 UTC, merged