Cacie/investigate/deprecate unload event
cypress-io/cypress pull request #29525
Opened 2024-05-15 19:05 UTC by cacieprins

- Closes https://github.com/cypress-io/cypress/issues/29241

### Additional details
In order to prepare for Chrome's removal of the `unload` event, we are migrating to using `pagehide` as a proxy for internal navigation detection. In order to preserve `window:unload`, for now, this event is also triggered on `pagehide`. Because the event emitted on `pagehide` is a superset of `Event`, which is emitted on `unload`, this is not a breaking change.

Future steps to support deprecation of `unload`:
* Add `window:pageshow` and `window:pagehide` events
* Warn when `window:unload` is used

### Steps to test
Existing tests should pass with the flags removed. To test full `unload` removal, uncomment the indicated flags in `packages/server/lib/util/chromium_flags.ts`.

### How has the user experience changed?
`window:unload` may fire both more reliably and at a slightly different point in the page lifecycle timeline. Otherwise, it should not be impacted.

### PR Tasks

- [X] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-05-15 21:22 UTC, jennifer-shehane requested changes
@cacieprins I'm not sure I would even advocate for exposing `page:show` and `page:hide` until users directly ask for it.

Shouldn't we update the `onUpload` callback to `onPageHide`?

2024-05-16 16:15 UTC, jennifer-shehane approved these changes

2024-05-17 19:25 UTC, AtofStryker approved these changes

2024-05-22 15:35 UTC, jennifer-shehane commented on packages/app/src/runner/event-manager.ts
> +    const unloadEvent = this.isBrowser({ family: 'chromium' }) ? 'pagehide' : 'unload'
@cacieprins Can you add a note about why we decided to only target chromium here?

2024-05-22 15:36 UTC, cacieprins commented on packages/app/src/runner/event-manager.ts
> +    const unloadEvent = this.isBrowser({ family: 'chromium' }) ? 'pagehide' : 'unload'
Absolutely

2024-05-22 18:00 UTC, cacieprins commented on packages/app/src/runner/event-manager.ts
> +    const unloadEvent = this.isBrowser({ family: 'chromium' }) ? 'pagehide' : 'unload'
Added in https://github.com/cypress-io/cypress/pull/29525/commits/a64d262b417823c67ee405c6a4ddba052f81649d

2024-05-22 18:06 UTC, merged