Fixed an issue where parent width 0 signal element hidden when it's visible
cypress-io/cypress pull request #29688
Opened 2024-06-17 07:17 UTC by senpl

- Closes https://github.com/cypress-io/cypress/issues/29687
### Additional details
This is necessery to be consistent with what users see in browsers.

### Steps to test
>` <div id="id2">`
>     `<div style="width: 0">`
>       `<p class="big">IN SECTION 2 </p>`    
>     `</div>`
>   `</div>`
    
expect(cy.$$('#id2 >div > p')).to.be.visible
    
cy.get('#id2 >div > p').click()`

### How has the user experience changed?
Some elementst that previously was marked as hidden now are will correctly be makresd as visible

### PR Tasks

- [x] Have tests been added/updated?
- [] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-06-17 08:15 UTC, senpl commented
It was done similar in the past as could be seen in https://github.com/cypress-io/cypress/issues/5974

2024-06-17 08:49 UTC, senpl commented
One test updated because element that was in test in fact was visible, and incorrectly exected to be hidden and not visible.

2024-06-21 17:39 UTC, jennifer-shehane requested changes, later dismissed
@senpl There a failure regarding visibility in the tests.
![Screenshot 2024-06-21 at 1 38 47 PM](https://github.com/cypress-io/cypress/assets/1271364/649f1bfa-2119-4ce0-a076-8693b81405ff)

2024-07-08 10:43 UTC, senpl commented
Now looks like cert errors, so probably something with pipeline.

2024-07-11 12:38 UTC, MikeMcC399 commented on cli/CHANGELOG.md
> +- Fixed an issue where parent width signal element hidden when it's visible [#29687](https://github.com/cypress-io/cypress/issues/29687).
```suggestion
```

This should be removed

2024-07-11 12:39 UTC, MikeMcC399 commented on packages/driver/cypress/e2e/commands/actions/click.cy.js
> +          expect(err.message).to.include('`cy.click()` failed because this element')
Does this error message make sense now?

2024-08-14 15:13 UTC, jennifer-shehane commented
We've decided to prioritize looking into these visibility fixes in Quarter 4 of this year, when we intend to spend time on Cypress 14 release. It will ease any concerns we have around releasing breaking changes with these fixes and also help us plan the proper time to review these. Tracking here: https://github.com/cypress-io/cypress/issues/29925

2024-09-30 15:29 UTC, jennifer-shehane commented
Updated the base branch to go against release/14.0.0

2024-11-13 15:08 UTC, jennifer-shehane commented
I'll leave some notes here on where I left off on this. 

Essentially, there are some circumstances where elements should be considered visible/hidden depending on the state of their child node that is a TEXT node. And Cypress is not taking those situations into account today. 

- If an element has a child text node that contains characters other than whitespace characters, that content makes it visible, unless the element itself is explicitly hidden OR **the text node is hidden by the element, like the element having overflow: hidden and the text node being clipped**. 

^this last part in highlighted text is not currently being accounted for in the logic, which is why there is a failing test. I'm not sure if there are other circumstances that this updated code doesn't account for. Essentially the Cypress logic never seemed to be taking into account TEXT nodes, we've only been accounting for actual element nodes.

2024-12-02 14:54 UTC, AtofStryker approved these changes

2024-12-02 15:37 UTC, merged