misc: add `CYPRESS_SKIP_VERIFY` option to suppress verification
cypress-io/cypress pull request #29836
Opened 2024-07-11 13:37 UTC by joshuajtward

- Closes #22243

### Additional details
The PR adds a flag `CYPRESS_SKIP_VERIFY` to prevent the verification steps from running. These steps are semi-redundant in CI environments, and regularly timeout leading to false negatives in test suites. 

### Steps to test
- Delete the Cypress cache on your machine and run Cypress with `CYPRESS_SKIP_VERIFY=true` in your env
- Confirm that the verification messages are not shown ("Looks like this is your first time running Cypress N.N.N...")

### How has the user experience changed?
If a user opts in they will not get the verification on Cypress startup

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-07-11 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=29836) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=29836) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=29836) it.</sub>

2024-07-24 13:20 UTC, MikeMcC399 requested changes
changelog does not match code

2024-07-24 13:20 UTC, MikeMcC399 commented on cli/CHANGELOG.md
> +- Added `CYPRESS_NO_VERIFY` flag to enable suppression of Cypress verification checks. Addresses [#22243](https://github.com/cypress-io/cypress/issues/22243)
`CYPRESS_NO_VERIFY` is not the name of the environment variable in the code, which is instead `CYPRESS_SKIP_VERIFY`

2024-07-29 11:16 UTC, MikeMcC399 commented
@joshuajtward 

> ### Additional details
> The PR adds a flag `CYPRESS_SKIP_VERIFY` to prevent the verification steps from running. These steps are semi-redundant in CI environments, and regularly timeout leading to false negatives in test suites.

Did you open an issue about timeouts so this could be investigated? I'm seeing some other problems in CI environments with `cypress verify` where the check is uncovering some other issues, so I wonder if it is a good idea to suppress this check.

2024-07-29 11:36 UTC, joshuajtward commented
Hi @MikeMcC399! I have not opened an issue about the timeouts, but there has been a lot of discussion in this repo about this issue already (see for example #6082). It has been partially addressed by adding the ability to set a long timeout, but I would like to add the option to suppress the error so that we can:

1. reduce the false negatives in our CI pipelines
2. see if suppressing it raises any more informative logs or errors

2024-07-29 12:18 UTC, MikeMcC399 commented
@joshuajtward 

- Thank you very much for the reference to issue #6082 ! I didn't know about that. I haven't seen this happen recently with Cypress Docker images, but maybe this depends on the environment?

2024-07-29 13:02 UTC, joshuajtward commented
Yes @MikeMcC399, I'm pretty sure something is going awry with the child tasks which interrogate the installed vs expected binaries, but it's pretty hard to narrow it down because it only happens on around 2% of jobs and usually passes on a re-run. I don't think it's a sensible use of resources to put `DEBUG=cypress:*` in all our CI runs...

For our use cases we don't much care about these integrity checks as we're pretty confident in our CI environment's stability (I think that will be a commonly held sentiment),  our jobs are all running on the same container infrastructure, and using the same caches. We don't want to have to implement a retry shell script or other such workarounds, so using a flag to opt out seems like a better way forward for us.

If our use of this flag helps to highlight a root cause or underlying problem I will be happy to raise it as an issue in this repo!

2024-07-29 13:26 UTC, MikeMcC399 commented
@joshuajtward 

Thanks again for your explanation and background! Which CI provider are you using and which package manager (npm, Yarn or pnpm)?

2024-07-29 13:46 UTC, joshuajtward commented
We're using GitHub Actions with a mix of Linux, Windows, and MacOS, and a mix of `yarn ` and `npm` across a number of repos

2024-08-02 11:38 UTC, MikeMcC399 commented
The new environment variable would need to be documented in the table https://docs.cypress.io/guides/references/advanced-installation#Environment-variables so this would mean that a release branch for `13.14.0` (or later if delayed) would need to be created in the docs repo to prepare for release.

![image](https://github.com/user-attachments/assets/18c207fd-cea4-449c-8e98-5ccc3ab578b3)

2024-08-02 11:39 UTC, MikeMcC399 requested changes
The documentation aspect needs to be covered.

2024-08-05 10:05 UTC, joshuajtward commented
@MikeMcC399 docs PR is here: https://github.com/cypress-io/cypress-documentation/pull/5889

2024-08-08 09:32 UTC, joshuajtward commented
@MikeMcC399 @jennifer-shehane is there anything else I can help with to get this moving?

2024-08-08 09:44 UTC, MikeMcC399 commented
@joshuajtward 

> is there anything else I can help with to get this moving?

Yes, you will need to resolve the conflicts in the branch. Unfortunately this can happen as changes are committed to the `develop` branch.

This is mentioned in the submitter's guide https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#pull-requests

2024-08-08 10:24 UTC, joshuajtward commented
@MikeMcC399 sorry I hadn't seen there were more conflicts. I have updated that now, is there anything else?

2024-08-08 11:51 UTC, MikeMcC399 commented
@joshuajtward 

> sorry I hadn't seen there were more conflicts. I have updated that now

👍🏻 

> is there anything else?

CI has one failing test, however that may be CircleCI flake. I expect that @jennifer-shehane will be able to provide more concrete feedback as the Cypress.io is more familiar with the individual tests than I am. They can also re-run individual tests. 

Since I'm only an external contributor, I don't have write privileges to CircleCI, to the repo or to the PR approval process. I can just provide comments.

2024-08-08 16:51 UTC, jennifer-shehane commented
@joshuajtward Just awaiting @AtofStryker review at this point

2024-08-09 13:31 UTC, AtofStryker requested changes

2024-08-09 13:31 UTC, AtofStryker commented on cli/lib/tasks/verify.js
> +    skipVerify: util.getEnv('CYPRESS_SKIP_VERIFY') || 'false',
Can we get this to just work with booleans?
```suggestion
    skipVerify: util.getEnv('CYPRESS_SKIP_VERIFY') === 'true',
```

2024-08-09 13:31 UTC, AtofStryker commented on cli/lib/tasks/verify.js
> +  if (options.skipVerify === 'true') {
```suggestion
  if (options.skipVerify) {
```

2024-08-09 13:31 UTC, AtofStryker commented on cli/lib/tasks/verify.js
> +    return Promise.resolve()
```suggestion
   debug('skipping verification of the Cypress app')
    return Promise.resolve()
```

2024-08-09 13:49 UTC, joshuajtward commented
Good shout @AtofStryker, that reads more nicely - I've updated it now

2024-08-09 14:25 UTC, jennifer-shehane commented
@joshuajtward There's a linting error 
![Screenshot 2024-08-09 at 10 25 04 AM](https://github.com/user-attachments/assets/600ce5d2-50d2-4b82-a8bd-a5fd62697b75)

2024-08-12 08:49 UTC, joshuajtward commented
@AtofStryker I have fixed this up and it should be ready for a re-review, thanks!

2024-08-15 13:54 UTC, AtofStryker commented
@joshuajtward Thank you for getting the changes addressed! One last question on my end. I created a binary of your code changes on https://github.com/cypress-io/cypress/commit/add6f09401f27489d2808ba4bc87096fd2dd42bf. Are you able to download the binary from the link and verify the changes work as expected?

2024-08-15 14:29 UTC, joshuajtward commented
> @joshuajtward Thank you for getting the changes addressed! One last question on my end. I created a binary of your code changes on [add6f09](https://github.com/cypress-io/cypress/commit/add6f09401f27489d2808ba4bc87096fd2dd42bf). Are you able to download the binary from the link and verify the changes work as expected?

Hi @AtofStryker, I have installed that binary and run a few tests, it appears to work as expected 

Without the flag it works as normal: 
<img width="600" alt="No flag" src="https://github.com/user-attachments/assets/5b98dd53-0590-4709-a75f-bb9849be68dc">

With the flag the verify steps are skipped:
<img width="600" alt="With flag" src="https://github.com/user-attachments/assets/421de4f2-7c55-4e91-bc91-e4b81ae3e2d7">

And if the binary is missing then it fails with an illustrative error: 
<img width="600" alt="No binary" src="https://github.com/user-attachments/assets/b9b95b22-3165-4640-bd1c-83d77eecc446">

Please let me know if there's any other testing you would like me to do!

2024-08-15 15:02 UTC, MikeMcC399 commented
@joshuajtward 

I notice that you're running quite an old version of Yarn (`v1.18.0`) from 2019. Yarn `v1.22.22` is the current stable version (see https://classic.yarnpkg.com/en/docs/install).

- Edit: See related https://github.com/cypress-io/cypress/pull/30048, but probably not an issue for this PR.

2024-08-15 15:55 UTC, AtofStryker approved these changes

2024-08-16 09:35 UTC, joshuajtward commented
@jennifer-shehane are we all set to merge? 🙏

2024-08-16 16:30 UTC, cacieprins approved these changes

2024-08-16 16:45 UTC, merged