chore(webkit): update playwright-webkit to 1.45.3
cypress-io/cypress pull request #29955
Opened 2024-08-01 06:32 UTC by MikeMcC399

- Closes https://github.com/cypress-io/cypress/issues/29954

### Additional details

Updates WebKit testing from browser version `16.0` to `17.4`.

`playwright-webkit` is updated from `1.24.2` to `1.45.3`

### Steps to test

TBD

The following does not test WebKit:

```shell
yarn test
```

### How has the user experience changed?

Affects internal CircleCI tests only.

### PR Tasks

- [ ] Have tests been added/updated?
- [na] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [na] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-08-01 07:32 UTC, MikeMcC399 commented
WebKit is not yet tested in CI. It needs approval in CircleCI for the remaining tests to execute including:

- `system-tests-webkit`
- `driver-integration-tests-webkit`

2024-08-01 17:53 UTC, jennifer-shehane requested changes
@MikeMcC399 I suspect something changed with cookies in this version perhaps. Or how we're interacting with it. Failures: https://app.circleci.com/pipelines/github/cypress-io/cypress/63152/workflows/e49a5390-7dc4-432e-abce-391b205c080b/jobs/2615104

![Screenshot 2024-08-01 at 1 52 37 PM](https://github.com/user-attachments/assets/9370f680-326b-4cbd-8649-f84d42637a23)
![Screenshot 2024-08-01 at 1 52 43 PM](https://github.com/user-attachments/assets/bd3e891b-3782-4170-87ba-9d91d576f330)
![Screenshot 2024-08-01 at 1 52 52 PM](https://github.com/user-attachments/assets/53754c60-d53a-4133-8e12-6788270fbf94)

2024-08-02 09:31 UTC, MikeMcC399 commented
@jennifer-shehane 

I only pre-tested using `cypress-example-kitchensink` so I wasn't prepared for the driver integration tests failing.

I will go back to earlier versions of webkit and test with them first. I'm going to close this PR in the meantime.

2024-08-02 09:31 UTC, closed without merging

2024-08-02 12:12 UTC, MikeMcC399 commented
The incompatibility started much earlier with `playwright-webkit@1.37.1`.