feat(breaking): 14.0.0 Release
cypress-io/cypress pull request #30305
Opened 2024-09-27 13:25 UTC by jennifer-shehane

BREAKING CHANGE: 14.0.0 release

# ⚠️ DO NOT SQUASH AND MERGE. USE A MERGE COMMIT

- close https://github.com/cypress-io/cypress/issues/29925

## Details

2024-11-22 14:08 UTC, MikeMcC399 commented
- When the `release/14.0.0` branch is rebased on `develop` I'll submit a documentation update to [CONTRIBUTING > Requirements](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#requirements) as a follow-on to PR #30633

2025-01-07 20:39 UTC, AtofStryker requested changes
semantic commits for npm release are not for npm packages. in the process of fixing this but until fix DO NOT MERGE this PR

2025-01-07 22:11 UTC, AtofStryker approved these changes
package versions are now correct and will be published correctly on merge commit into develop 
<img width="305" alt="Screenshot 2025-01-07 at 5 10 14 PM" src="https://github.com/user-attachments/assets/3699daa9-6604-4510-ab9d-e6784d4479d1" />

2025-01-07 22:18 UTC, mschile approved these changes

2025-01-07 23:26 UTC, merged