WIP Issue 2957
cypress-io/cypress pull request #3030
Opened 2018-12-28 16:45 UTC by Bkucera

fix #2956

2019-02-04 16:49 UTC, Bkucera commented
WIP going back on for dblclick and rightclick changes

2019-05-24 06:13 UTC, jennifer-shehane commented
Changed the base to `develop`, is this still WIP since there's a checkbox not checked?

2019-05-24 10:55 UTC, Bkucera commented
It's in a reviewable state, but I do still have one task to do

2019-08-09 04:26 UTC, brian-mann commented
I see some cleanup but overall this is excellent.

2019-08-14 22:38 UTC, brian-mann submitted a review, later dismissed
- these are mostly notes, but adding them now. some of which i will internally handle - so don't jump into these yet.
- i'm currently going through each of the issues and finding the tests and running them to understand and gauge the solutions we implemented.
- also i'm looking for our collective notes on the algorithm changes so we can surface those and them not get lost
- we talked internally about using `while` loops vs tail-call optimized recursions. no change needed but some research needs to be done to see which pattern we should employ. there are places that we traverse the dom using recursion which may not be tail-call optimized and could blow out the stack. however research suggests recursion is more performant that while loops. probably is easier to convert those recursive calls to `while` loops, but ideally we could look into this further and then decide on a general strategy of how/when to use one vs the other.

2019-08-14 22:42 UTC, brian-mann commented on packages/driver/test/cypress/integration/commands/actions/click_spec.js
> +      cy.getAll('$btn', 'pointerdown mousedown pointerup mouseup click').each(shouldBeCalled)
need to think about a potentially better way to do this. not necessarily bad or wrong just need to discuss

2019-08-15 16:53 UTC, Bkucera commented on packages/driver/src/cy/mouse.js
> +const $ = require('jquery')
we have not. there is a plugin but it has strange bugs sometimes where it moves all your requires to the bottom of the file

2019-08-15 17:11 UTC, Bkucera commented on packages/driver/src/cy/mouse.js
> +        pressure: 0.5,
yes, added comment to clarify

2019-08-15 17:11 UTC, Bkucera commented on packages/driver/src/cy/mouse.js
> +  const evt = new constructor(evtName, _.extend({}, evtOptions, { bubbles, cancelable }))
:+1:

2019-08-15 17:12 UTC, Bkucera commented on packages/driver/src/cy/mouse.js
> +  const constructor = el.ownerDocument.defaultView.MouseEvent
:+1:

2019-08-15 17:12 UTC, Bkucera commented on packages/driver/src/cy/mouse.js
> +      // mouse._mouseMoveEvents(el, { x, y })
:+1:

2019-08-15 17:12 UTC, Bkucera commented on packages/driver/src/cy/mouse.js
> +const debug = require('debug')('driver:mouse')
:+1:

2019-08-15 17:12 UTC, Bkucera commented on packages/driver/src/cy/keyboard.js
> +    _.pickBy(modifiers, (val) => {
:+1:

2019-09-25 17:57 UTC, brian-mann commented on packages/driver/test/cypress/integration/commands/actions/click_spec.js
> +      cy.getAll('$btn', 'pointerdown mousedown pointerup mouseup click').each(shouldBeCalled)
This was an old comment, disregard

2019-09-25 18:01 UTC, brian-mann requested changes
Can you write out the event firing algorithm including how we handle things like when the element moves in response to an event? 

It will take some legwork, and it may possibly be better diagramed as a flowchart (rather than nested bullet points) - i don't necessarily care, i just want it documented somewhere. I would prefer if its documented in the code itself so it doesn't become stale - and new engineers will be able to pick it up. I'd also accept a link to an external document in the code if necessary. We can also use flowchart.js to accomplish both - where the algorithm is written in code in notes but a physical flowchart asset is generated from the code. That way it never gets stale.

as you described they are incoherent. We need to build institutional knowledge around these algorithms and make them very transparent. Jennifer created one awhile ago for the visibility algorithm - she'll link you here in a sec.

2019-09-25 18:02 UTC, jennifer-shehane commented
maybe flowchart in code similar visibility algo 

![nC0TrUIVMOLJObyg-F2826 copy](https://user-images.githubusercontent.com/1271364/65627302-195e9800-df9d-11e9-8657-960f39ff91e5.png)

2019-09-25 18:03 UTC, Bkucera commented
@jennifer-shehane ok, do we have the flowchart-as-code stuff documented anywhere

2019-09-30 02:54 UTC, brian-mann requested changes
update test for iframe coordinates to actually have coords
- fromAutWindow
- remove the $elements.getFromDocCoords(x, y, win)
- write a proper test for the iframe coordinates specifically for drawing the red hitbox
- remove docCoords

2019-10-11 22:43 UTC, merged