Support webcam/WebRTC testing
cypress-io/cypress pull request #3060
Opened 2019-01-04 06:30 UTC by jennifer-shehane

- close #2704 

## Todo

- [ ] Add `--use-fake-ui-for-media-stream` to Cypress default flags
- [ ] Add `--use-fake-device-for-media-stream` to Cypress default flags
- [ ] Write webcam tests
- [ ] Test that a user pushing arg `--use-file-for-fake-video-capture` to the browser launch API works properly.

2019-01-19 23:04 UTC, brian-mann requested changes
- `packages/driver/test/cypress/videos/e2e/webcam_spec.js.mp4` was committed accidentally and needs to be removed from `git`
- we should likely add `cypress/videos` to `.gitignore` to prevent this from happening in the future
- @jennifer-shehane 	where are we going to document that we now automatically set fake devices for webrtc / webcam testing? I can imagine users being pretty confused seeing the fake media streams / videos that chromium generates

2019-01-22 10:22 UTC, jennifer-shehane commented
Yeah, good question. I'm not sure I have an answer at the moment, but I've added it to this issue for now https://github.com/cypress-io/cypress-documentation/issues/1330

2019-01-23 06:51 UTC, brian-mann approved these changes

2019-01-23 06:52 UTC, merged

2020-08-24 05:35 UTC, jennifer-shehane commented
@odahcam There's an example here: https://on.cypress.io/browser-launch-api#Use-fake-video-for-webcam-testing