misc: update browser icons
cypress-io/cypress pull request #30790
Opened 2024-12-19 16:04 UTC by mschile

- Closes n/a

### Additional details

* Updated to use the @cypress-design system browser icons

### Steps to test

Verify the icons are correct.

### How has the user experience changed?

Browser selection:
<img width="1454" alt="Screenshot 2024-12-19 at 9 19 02 AM" src="https://github.com/user-attachments/assets/72a77b8f-709a-498d-ab57-0bf59e63ed30" />

Open mode header and dropdown:
<img width="1840" alt="Screenshot 2024-12-19 at 9 19 38 AM" src="https://github.com/user-attachments/assets/1ab59007-0108-4010-8273-958af320cc58" />

Debug:
<img width="1288" alt="Screenshot 2024-12-19 at 9 20 33 AM" src="https://github.com/user-attachments/assets/caa4d472-9f0e-4bc7-894d-b292a725ba66" />

Run mode header:
<img width="1666" alt="Screenshot 2024-12-19 at 9 22 39 AM" src="https://github.com/user-attachments/assets/c0044d44-5303-439f-9700-40fce93129f6" />

Automation missing:
<img width="1330" alt="Screenshot 2024-12-20 at 8 33 04 AM" src="https://github.com/user-attachments/assets/1d953527-ab93-4704-9edb-184aa65a05a9" />

### PR Tasks

- [x] Have tests been added/updated?
- [n/a] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [n/a] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?

2024-12-19 16:45 UTC, cacieprins requested changes

2024-12-19 16:45 UTC, cacieprins commented on packages/app/src/runner/SpecRunnerHeaderOpenMode.vue
> +          <component
This conditional logic is repeated in several places - can it be abstracted to a new component?

2024-12-19 16:54 UTC, mschile commented on packages/app/src/runner/SpecRunnerHeaderOpenMode.vue
> +          <component
Are you referring to this conditional logic?
```
:is="allBrowsersIcons[selectedBrowser.displayName?.toLowerCase()] || allBrowsersIcons.generic"
```

That was already there before just under the `src` prop:

```
:src="allBrowsersIcons[selectedBrowser.displayName] || allBrowsersIcons.generic"
```

2024-12-20 16:40 UTC, cacieprins approved these changes

2025-01-07 15:46 UTC, merged