fix flakey timers_spec
cypress-io/cypress pull request #3227
Opened 2019-01-25 19:46 UTC by Bkucera

upping the timeout here seems to fix it

2019-01-25 20:43 UTC, Bkucera commented
ironically another flaky test just failed

2019-01-25 20:58 UTC, brian-mann requested changes
if the timers aren't fired while the page is transition that's a bigger problem and one that we need to investigate and try to fix for real... 

i can pair with you on it

2019-01-25 22:20 UTC, Bkucera commented
> if the timers aren't fired while the page is transition that's a bigger problem and one that we need to investigate and try to fix for real...
> 
> i can pair with you on it

if this moves the chains, can it go ahead and go in?

2019-01-29 19:27 UTC, brian-mann approved these changes

2019-01-29 19:28 UTC, merged