Update coffeescript to 2.4.1
cypress-io/cypress pull request #4141
Opened 2019-05-06 10:04 UTC by szb512

Updates coffeescript to 2.4.1.
Also, there is NO removing the bot commits, no matter what. They just react again if you do.

2019-05-06 10:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=4141) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=4141) before we can accept your contribution.<br/>**1** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: szb512<br/>:x: ImgBotApp<br/>:x: whitesource-bolt-for-github[bot]<br/>:x: code-dog-auto-merge[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=4141) it.</sub>

2019-05-06 10:05 UTC, szb512 commented
@CLAassistant I'm pretty sure the bots don't know what to do with it.

2019-05-06 10:23 UTC, jennifer-shehane requested changes
@szb512 I'm sorry. We won't be able to merge this PR with the bot commits. They are making commits that are not wanted in our cypress project - including this `.whitesource` config file https://github.com/cypress-io/cypress/pull/4141/commits/1d24c788ec51fbeee3b150ba8ce1a59a38eecad5 and updating the images on our project. https://github.com/cypress-io/cypress/pull/4141/commits/717fbc7a343f6387f76d795768910aee03e4054d

2019-05-07 06:21 UTC, jennifer-shehane commented
closing in favor of https://github.com/cypress-io/cypress/pull/4147

2019-05-07 06:21 UTC, closed without merging