allow contains to pick chained subject as priority element
cypress-io/cypress pull request #4326
Opened 2019-05-28 20:45 UTC by Bkucera

fix #1887

2019-05-29 12:18 UTC, lukeapage commented
I can see how the new behaviour is preferred.. but this is a big breaking change for us.
We've used contains as a kind of pseudo-selector e.g.

```
cy.get('.tst-section-a')
   .contains('Cancel')
   .click();
```

If you didn't want to change the target couldn't you write `.should('contain', 'Cancel')` ?

2019-05-29 14:34 UTC, Bkucera commented
@lukeapage as long as the element is not a priority element, nothing would change,
is `.tst-section-a` a `link, a, or button` ?

2019-05-29 14:40 UTC, lukeapage commented
No it’s not a button, it’s a section. And the button only contains the text

2019-05-29 15:29 UTC, lukeapage commented
Oh, wow ok.. that is okay. It’s pretty non straight forward, hard to predict behavior.

2019-05-29 17:28 UTC, Bkucera commented
@lukeapage agreed.

2019-07-26 18:43 UTC, brian-mann requested changes

2019-07-26 18:43 UTC, brian-mann commented on packages/driver/test/cypress/integration/commands/querying_spec.coffee
> +      console.log($btn)
console log :-/

2019-07-26 18:43 UTC, brian-mann commented on packages/driver/src/cy/commands/querying.coffee
> +            elArray = [].slice.call($el)
$el.get()

2019-07-26 18:43 UTC, brian-mann commented on packages/driver/test/cypress/integration/commands/querying_spec.coffee
> +      span = cy.$$("#click-me a")
no longer a `span`

why modify this test?

2020-07-13 08:34 UTC, jennifer-shehane commented
Unfortunately we have to close this due to inactivity. Please reopen if there is work to be done addressing this again.

2020-07-13 08:34 UTC, closed without merging