Revert "Add option to ignore special character sequences to cy.type (…
cypress-io/cypress pull request #4761
Opened 2019-07-18 19:12 UTC by Bkucera

Adding the option to ignore special char sequences it not necessary

This can be easily done in, and does not reduce complexity for the user compared to userland solution
you can simply have a function that escapes your string:

```js
const rawTypeString = (str) => str.replace(/{/g, '{{}')
cy.type(rawTypeString('{hello}'))
```

As bonus, its even more readable, since I get told I'm passing a `rawTypeString` before I even know the string

2019-07-23 16:45 UTC, brian-mann commented
After discussion, we'll go ahead and keep this option but...

- [ ] rename it to `parseSpecialCharSequences`
- [ ] update the `cy.type()` error message that indicates an invalid sequence and point the user to this option
- [ ] update the docs for `cy.type()`

2019-07-23 20:37 UTC, brian-mann requested changes
- [x] Can we say explicitly to "pass the option: { ... }" in the footer?
- [x] Can we add a link to the `cy.type` docs in the footer too? https://on.cypress.io/type

2019-07-24 04:00 UTC, jennifer-shehane commented
I feel a little bit like....am I missing something? 

The default for `parseSpecialCharacterSequences` should be `true` and you set `false` to turn off parsing and type the literal characters. Yah?

I reversed all of the logic and booleans in this commit https://github.com/cypress-io/cypress/pull/4761/commits/159f1d09ef0c04488db3683376ecf25d7a9ad416

2019-07-24 15:35 UTC, Bkucera commented
@jennifer-shehane nice. good catch

2019-07-24 19:50 UTC, brian-mann commented on packages/driver/test/cypress/integration/commands/actions/type_spec.js
> +          expect(err.message).to.eq(`Special character sequence: '{bar}' is not recognized. Available sequences are: ${allChars}
Approving this PR but this would be a good place to introduce template tags using the `common-tags` module.

2019-07-24 19:50 UTC, brian-mann approved these changes

2019-07-24 19:50 UTC, merged