set top.onerror same as autWindow.onerror
cypress-io/cypress pull request #5249
Opened 2019-09-30 17:36 UTC by Bkucera

- fix #987  

### Description of change

### How to use the feature

### How the design has changed

### Notes

### Pre-merge Tasks

- [ ] Have tests been added/updated for the changes in this PR?
- [ ] Has a PR to [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation) been submitted to document any user-facing changes? 
- [ ] Have the [type definitions](cli/types/index.d.ts) been updated with any user-facing API changes?
- [ ] Has the [cypress.schema.json](cli/schema/cypress.schema.json) been updated with any new configuration options?
- [ ] Has the original issue been tagged with a release in ZenHub?

2019-09-30 17:41 UTC, bahmutov commented on packages/driver/test/cypress/integration/e2e/uncaught_errors_spec.coffee
> +    # cy.visit('https://www.nba.com/membership/user/login')
haha, nice comment

2019-09-30 17:43 UTC, Bkucera commented on packages/driver/test/cypress/integration/e2e/uncaught_errors_spec.coffee
> +    # cy.visit('https://www.nba.com/membership/user/login')
ok ok.

2019-10-30 21:43 UTC, brian-mann requested changes

2019-10-30 21:43 UTC, brian-mann commented on packages/driver/src/cy/commands/xhr.coffee
> +      throw err
leave a note here indicating why this is necessary

2019-10-30 21:43 UTC, brian-mann commented on packages/driver/src/cypress/cy.coffee
> +  top.onerror = ->
assign this and reuse it on the `get`, as opposed to pulling it off of `getOwnPropertyDescriptor` again

2019-10-30 21:43 UTC, brian-mann commented on packages/driver/test/cypress/integration/commands/xhr_spec.coffee
> +
make this local to the function and use `cy.stub()`

2019-10-30 22:17 UTC, brian-mann submitted a review, later dismissed

2019-10-30 23:17 UTC, merged