WIP: merge all events in one table, cleanup keyboard events
cypress-io/cypress pull request #5606
Opened 2019-11-05 00:05 UTC by Bkucera

- log all events for mouse commands in one table, instead of three
- keep keyboard events separate, but redesign the output and col names
fix #5553 

### User facing changelog
- improve user experience around inspecting events fired during click and type commands #5553  

### Additional details

### How has the user experience changed?
we now show all mouse related events in one table in console, in order:
[screenshot]

we have more detailed information in the `type` command in the console:
[screenshot]

### PR Tasks
- [ ] add screenshots of table
- [ ] add comment linking issue

- [x] Have tests been added/updated?
- [NA] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [NA] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [NA] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

2019-11-05 19:29 UTC, jennifer-shehane commented
This is much clearer - and addresses my earlier concerns of not being able to tell the order in which events were occuring.

2019-11-05 20:20 UTC, Bkucera commented
I should probably re-order the columns, and rename "Event.Target" to "Target Element"

2019-11-06 16:53 UTC, brian-mann requested changes
**Mouse Events**
- index
- Event Type
- Target Element
- Prevented Default 
  - null
  - true
- Stopped Propagation
  - null
  - true
- Active Modifiers
  - null
  - string

**Keyboard Events**
- index
- Typed
- Target Element
- Events Fired
- Details 
  - { code: '...', which: '... }
- Prevented Default 
  - null
  - true
- Active Modifiers
  - null
  - string

- Use `{cmd}` and `{option}` when literally typed in the `Typed` column.
- `keydown, keyup, keyup, keyup` on the final type needs to be split up and each independent keyboard event needs its own entry

2019-11-07 00:10 UTC, brian-mann approved these changes

2019-11-07 00:10 UTC, brian-mann commented
These changes look perfect

2019-11-07 00:10 UTC, merged