desktop-gui: Add toggle buttons to root specs to expand/collapse all their subfolders
cypress-io/cypress pull request #6541
Opened 2020-02-24 08:57 UTC by martinsik

- Closes #6282

### User facing changelog

Add "collapse all" and "expand all" buttons to UI to collapse/expand all subfolders for a root spec.

### How has the user experience changed?

This PR adds two buttons to UI next to each root spec name. Clicking "Collapse all" will only collapse subfolders and will keep the root spec expanded.

![issue-6282-add-expand-collapse-buttons](https://user-images.githubusercontent.com/238765/75138805-6af58500-56eb-11ea-9841-83cb11bdece0.png)

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

2020-02-24 08:57 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=6541) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=6541) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=6541) it.</sub>

2020-02-24 10:08 UTC, martinsik commented
I'm not sure why there are two failing tests in `commands/xhr_spec.coffee` and `commands/angular_spec.coffee`.

2020-02-24 16:53 UTC, jennifer-shehane requested changes
I think the `collapse all | expand all` links should be removed if there are no folders to expand/collapse, otherwise if just seems like the links don't do anything and is more clutter for users that don't have a larger test suite. 

![](http://g.recordit.co/3LDY0zsVTP.gif)

2020-02-24 16:53 UTC, jennifer-shehane commented on packages/desktop-gui/cypress/integration/specs_list_spec.js
> +      it('collapses all children folders', () => {
This is an interesting way to test this 👍

2020-02-26 06:25 UTC, jennifer-shehane submitted a review, later dismissed
@martinsik Some linting errors need fixing. You can run `yarn lint-fix` in the root of the project to automatically fix these before committing.

2020-02-26 09:22 UTC, martinsik commented
@jennifer-shehane I tried running `yarn lint-fix` but it went through the whole project.

The lint check is now throwing:
```
/root/cypress/packages/desktop-gui/src/specs/specs-store.js
  146:16  error  'child' is defined but never used  no-unused-vars
```
But that's  on this line which is weird.
https://github.com/cypress-io/cypress/pull/6541/files#diff-2bf56b7e7d242f95dffdd2309a9f2948R145-R152

It might be related to this: https://github.com/eslint/eslint/issues/12165

2020-02-27 14:15 UTC, chrisbreiding submitted a review, later dismissed

2020-02-28 04:21 UTC, jennifer-shehane commented
Final cosmetic change after asking team - wanted to move the 'collapse/expand' buttons to the right to clean up the UI clutter some.

2020-02-28 04:21 UTC, jennifer-shehane approved these changes

2020-02-28 07:01 UTC, merged

2023-05-16 20:56 UTC, gunslingor commented
What's the status of this? We have thousands of cy files in many folders, sure would be nice to collapse so we can see structure. An alternative would be to turn it into a table with path field and all column filter.

2023-05-23 10:23 UTC, martinsik commented
@gunslingor This PR was merged a while ago into the old UI. I guess it was rewritten from scratch or redesigned heavily, so even though this PR was merged it's probably not relevant any more.