[WIP]: cypress cache list should print last accessed date
cypress-io/cypress pull request #6627
Opened 2020-03-03 16:33 UTC by bahmutov

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

2020-03-06 08:59 UTC, jennifer-shehane requested changes
I thought the original scope of this was to list the directory the cache is located in and also the file size of the binary. Has that been removed from scope or is this just partially addressing #6404? (which is fine if it is!)

2020-03-06 08:59 UTC, jennifer-shehane commented on cli/lib/tasks/cache.js
> +const a = chalk.red
These const names are more confusing than helpful. If I saw `a('text')`, I would have zero idea what `a` means or what it is doing. If the functionality is just coloring text red, something like `red('text')` makes more sense. Clarity > brevity.

2020-03-06 08:59 UTC, jennifer-shehane commented on cli/lib/tasks/cache.js
> +      head: [a('version'), a('last used')],
I would probably opt for white (I think this is default) or grey text here. The red does not look good visually 😅. Every other use case of `chalk.red` that I found also denotes errors/warnings/failures so seems inappropriate functionality-wise.

2020-03-06 08:59 UTC, jennifer-shehane commented on cli/lib/tasks/cache.js
> +      const lastUsed = x.accessed ? u(x.accessed) : 'unknown'
Again, what is `x` here? This variable name makes this method harder to read. Suggest calling it `binary` if it is a singular of `binaries. Clarity > brevity.

2020-03-06 16:31 UTC, bahmutov commented
@jennifer-shehane thanks for good code review, appreciate it. I have renamed everything for clarity.

For the folder sizes - I left a note in the PR description. Turns out Node's recursive folder size is _much_ slower than native "du -h" on Mac for example. So I think let's start with this table, since it already introduces better UI and a feature (last access timestamp) plus CLI visual artifacts. Then we can reconsider how to implement fast folder size across platforms. I am thinking a separate NPM tool that tries to use native tools with Node's fallback

2020-03-09 05:51 UTC, jennifer-shehane approved these changes
Looks good - tested manually as well. I would still like the path to each cache printed because I have to run `cypress cache path` directly after to see where these are. 

@bahmutov I would suggest opening a new issue for the directory location and size if you intend to close the original issue from this PR. 

<img width="236" alt="Screen Shot 2020-03-09 at 12 19 16 PM" src="https://user-images.githubusercontent.com/1271364/76186340-6dce9a80-6200-11ea-8ad3-586502357837.png">

2020-03-09 13:27 UTC, merged