Partial config options
cypress-io/cypress pull request #7239
Opened 2020-05-06 15:20 UTC by bahmutov

- Closes #7238

### User facing changelog

We export `Cypress.ConfigOptions` as a partial of the full options interface, thus you can write realistic TypeScript code right away

```ts
// provide only some config options
const runConfig: Cypress.ConfigOptions = {
  baseUrl: 'http://localhost:8080',
  env: {
    login: false
  },
}
cypress.run({ config: runConfig })
```

### Additional details

- removed duplicate TS code between `npm-api ts` file and `index.d.ts`
- moved the full config options into a different interface name, and added
```
type ConfigOptions = Partial<AllConfigOptions>
```

### How has the user experience changed?

Using Cypress NPM module API correctly got easier

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [x] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?

2020-05-06 15:20 UTC, bahmutov commented
I think this is a better solution than https://github.com/cypress-io/cypress/pull/6696

2020-05-06 16:01 UTC, flotwig requested changes
so the reason for this, over #6696, is that it allows us to express the shape of the config *after* config.coffee has resolved the full configuration object, right?

2020-05-06 16:36 UTC, bahmutov commented on cli/types/index.d.ts
> +  interface AllConfigOptions {
I will use `ResolvedConfigOptions` - just note that in our server package the resolved config has options AND for each has `from: ... value: ...` structure

2020-05-06 19:48 UTC, bahmutov commented
unrelated flake e2e test

2020-05-07 14:04 UTC, flotwig requested changes

2020-05-07 14:04 UTC, flotwig commented on cli/types/index.d.ts
> +   */
The way that this is phrased implies that users cannot supply all config options, maybe something like this:

```suggestion
  /**
   * All configuration items are optional.
   */
```

2020-05-07 14:11 UTC, flotwig approved these changes

2020-05-07 14:39 UTC, merged