Enable object as parameter for css, prop, and attr assertions
cypress-io/cypress pull request #7356
Opened 2020-05-14 22:49 UTC by panzarino

- Closes #7353

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](cli/types/index.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](cli/schema/cypress.schema.json)?

2020-05-20 06:20 UTC, jennifer-shehane requested changes
### 1. Assertion display differences

The display of the assertions differs when you use Cypress `.should()` assertions versus the standard expect. When using `.should()` it always only displays the last assertion in the Command Log. You should be able to write tests around the number/value of logs displayed in this situation.

My code against `<div style="display: block; position: absolute;">div</div>`

```js
it('visit', () => {
  cy.visit('index.html')
  cy.get('div').then(($div) => {
    expect($div).to.have.css({ display: 'block' })
    expect($div).to.have.css({ position: 'absolute' })
    expect($div).to.have.css({ display: 'block', position: 'absolute' })
  })
})

it('visit', () => {
  cy.visit('index.html')
  cy.get('div').should('have.css', { display: 'block' })
  cy.get('div').should('have.css', { position: 'absolute' })
  cy.get('div').should('have.css', { display: 'block', position: 'absolute' })
})
```

<img width="656" alt="Screen Shot 2020-05-20 at 12 36 54 PM" src="https://user-images.githubusercontent.com/1271364/82410910-be7f3100-9a96-11ea-9f04-344700d8abb0.png">

### 2. Empty object behavior

The assertions always pass when passed an empty Object. I dunno, maybe this is ok? Seems a bit weird though. The assertions don't display in the UI at all, so it seems like a noop.

```js
it('visit', () => {
  cy.visit('index.html')
  cy.get('div').then(($div) => {
    expect($div).to.have.css({})
  })
})

it('visit', () => {
  cy.visit('index.html')
  cy.get('div').should('have.css', {})
})
```

<img width="254" alt="Screen Shot 2020-05-20 at 12 41 42 PM" src="https://user-images.githubusercontent.com/1271364/82411194-4f560c80-9a97-11ea-9b43-5b6cb0601e19.png">

2020-05-20 06:20 UTC, jennifer-shehane commented on packages/driver/test/cypress/integration/commands/assertions_spec.js
> +        this.$div = $('<div foo=\'bar\' fizz=\'buzz\'>foo</div>')
You can use double quotes here - these escaped single quote `\'` are just an artifact of converting from CoffeeScript. I'd prefer double quotes.

2020-05-27 17:59 UTC, kuceb requested changes

2020-05-27 17:59 UTC, Bkucera commented on cli/types/index.d.ts
> +/// <reference path="./cypress-expect.d.ts" />
```suggestion
/// <reference path="./cypress-expect.d.ts" />

```

2020-06-02 16:09 UTC, panzarino commented
@chrisbreiding and I decided that its probably best to not make these changes as they are fairly inconsistent with other methods and the existing Chai api, plus there would have to be a unique workaround to fix the logging issues. For now, I'm just going to submit another PR that causes a test to fail when passed an object rather than blindly succeed.

2020-06-11 17:34 UTC, brian-mann commented
I am not convinced this should not be implemented... I don't believe there are logging issues with this.

2020-06-12 05:01 UTC, jennifer-shehane commented
Perhaps this illustrates the issue more clearly. When using `.should()`, only the last assertion in the object is logged as opposed to logging all assertions within a normal expect.

@brian-mann Can you explain more clearly why you consider this not an issue?

<img width="1027" alt="Screen Shot 2020-06-12 at 11 27 49 AM" src="https://user-images.githubusercontent.com/1271364/84466624-cc902e00-ac9f-11ea-8c24-dc9b4c662153.png">

Also, my second point about asserting on an empty object hasn't been responded to - whether this is desired behavior or not.

2020-06-12 23:40 UTC, brian-mann commented
With the object literal pattern - its really a "subset" kind of assertion, which means that the key's of the object are what you're asserting against.

If given a blank object then I believe this would give you a specific error telling you to provide **some** kind of assertion otherwise there's nothing specifically we can assert about.

2021-05-18 13:20 UTC, jennifer-shehane commented
Closing due to inactivity. We can reopen a new PR if we feel the work is something we want to prioritize in the future.

2021-05-18 13:20 UTC, closed without merging