Fix back to tests button
cypress-io/cypress pull request #7425
Opened 2020-05-20 00:20 UTC by panzarino

- Closes #5948

### User facing changelog

Fix malfunctioning back to tests button in runner

### How has the user experience changed?

The back button will now focus the test list window instead of doing nothing.

### PR Tasks

It seems like tests have already been added to check for this behavior yet non ddo successfully. I am not sure how to make a test that correctly checks this functionality.

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub?

2020-05-20 04:55 UTC, jennifer-shehane requested changes
I'm not seeing any change in behavior here from the original bug. 🤔 Did you push all your code changes? What OS do you use btw so I'm aware of what OS you're typically fixing changes in?

![](http://g.recordit.co/EgjktZVJfe.gif)

2020-05-20 21:23 UTC, panzarino commented
@jennifer-shehane there is a "force" option (`{steal: true}`) which might fix this issue in newer/older versions of macOS. I'll go ahead and push that option, since there is no reason not to have it.

For reference I am using macOS Mojave.

2020-05-26 09:21 UTC, jennifer-shehane requested changes
So, yay, this fixes the focus in Chrome, Firefox, and Edge. 

But now the focus tests button does not work in Electron. 😅

2020-05-27 03:04 UTC, jennifer-shehane approved these changes

2020-05-27 03:05 UTC, merged