Add UTM parameters to Dashboard login buttons
cypress-io/cypress pull request #7639
Opened 2020-06-09 16:26 UTC by panzarino

- Closes #7638 

### Additional details

Adds tracking to dashboard login links

Contingent on https://github.com/cypress-io/cypress-services/pull/2685 being merged

### PR Tasks

- [x] Have tests been added/updated?
- [x] Has the original issue been tagged with a release in ZenHub?

2020-06-10 05:31 UTC, jennifer-shehane requested changes
We should probably add a test here, since we're not technically testing that this link in the project setup modal is correctly routing to the dashboard route. 

https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/integration/setup_project_modal_spec.js#L522:L522

2020-06-15 16:10 UTC, panzarino commented
@jennifer-shehane Turns out I was putting the UTM parameters on the wrong links, I've updated it now.

I'm fairly unfamiliar as to how to write a full e2e test that will check for full functionality here as these changes span both `desktop-gui` and `server`. I'm also unsure of whether Google Analytics will actually pick up on the UTM parameters when sent through this method, so essentially there needs to be additional testing all around.

2020-06-16 13:27 UTC, flotwig requested changes
> I'm fairly unfamiliar as to how to write a full e2e test that will check for full functionality here as these changes span both `desktop-gui` and `server`. I'm also unsure of whether Google Analytics will actually pick up on the UTM parameters when sent through this method, so essentially there needs to be additional testing all around.

@panzarino I don't think you need a full e2e test for this. Probably just a Cypress test in `desktop-gui` that verifies that the UTM code is sent to the IPC channel, and then a unit test in the `server` `auth_spec` that verifies that the expected URL is generated. You could also add a test in `events_spec` that the IPC event calls `beginAuth` properly.

2020-06-16 13:27 UTC, flotwig commented on packages/server/lib/gui/auth.js
> +const start = (onMessage, utm_code) => {
Keep it camelCase until it absolutely doesn't have to be:

```suggestion
const start = (onMessage, utmCode) => {
```

2020-06-16 13:27 UTC, flotwig commented on packages/server/lib/gui/auth.js
> +  utm = utm_code
```suggestion
  utm = utmCode
```

2020-06-16 18:02 UTC, flotwig approved these changes
nice!

2020-06-19 19:51 UTC, jennifer-shehane approved these changes

2020-06-19 20:53 UTC, merged