Fix issue where command is never fully ended and following assertions are displayed incorrectly
cypress-io/cypress pull request #7734
Opened 2020-06-17 04:06 UTC by panzarino

- Closes #7731

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](../cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](../cli/schema/cypress.schema.json)?

2020-06-17 07:28 UTC, jennifer-shehane requested changes
I can't recreate this issue in 4.8.0 or the `develop` branch. Are you sure this wasn't introduced in https://github.com/cypress-io/cypress/pull/7356 itself? Can you provide the repro example for the original issue?

I tried using `before` hooks, tried moving the `before` hook around the suites...

Below is what I'm seeing in `develop` branch.

```js
context('closing commands', () => {
  beforeEach(function () {
  })

  it('properly closes commands', () => {
    expect(true).to.be.true
  })
})
```

<img width="581" alt="Screen Shot 2020-06-17 at 1 55 10 PM" src="https://user-images.githubusercontent.com/1271364/84868125-3777a580-b0a2-11ea-98fd-3394063b998d.png">


```js
context('closing commands', () => {
  beforeEach(function () {
    cy.visit('index.html')
  })

  it('properly closes commands', () => {
    expect(true).to.be.true
  })
})
```
<img width="583" alt="Screen Shot 2020-06-17 at 1 52 52 PM" src="https://user-images.githubusercontent.com/1271364/84868064-2038b800-b0a2-11ea-83f2-8a0116a8417d.png">

2020-06-17 08:00 UTC, panzarino commented
@jennifer-shehane  I may have described the actual cause of the issue incorrectly. I realized that this issue was only occuring when I put an `.only` on the test. I've moved it to be the first test in `cy_spec.js` which seemed to accurately test for the error, and now if run without the changes, the test should fail.

2020-06-17 08:43 UTC, jennifer-shehane approved these changes
Looks good 👍

2020-06-17 15:29 UTC, merged

2020-06-17 18:04 UTC, Saibamen commented
What this green dash means?

2020-06-22 08:15 UTC, jennifer-shehane commented
@Saibamen It is used to indicate that the command is a 'child' command, that there is a parent above it.