Remove offscreen mode from new windows Fixes #7930
cypress-io/cypress pull request #8351
Opened 2020-08-19 20:10 UTC by lukeapage

Offscreen rendering:
https://www.electronjs.org/docs/tutorial/offscreen-rendering

passes every frame to a 'paint' event, which cypress does not listen too.

In electron 8.2.1 it was fixed and switched back on, so when cypress upgraded from 8.2.0 to 8.2.3, it caused a performance regression.

The performance regression on slow computers is about 8x slower. On fast computers you don't see a difference - I expect the multi-process nature of electron and cypress means that more cores mitigate the extra cpu needed.

The option was introduced here, 3 years ago:
https://github.com/cypress-io/cypress/commit/5bde862d9122697dbab48156770950d4b58096f1

My guess is it was a mistake. @brian-mann do you remember?

- Closes 

### User facing changelog

### Additional details

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2020-08-19 20:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=8351) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=8351) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=8351) it.</sub>

2020-08-20 07:30 UTC, jennifer-shehane commented
Would be nice to have a test for this. Performance tests are really challenging though. 🤔

2020-08-20 09:29 UTC, lukeapage commented
I hoped I could see a marked difference in your test runs, but perhaps down to whatever hardware used, there’s no big time difference there. Given the difficulty of performance tests and that this is removing bad code from 3 years ago I’d ask that be done as a separate feature.

2020-08-20 17:12 UTC, bahmutov commented
Question: the test run videos are still captured though?

2020-08-20 17:24 UTC, lukeapage commented
how do I test videos? I can verify windows but it would be good to double check Mac and Linux too - this Pr has no link to a dashboard like other prs I see.

2020-08-21 08:17 UTC, lukeapage commented
I can confirm that videos still work on windows.

2020-08-24 07:47 UTC, jennifer-shehane commented
Video recording seems fine on Mac

2020-08-24 13:40 UTC, jennifer-shehane requested changes
I got some notes from @brian-mann on why this option was originally added:

- hiding would leak elements like select drop downs to the screen 
- we used to only be able to record and control the FPS this way
- we used to control the screen size and DPI consistently at 1x DPI
- performance
- did not use the GPU to render which prevented display issues

Hopefully he can comment with some more detailed thoughts, but we may want to look into removing this more closely. I remember the dropdown issue anyway and could look at that.

2020-08-24 14:21 UTC, brian-mann commented
Adding to my notes that @jennifer-shehane listed...

With offscreen we get the monitor DPI controlled for and normalized everywhere. If we take off offscreen we have to use the RDP protocol to normalize it for all users. In our e2e tests we manually do that, but that will not be available to other users, so we'll have to do it for them.

2020-08-24 14:29 UTC, flotwig commented
In addition to the reasons that @jennifer-shehane mentioned, Cypress /was/ using the `paint` event to capture video of the running tests, so for a time, there *was* a good reason to use offscreen rendering. We switched to using Chrome DevTools Protocol for recording in 4.2.0, so that is why you are able to disable offscreen rendering and still have video recording work.

The issue where dropdowns and other elements would appear on screen during `--headless` on macOS, without `offscreen: true`, was like, 8 major versions of Electron ago (1.x? 2.0.18?), so it's possible that it's been fixed now that we're on Electron 9. Someone with a Mac can confirm.

As long as we can ensure that issue is fixed, and that 1x DPI is still enforced somehow with `offscreen: false`, LGTM. 

---

Here is the code @brian-mann is referring to that forces 1x DPI in our e2e tests: https://github.com/cypress-io/cypress/blob/ee60b0138346312e0847729c2457ae2876067c19/packages/server/test/support/fixtures/projects/e2e/cypress/support/index.js#L4-L25

We don't force the 1x override in Electron or Firefox though, so I'm not sure what that says for how important this is...

2020-08-24 14:43 UTC, lukeapage commented
Remember also that electron 8 - 8.2.0 had offscreen disabled so the option did nothing:
https://www.electronjs.org/blog/electron-8-0
I believe that cypress used this range in 4.3.0-4.4.1
So I’d expect bugs reported for these cypress versions that were resolved with 4.5.0

2020-08-24 14:46 UTC, lukeapage commented
What do you want to do? Make it an option or spend more time testing it?

2020-08-24 15:17 UTC, brian-mann commented
@jennifer-shehane and I paired earlier on this and she's testing out the various scenarios. Once we can confirm everything behaves the same and there are no gaps we can merge this in.

2020-08-27 10:48 UTC, jennifer-shehane commented
I don't see the weird `<select>` rendering issue that we used to when running Electron.

I'm also not seeing the behavior of the video change based on the DPI of my screen.

2020-08-27 16:34 UTC, merged