Fix driver move to start/end, add tests
cypress-io/cypress pull request #8466
Opened 2020-09-01 17:14 UTC by Bkucera

cont. of #7970 to move it to an internal branch
 
- fix #8465
- Closes #5502 

### User facing changelog
Bug fix: fix issue with `cy.type` `{moveToStart}`/`{moveToEnd}` special characters moving cursor on the current line instead of the entire text editable when typing in a `contentEditable` element.

### Additional details
- thanks to @sainthkh for adding tests for moveToStart/End and surfacing this bug.

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2020-09-01 17:17 UTC, Bkucera commented
@sainthkh let me know what you think, used a simple selection.collapse for chrome, had to add more logic for firefox to fix the selection to prevent newline issue

2020-09-02 06:12 UTC, sainthkh requested changes
LGTM. There are only 2 minor changes.

2020-09-02 06:12 UTC, sainthkh commented on packages/driver/src/dom/selection.ts
>    return false
We don't need this line. Every `return` above returns `undefined` but it's `false` here. And `moveSelectionToEnd` and `moveSelectionToStart` doesn't need a return value.

2020-09-02 06:12 UTC, sainthkh commented on packages/driver/src/dom/selection.ts
> +      // but its innerText will be '\n' (maybe find a more efficient measure)
```suggestion
      // in firefox, when an empty contenteditable is a single <br> element, or <div><br/></div>
      // its innerText will be '\n' (maybe find a more efficient measure)
```

`my be` might be a typo of `might be` or `may be`

2020-09-02 20:16 UTC, merged