fix(perf): use JS to animate command progress bars
cypress-io/cypress pull request #8522
Opened 2020-09-08 15:34 UTC by flotwig

- Closes #8012

### User facing changelog

- Fixed a performance issue which led to CPU bottlenecking during Cypress runs.

### Additional details

- `<Progress>` element added in #7646 has a performance issue, the CSS animation on `width` causes repetitive Layout updates which leads to a serious performance regression: 
	* without Progress element:  
		 ![Pasted image](https://i.imgur.com/oQHns1t.png)
	* with Progress element:  
         ![Pasted image](https://i.imgur.com/wapT8wX.png)
	* performance issues were noted in the original PR but it was merged anyways
- i attempted to change the nature of the CSS animation to fix it, but none of these worked:
	- removing float:left
	- setting max-widths and preventing overflow
	- animating linear-gradient to do a progress bar (not supported, since linear-gradient is technically a background-image, which is not animatable)
- so, ended up re-implementing the animation using JS requestAnimationFrame, which seems to avoid the performance issue:
	Commit SHA | Time to finish https://github.com/nphillipsworth/cypress-test-tiny/
	--- | ---
	public 4.8.0 build | 142066ms
	3f3e860fc | 172671ms
	f883590ef | 174939ms
	f305f8b10 | 153007ms
	dc075618b (from #7646) | 302152ms
	dc075618b without Progress element | 157521ms
	dc075618b using requestAnimationFrame (this PR) | **182470ms**
	6c6b23f88 | 323244ms
	4fb3f0b32 | 417179ms
	public 4.9.0 build | 310599ms
- animating using JS feels bad, but i think it's either this, or revert #7646. open to suggestions

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2020-09-08 17:45 UTC, brian-mann commented
Ironically @jennifer-shehane brought this up during the original implementation because she had broad concerns over the perf implications. I know we caught one other problem before we released it, but I think we should investigate or think about ways to automatically detect self imposed performance regressions since we've had quite a few of them in the UI layer recently.

2020-09-08 18:20 UTC, Bkucera requested changes
progress bar is now going the other direction :smile:

2020-09-08 18:22 UTC, flotwig commented
Oops, can probably update `transform-origin` to fix that. I do like it this way too

2020-09-08 18:28 UTC, Bkucera approved these changes
status bar direction flip is a much needed change :+1:

2020-09-08 20:35 UTC, merged

2020-09-09 00:08 UTC, brian-mann commented
Don't flip the direction please 🙈

2020-09-09 00:09 UTC, flotwig commented
oh boy, it's the spinner debacle all over again!

i'll open a PR tomorrow to swap it back

2020-09-09 00:17 UTC, bahmutov commented
Make it go diagonally across

Sent from my iPhone

> On Sep 8, 2020, at 20:09, Zach Bloomquist <notifications@github.com> wrote:
> 
> ﻿
> oh boy, it's the spinner debacle all over again!
> 
> i'll open a PR tomorrow to swap it back
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.