Allow empty redirects - Closes #8544
cypress-io/cypress pull request #8550
Opened 2020-09-10 19:43 UTC by fras2560

- Closes #8544

### User facing changelog
Empty redirects will be allowed

### PR Tasks

- [N ] Have tests been added/updated?
- [] Has the original issue been tagged with a release in ZenHub?
- [] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)?
- [N] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2020-09-10 19:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=8550) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=8550) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=8550) it.</sub>

2020-09-10 19:48 UTC, flotwig requested changes
Hey @fras2560, thanks for the PR!

This will need tests to ensure there is not a regression at some point in the future.

A good place for the tests would be this file: https://github.com/cypress-io/cypress/blob/fcd1d35d5d4db7a0f451ffc4848e8ef3323516af/packages/server/test/integration/http_requests_spec.js

You can run this suite by doing `yarn test-integration http_requests` from within `packages/server`.

Let me know if you have any questions or anything I can help with.

2020-09-10 20:45 UTC, fras2560 commented
@flotwig okay I will attempt at writing one. I am assuming for the context be added under 'POST'?

Also I am not really sure what url is http://localhost:2020/__cypress/xhrs/users/1? Like is this a mock server? If so there one the makes for redirect?

2020-09-10 20:59 UTC, flotwig commented
> @flotwig okay I will attempt at writing one. I am assuming for the context be added under 'POST'?

Sounds like a good place.

> Also I am not really sure what url is http://localhost:2020/__cypress/xhrs/users/1? Like is this a mock server? If so there one the makes for redirect?

Yeah, check out our usage of `nock`, it is what we use to mock the HTTP upstreams for this spec. You can find docs here: https://github.com/nock/nock

2020-09-11 16:40 UTC, fras2560 commented
@flotwig  am I even on the right track with the unit test? I am struggling to follow some of the code.

2020-09-11 16:53 UTC, flotwig commented
@fras2560 Hmm, I'm trying to understand the problem you reported in #8544.

So the issue is:

1. You `cy.visit({ method: 'POST', url: 'http://some-url' })`
2. `http://some-url` serves a `3xx` redirect to `http://another-url`
3. `http://another-url` serves a document without a `Content-Type`?

If so, then I'm afraid this is actually expected behavior for Cypress - Cypress requires the final destination of the `cy.visit` to be an HTML document, or have the `Content-Type: text/html`.

If you set `Content-Type` properly on `http://another-url`, then Cypress appears to work as expected as of 5.1.0.

If I'm understanding correctly, this PR and the issue aren't needed. Your test should be updated to either use `cy.request` (which is designed to load non-HTML resources and can use `POST`) or your server should be updated to serve the proper `Content-Type` on the final destination URL.

2020-09-11 17:15 UTC, fras2560 commented
@flotwig I created a cypress-tiny-test to help explain it

https://github.com/fras2560/cypress-test-tiny

`app.post('/redirect', (req, res) => {
  res.writeHead(302, {
    'Location': '/whatsup'
  });
  res.end();
})

app.get('/whatsup', (req, res) => {
  res.send("<p>Whats up</p>")
})
`

`  it('Visit - a 302 redirect with an empty body', () => {
    cy.visit({url: '/redirect', method: 'POST'});
  })`
It fails on the redirect response - http://some-url and never gets to http://another-url.

2020-09-11 18:28 UTC, flotwig commented
Ahhh, ok, now I see the bug. Thank you for the repro. Let me look at this for a little bit, `cy.visit` is supposed to handle this already actually...

2020-09-11 18:30 UTC, fras2560 commented
@flotwig it seems it only applies with POST visit and not a GET visit. If I change my test to GET it works fine. Hopefully that helps narrow down the bug.

2020-09-11 19:15 UTC, flotwig commented
bah, @fras2560 could you re-push your changes to your repo? i mistakenly pushed my `develop` over your `develop` and now GitHub is giving me permission denied to update your branch :roll_eyes: 

or, give me write access to `fras2560/develop`

2020-09-11 19:44 UTC, flotwig commented
Thanks @fras2560 ! I updated the PR. It turns out our HTTP request library already supports this behavior, under the `followAllRedirects` flag:

![image](https://user-images.githubusercontent.com/1151760/92966459-95b7e880-f445-11ea-8a56-d302588fb756.png)

So, I enabled that, and added tests for all the known 3xx redirect types, and it appears to fix the problem. Thanks again for identifying the bug and coming up with the initial PR.

2020-09-11 20:01 UTC, fras2560 commented
@flotwig thanks for doing this. It seems some of the checks are failing is that an issue? 

Also once this is checked in any idea before it will be part of a release?

2020-09-11 20:02 UTC, flotwig commented
Looks unrelated to this PR. Next release should be early next week.

2020-09-11 20:15 UTC, merged