fix: use net-stubbing.d.ts in triple-slash reference
cypress-io/cypress pull request #8603
Opened 2020-09-17 13:04 UTC by unstubbable

### User facing changelog

fix compiler error with custom rootDir that was caused by net-stubbing.ts reference

### Additional details

When referencing a .ts file (vs. .d.ts) file, an import of cypress in a TypeScript project with a custom rootDir will lead to this error:

```
error TS6059: File
'<snip>/foo/node_modules/cypress/types/net-stubbing.ts' is not under
'rootDir' '<snip>foo/bar'. 'rootDir' is expected to contain all source
files.
```

Using a .d.ts file is in line with the other references in index.d.ts and fixes this compiler error.

### How has the user experience changed?

no compiler error when importing cypress in a TypeScript project with a custom rootDir

2020-09-17 13:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=8603) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=8603) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=8603) it.</sub>

2020-09-18 14:14 UTC, flotwig commented
Hmm, I think the reason I left it as a .ts file is because as a .d.ts I ran into issues using `export`, and I wasn't sure how to convert the exported types that are used internally into ambient declarations. I didn't think it would cause issues though.

But as you can see, `lint-types` is failing, complaining about it being invalid to use `export` in a `d.ts` file. Do you know how to solve this?

2020-09-21 09:18 UTC, unstubbable commented
In general [modules should be preferred over namespaces](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html), so I get your intend. But with the current setup of how Cypress publishes its types and how they are [supposed to be consumed](https://docs.cypress.io/guides/tooling/typescript-support.html), i.e. using the global `Cypress` namespace, I don't think mixing this with types that are [supposed to be imported from a module](https://github.com/cypress-io/cypress/blob/develop/cli/scripts/post-install.js#L73) is a feasible approach. Therefore I would suggest to move the types and interfaces from `packages/net-stubbing/lib/external-types.ts` into the `Cypress` namespace that is already used for the other use cases, e.g. `Cypress.PluginConfig`.

2020-09-21 09:45 UTC, unstubbable commented
FYI: As a work-around I moved our integration test files from `packages/itests/cypress` (which also [includes the `tsconfig.json` file](https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json)) to `packages/itests`, thus avoiding the `net-stubbing.ts is not under 'rootDir'` error. But this probably won't be a solution for projects that don't have their integration tests in a dedicated package inside of a mono repo.

2020-10-02 08:54 UTC, jennifer-shehane requested changes
@unstubbable There's an error in our types linting: https://app.circleci.com/pipelines/github/cypress-io/cypress/13374/workflows/a4807e66-7877-468b-8ab1-fe030061b0b8/jobs/448446

```
Error: /root/cypress/cli/types/net-stubbing.d.ts:14:3
ERROR: 14:3  strict-export-declare-modifiers  'export' keyword is redundant here because all declarations in this module are exported automatically. If you have a good reason to export some declarations and not others, add 'export {}' to the module to shut off automatic exporting. See: https://github.com/Microsoft/dtslint/blob/master/docs/strict-export-declare-modifiers.md
ERROR: 19:3  strict-export-declare-modifiers  'export' keyword is redundant here because all declarations in this module are exported automatically. If you have a good reason to export some declarations and not others, add 'export {}' to the module to shut off automatic exporting. See: https://github.com/Microsoft/dtslint/blob/master/docs/strict-export-declare-modifiers.md
ERROR: 40:3  strict-export-declare-modifiers  'export' keyword is redundant here because all declarations in this module are exported automatically. If you have a good reason to export some declarations and not others, add 'export {}' to the module to shut off automatic exporting. See: https://github.com/Microsoft/dtslint/blob/master/docs/strict-export-declare-modifiers.md
ERROR: 49:3  strict-export-declare-modifiers  'export' keyword is redundant here because all declarations in this module are exported automatically. If you have a good reason to export some declarations and not others, add 'export {}' to the module to shut off automatic exporting. See: https://github.com/Microsoft/dtslint/blob/master/docs/strict-export-declare-modifiers.md

    at /root/cypress/node_modules/dtslint/bin/index.js:190:19
    at Generator.next (<anonymous>)
    at fulfilled (/root/cypress/node_modules/dtslint/bin/index.js:5:58)
```

2020-10-02 09:47 UTC, unstubbable commented
@jennifer-shehane I know, see previous comments please. I will close this PR since I think this should be solved differently as expressed in https://github.com/cypress-io/cypress/pull/8603#issuecomment-695998863.

2020-10-02 09:47 UTC, closed without merging