fix: Don't add / when baseUrl has param(s).
cypress-io/cypress pull request #8630
Opened 2020-09-21 07:52 UTC by sainthkh

- Closes #2101

### User facing changelog

/ is not added when `baseUrl` has param(s)

### Additional details

- Why was this change necessary? Some people defines `baseUrl` with params. But Cypress adds `/` by default. 
- What is affected by this change? => N/A
- Any implementation details to explain? => N/A

### How has the user experience changed?

N/A

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [N/A] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [N/A] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [N/A] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2020-09-22 05:52 UTC, sainthkh commented
Flaky failures.

2020-09-25 18:34 UTC, flotwig approved these changes

2020-09-28 14:14 UTC, flotwig requested changes
@sainthkh can you take a look at the failing location_spec? the merge seems to have broken something, probably from the other PR against `$Location`

2020-09-29 09:16 UTC, sainthkh commented
It happened because `new URL(to, from).toString()` forcefully appends `/` right after the URL before `?`. Fixed it.

2020-09-29 13:17 UTC, flotwig approved these changes
nice

2020-10-02 05:34 UTC, merged

2020-11-30 04:11 UTC, jennifer-shehane commented
This PR introduced this issue https://github.com/cypress-io/cypress/issues/9360