Update types for Cypress.Chainable.task to allow for parameterizing the task return type
cypress-io/cypress pull request #8753
Opened 2020-10-06 00:15 UTC by kevin-wittmer

Closes #7136

### User facing changelog

Update types for `Cypress.Chainable.task` to allow for parameterizing the task return type.

### Additional details

Previously, the return type of `task` would be determined by the previous subject's type. In this example:
```
cy.task("task").then((val) => ...);
```
`val` is typed as `undefined` with no way to change it besides explicitly casting `val` inside the lambda function. This change supports specifying the type of `val` in a first-class way:
```
// val now has type MyType
cy.task<MyType>("task").then((val) => ...);
```

### How has the user experience changed?

User experience has not changed -- developer experience is better!

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2020-10-06 00:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=8753) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=8753) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=8753) it.</sub>

2020-10-06 13:04 UTC, bahmutov requested changes
Can you please a few type tests for this?

2020-10-08 00:53 UTC, kevin-wittmer commented
@bahmutov Tests have been added. Not sure what type of coverage is expected here or if my approach makes sense, so feedback is welcome. Thanks!

2020-10-09 14:07 UTC, bahmutov requested changes
Kevin, could you take a look at these tests failing on CI

https://app.circleci.com/pipelines/github/cypress-io/cypress/13882/workflows/47534892-805e-4efe-b4e0-48e1b93eed78/jobs/473420

```
Installing to /root/.dts/typescript-installs/3.5...
Installed!

Installing to /root/.dts/typescript-installs/next...
Installed!
Error: /root/cypress/cli/types/tests/cypress-tests.ts:608:3
ERROR: 608:3  expect   TypeScript@next expected type to be:
  Cypress.Chainable<unknown>
got:
  Chainable<unknown>
ERROR: 613:3  expect   TypeScript@next expected type to be:
  Cypress.Chainable<number>
got:
  Chainable<number>
ERROR: 617:2  eofline  file should end with a newline

    at /root/cypress/node_modules/dtslint/bin/index.js:190:19
```

2020-10-13 01:24 UTC, kevin-wittmer commented
@bahmutov The tests relevant to this PR have been fixed. It doesn't look like the integration test failures are related to this PR, so not sure what's going on there.

2020-10-13 12:01 UTC, bahmutov commented on cli/types/tests/cypress-tests.ts
> +  cy.task<number>('foo').then((val) => {
and what if the user does not specify a type? Can you add a test
```
cy.task('foo') // $ExpectType Chainable<unknown>
```

2020-10-13 14:49 UTC, bahmutov commented on cli/types/tests/cypress-tests.ts
> +  cy.task<number>('foo').then((val) => {
Is the default value yielded from `cy.task` `undefined` or `null`?

2020-10-13 15:10 UTC, kevin-wittmer commented
@bahmutov Right, but in your example I would expect the TS code to look like
```
cy.task<null>('foo')
```
because the caller knows that `foo`'s return type is `null`. What I'm getting at is **what do we want the default type to be when the caller does not provide a type?** In concrete terms,
```
cy.task('foo').then(x => ...)
```
what is the type of `x`? Without this PR, the current state is the type of `x` is `undefined`. In the current state of this PR, depending on the version of TS, `x` is either `unknown` or `{}`. I think either `unknown` or `undefined` would be a fine default type. Which do you prefer?

2020-10-13 15:19 UTC, bahmutov commented
I vote for unknown 

Sent from my iPhone

> On Oct 13, 2020, at 11:10, Kevin Wittmer <notifications@github.com> wrote:
> 
> ﻿
> @bahmutov Right, but in your example I would expect the TS code to look like
> 
> cy.task<null>('foo')
> because the caller knows that foo's return type is null. What I'm getting at is what do we want the default type to be when the caller does not provide a type? In concrete terms,
> 
> cy.task('foo').then(x => ...)
> what is the type of x? Without this PR, the current state is the type of x is undefined. In the current state of this PR, depending on the version of TS, x is either unknown or {}. I think either unknown or undefined would be a fine default type. Which do you prefer?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-10-27 14:48 UTC, jennifer-shehane commented
@kevin-wittmer Do you still have time to address the changes requested in this PR?

2020-10-27 17:31 UTC, kevin-wittmer commented
@jennifer-shehane Thanks for the reminder -- I'll address the remaining feedback today.

2020-10-27 22:41 UTC, kevin-wittmer commented
@jennifer-shehane @bahmutov Feedback has been addressed.

2020-10-28 15:43 UTC, flotwig approved these changes

2020-10-28 15:56 UTC, merged