Fix scrollIntoView to work when scrolling is on the body
cypress-io/cypress pull request #8784
Opened 2020-10-08 07:25 UTC by lukeapage

### User facing changelog

Fixes scrollIntoView to work when the body element is scrollable and when `overflow: overlay` is used.

### Additional details

When you have a body element that is scrollable, both cypress and jquery.scrollTo assume it is the window that is scrollable and try to scroll that. Since that is not scrollable, nothing happens and the command is useless.

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Fix jquery.scrollTo and upgrade it

2020-10-08 07:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=8784) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=8784) before we can accept your contribution.<br/><hr/>**Luke Page** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=8784) it.</sub>

2020-10-08 07:54 UTC, lukeapage commented
jquery.scrollTo PR - https://github.com/flesler/jquery.scrollTo/pull/181

2020-10-09 10:11 UTC, jennifer-shehane commented
Is this meant to fix this issue? https://github.com/cypress-io/cypress/issues/991

2020-10-09 10:41 UTC, jennifer-shehane requested changes
We won't be able to merge this with the breaking test, so we'll need to wait for the scrollTo fix to be merged or implement our own scrolling. 

This is not high priority however as overlay scroll is not maintained.

2020-10-09 11:24 UTC, lukeapage commented
It fixes 2 bugs -
1. Overlay - #991 
2. Scrolling on the body rather than the window / no bug raised and this requires a fix in jquery.scrollTo

Yes definitely don’t merge this until jquery.scrollTo is fixed

2020-11-04 20:12 UTC, lukeapage commented
Giving up on this since the change to the underlying dependency is unlikely to be merged.

2020-11-04 20:12 UTC, closed without merging