Set status property on the module API resolved object
cypress-io/cypress pull request #8799
Opened 2020-10-09 02:19 UTC by bahmutov

- Closes #8798

### User facing changelog

`cypress.run().then(results)` now has `status` property in the `results` object matching our CLI types ("failed" or "finished")

### PR Tasks

- [x] Have tests been added/updated?
- [ ] Has the original issue been tagged with a release in ZenHub?

2020-10-09 19:06 UTC, flotwig requested changes
types need to be updated for this, also, what is the utility of this? where's the `passed` status?

2020-10-09 19:18 UTC, bahmutov commented
@flotwig check the linked issue - I have added the _type_ for the results objects before, but forgot to actually add the property. This fixes the omission

2020-10-09 19:25 UTC, flotwig commented
icic, what is the utility of this property? where's the `passed` status?

2020-10-09 19:31 UTC, bahmutov commented
Not sure what you mean - there is not `passed` property. There is only `status: failed` or `status: finished`. Failed runs that completely failed to start have `status: failed`. Otherwise, even if tests failed, we return `status: finished`. Then TypeScript and JS code can determine correctly the status of the `cypress.run` result with TS complaining

2020-10-13 06:19 UTC, jennifer-shehane commented
Yah, I think the use of the word 'failed' is the confusion here, since we use that for tests - I was also trying to figure out where 'passed' status is.

2020-10-16 15:26 UTC, flotwig approved these changes
seems to make sense, LGTM

2020-10-19 08:50 UTC, merged