feat(react): allow modifying the final preprocessorOptions for cra-v3
cypress-io/cypress pull request #9738
Opened 2020-12-11 21:39 UTC by stoically

Inspired by Storybook's [webpackFinal](https://storybook.js.org/docs/react/configure/webpack) option, this allows passing a third parameter to the `react-scripts` function. If `preprocessorOptionsFinal` as function is given, it'll get called with the final `preprocessorOptions` to give user space a chance to modify things, like adjusting the webpack config, e.g.

```js
    reactScripts(on, config, {
        preprocessorOptionsFinal(preprocessorOptions) {
            preprocessorOptions.webpackOptions.devtool = false
            return preprocessorOptions
        },
    })
```

I suppose this would need some tests and/or documentation, just wanted to check if this might be a proper way to approach it

- Closes #9701 

### User facing changelog

- Allows to modify the `preprocessorOptions` from the `cra-v3` react plugin before they get passed into `webpackPreprocessor`

### Additional details

Transferred from https://github.com/cypress-io/cypress-react-unit-test/pull/557

### How has the user experience changed?

### PR Tasks

- [ ] Have tests been added/updated?
- [ ] Has the original issue or this PR been tagged with a release in ZenHub? 
- [ ] Has a PR for user-facing changes been opened in [`cypress-documentation`](https://github.com/cypress-io/cypress-documentation)? 
- [ ] Have API changes been updated in the [`type definitions`](https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts)?
- [ ] Have new configuration options been added to the [`cypress.schema.json`](https://github.com/cypress-io/cypress/blob/develop/cli/schema/cypress.schema.json)?

2020-12-11 21:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cypress-io/cypress?pullRequest=9738) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cypress-io/cypress?pullRequest=9738) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cypress-io/cypress?pullRequest=9738) it.</sub>

2020-12-14 07:30 UTC, lmiller1990 reviewed
I am still pretty new to the code base, but this approach seems good. 

You could test this out by modifying an example project, perhaps [this one](https://github.com/cypress-io/cypress/tree/develop/npm/react/examples/webpack-options) would be a good candidate.

As for a test, what are the main use-cases for this?

2020-12-14 12:07 UTC, dmtrKovalenko approved these changes
Please let me know if you want to update other examples, if not – I can push changes to this PR :)

2020-12-14 12:07 UTC, dmtrKovalenko commented on npm/react/docs/recipes.md
> +      preprocessorOptionsFinal(preprocessorOptions) {
Related to naming. I think that we can make it a little bit simpler, we can do the same as next.js doing in config. And this API should be available for all the plugins 

```js
 webpack: (config) => {
    config.module.rules.push({
      test: /\.md$/,
      use: "raw-loader",
    });

    return config;
  },
```

2020-12-14 12:09 UTC, dmtrKovalenko requested changes
Sorry, I miss clicked the review summary. Find the required changes in the previous comment ^

2021-03-02 14:36 UTC, jennifer-shehane commented
@stoically Do you still have time to address the changes requested in this PR? We will have to close this PR due to inactivity otherwise.

2021-03-04 10:31 UTC, stoically commented
@jennifer-shehane No, unfortunately I don't have time to pick this up. Here's still hoping that we see performance improvements for `@cypress/react` in general, since it currently isn't really usable in real world projects as is

2021-03-04 10:32 UTC, closed without merging